// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The BUILT-IN `interface` plugin's OWN CUE schema — the typed plugin_input for the
// `interface` verb (`ip -o addr show <name>` existence + MTU + address probe). It is
// the SINGLE SOURCE for this plugin's params, used two ways (the same contract the
// reference examplerunverb and core `spec` use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by task cue:gen,
//     which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a TYPED
//     struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the builtin serves this source over the
//     Describe channel (InProcTransport) exactly like an external serves it over
//     gRPC; the host splices it onto the base (base ++ plugin) and validates every
//     authored `interface` step's plugin_input against #InterfaceInput.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone (gengotypes +
// the load-gate compile) AND splices onto the base — the base ++ plugin splice exists
// to detect a def-name collision with the base, not to resolve base refs.
//
// `addrs` was a SHARED base #Op field (the now-extracted `dns` plugin also read it),
// but with both `dns` and `interface` extracted it has NO remaining #Op consumer, so it
// is REMOVED from #Op and reproduced standalone here (a bare `[...string]` list, NO def
// reference). `mtu` is interface-specific and likewise leaves #Op. The provider is a
// CheckVerbProvider — it dispatches IN-PROCESS via RunVerb and so keeps the live
// *Runner the probe needs (mirrors examplerunverb).
type InterfaceInput struct {
	// interface — the network interface name to probe (the verb discriminator).
	Interface string `yaml:"interface,omitempty" json:"interface"`

	// mtu — optional expected MTU; when set the probe asserts the interface's MTU.
	MTU *int `yaml:"mtu,omitempty" json:"mtu,omitempty"`

	// addrs — optional required addresses; each must appear in the `ip addr` output.
	Addrs []string `yaml:"addrs,omitempty" json:"addrs,omitempty"`
}
