// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #McpPlugin documents the verb the plugin serves. mcp keeps its entire authoring
// contract (the #McpMethod enum + modifiers) on charly's core #Op, so there is no
// plugin_input to validate here.
type McpPlugin struct {
	Verb string `yaml:"verb,omitempty" json:"verb"`

	Contract string `yaml:"contract,omitempty" json:"contract"`
}
