// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #UdevPlugin documents the command the plugin serves. The command keeps its entire contract in
// its own CLI grammar (parsed from os.Args in CLI mode), so there is no plugin_input to validate
// here.
type UdevPlugin struct {
	Command string `yaml:"command,omitempty" json:"command"`

	Contract string `yaml:"contract,omitempty" json:"contract"`
}
