version: '3'

dotenv: ['.env']

env:
  PATH: "{{.ROOT_DIR}}/bin:{{.PATH}}"

includes:
  build:
    taskfile: ./taskfiles/Build.yml
    dir: "{{.ROOT_DIR}}"
  run:
    taskfile: ./taskfiles/Run.yml
    dir: "{{.ROOT_DIR}}"
  setup:
    taskfile: ./taskfiles/Setup.yml
    dir: "{{.ROOT_DIR}}"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
