// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #ExternalprobeInput — the plugin_input shape for the `externalprobe` verb.
type ExternalprobeInput struct {
	// marker is a NON-EMPTY string the plugin echoes back as the check result
	// message (proving the value round-trips author -> wire -> external process
	// -> result). The `& !=""` constraint is enforced by the host at validate time.
	Marker string `yaml:"marker,omitempty" json:"marker"`
}
