// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The BUILT-IN `init` plugin's OWN CUE schema — the typed input for the `init` KIND
// (the init-system vocabulary: supervisord/systemd, formerly a core `init:` kind
// decoded into the typed core map uf.Init). SINGLE SOURCE for this plugin's params,
// used two ways (the same contract the package-group/agent/module/sidecar/distro/builder
// plugins and core `spec` use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (task cue:gen) →
//     ../params/cue_types_gen.go.
//  2. VALIDATE authored input AT RUNTIME — served over Describe (InProcTransport),
//     spliced base ++ plugin, every authored `init:` body validated against #InitInput
//     BEFORE runPluginKind dispatches.
//
// SELF-CONTAINED: the core #Init (schema/init.cue) already references NO _common.cue
// def, so this is a verbatim reproduction with the inner #InitServiceSchema renamed
// #InServiceSchema (prefix #In) and the @go() annotations dropped (CORE codegen only;
// the validator ignores attributes). The plugin's Invoke canonicalises the body back
// through the core spec.Init type (which InitDef aliases and the generator consumes via
// the Inits() accessor). NAME: the entity name is the node KEY, never a body field —
// #Init has no name field. `model` is the one mandatory field (concrete-validated).
//
// NOTE — the Go package is `initbuiltin` (not `init`, a reserved Go identifier); the
// directory + the kind keyword stay `init`.
type InitInput struct {
	Candy_field []string `yaml:"candy_field,omitempty" json:"candy_field,omitempty"`

	Candy_file []string `yaml:"candy_file,omitempty" json:"candy_file,omitempty"`

	Depends_candy string `yaml:"depends_candy,omitempty" json:"depends_candy,omitempty"`

	Requires_capability []string `yaml:"requires_capability,omitempty" json:"requires_capability,omitempty"`

	// The one mandatory field: the build model.
	Model string `yaml:"model,omitempty" json:"model"`

	Header_file string `yaml:"header_file,omitempty" json:"header_file,omitempty"`

	Fragment_dir string `yaml:"fragment_dir,omitempty" json:"fragment_dir,omitempty"`

	Relay_template string `yaml:"relay_template,omitempty" json:"relay_template,omitempty"`

	Stage_name string `yaml:"stage_name,omitempty" json:"stage_name,omitempty"`

	Stage_header_copy string `yaml:"stage_header_copy,omitempty" json:"stage_header_copy,omitempty"`

	Stage_fragment_copy string `yaml:"stage_fragment_copy,omitempty" json:"stage_fragment_copy,omitempty"`

	Assembly_template string `yaml:"assembly_template,omitempty" json:"assembly_template,omitempty"`

	System_enable_template string `yaml:"system_enable_template,omitempty" json:"system_enable_template,omitempty"`

	Post_assembly_template string `yaml:"post_assembly_template,omitempty" json:"post_assembly_template,omitempty"`

	Entrypoint []string `yaml:"entrypoint,omitempty" json:"entrypoint,omitempty"`

	Fallback_entrypoint []string `yaml:"fallback_entrypoint,omitempty" json:"fallback_entrypoint,omitempty"`

	Management_tool string `yaml:"management_tool,omitempty" json:"management_tool,omitempty"`

	Management_command map[string]string `yaml:"management_command,omitempty" json:"management_command,omitempty"`

	Label_key string `yaml:"label_key,omitempty" json:"label_key,omitempty"`

	Service_schema InServiceSchema `yaml:"service_schema,omitempty" json:"service_schema,omitempty"`
}

type InServiceSchema struct {
	Service_template string `yaml:"service_template,omitempty" json:"service_template,omitempty"`

	Unit_path_template string `yaml:"unit_path_template,omitempty" json:"unit_path_template,omitempty"`

	Dropin_template string `yaml:"dropin_template,omitempty" json:"dropin_template,omitempty"`

	Dropin_path_template string `yaml:"dropin_path_template,omitempty" json:"dropin_path_template,omitempty"`

	Supports_packaged bool `yaml:"supports_packaged,omitempty" json:"supports_packaged,omitempty"`
}
