// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The BUILT-IN `sidecar` plugin's OWN CUE schema — the typed input for the `sidecar`
// KIND (the reusable sidecar-container template library, formerly a core `sidecar:`
// kind decoded into the typed core map uf.Sidecar). It is the SINGLE SOURCE for this
// plugin's params, used two ways (the same contract the reference exampleprobe/process,
// the package-group/agent/module plugins, and core `spec` use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by task cue:gen,
//     which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go.
//  2. VALIDATE authored input AT RUNTIME — the builtin serves this source over the
//     Describe channel (InProcTransport) exactly like an external serves it over
//     gRPC; the host splices it onto the base (base ++ plugin) and validates every
//     authored `sidecar:` entity body against #SidecarInput BEFORE runPluginKind
//     dispatches (validateAuthoredPluginInput(ClassKind, "sidecar", …)) — the
//     kind-class analogue of the verb plugin_input gate.
//
// SELF-CONTAINED: it references NO base def — every shared shape (#ScStrMap value,
// #ScSidecarSecret, #ScSidecarVolume, #ScSecurity, #ScSize) is reproduced standalone
// here, so it compiles standalone (gengotypes + the load-gate compile) AND splices
// onto the base (the base ++ plugin splice exists to detect a def-name collision with
// the base, not to resolve base refs). It is a faithful reproduction of the core
// #Sidecar (schema/sidecar.cue) — the same authored WIRE keys, so the host validates a
// real sidecar entity (incl. the binary-embedded `tailscale` template), and the
// plugin's Invoke canonicalises the body back through the core spec.Sidecar type (which
// SidecarDef aliases and the deploy/quadlet code consumes via the Sidecars() accessor).
//
// NAME: in node-form the entity name is the top-level node KEY, not a body field, so
// the assembled entity body NEVER carries `name`; #Sidecar has no name field either, so
// there is nothing to make optional here.
type SidecarInput struct {
	Description string `yaml:"description,omitempty" json:"description,omitempty"`

	Image string `yaml:"image,omitempty" json:"image,omitempty"`

	// env / parameter are string-coercible maps (#StrMap: values may be a quoted
	// string / number / bool). parameter "" is the "deploy must supply" sentinel.
	Env map[string]any/* CUE disjunction: (bool|string|number) */ `yaml:"env,omitempty" json:"env,omitempty"`

	Parameter map[string]any/* CUE disjunction: (bool|string|number) */ `yaml:"parameter,omitempty" json:"parameter,omitempty"`

	Secret []ScSidecarSecret `yaml:"secret,omitempty" json:"secret,omitempty"`

	Volume []ScSidecarVolume `yaml:"volume,omitempty" json:"volume,omitempty"`

	Security ScSecurity `yaml:"security,omitempty" json:"security,omitempty"`
}

// reproduces #SidecarSecret standalone.
type ScSidecarSecret struct {
	Name string `yaml:"name,omitempty" json:"name"`

	Env string `yaml:"env,omitempty" json:"env"`

	Env_from string `yaml:"env_from,omitempty" json:"env_from,omitempty"`

	Description string `yaml:"description,omitempty" json:"description,omitempty"`
}

// reproduces #SidecarVolume standalone.
type ScSidecarVolume struct {
	Name string `yaml:"name,omitempty" json:"name"`

	Path string `yaml:"path,omitempty" json:"path"`
}

// reproduces #Security (schema/_common.cue) standalone.
type ScSecurity struct {
	Privileged bool `yaml:"privileged,omitempty" json:"privileged,omitempty"`

	Cgroupns string `yaml:"cgroupns,omitempty" json:"cgroupns,omitempty"`

	Cap_add []string `yaml:"cap_add,omitempty" json:"cap_add,omitempty"`

	Devices []string `yaml:"devices,omitempty" json:"devices,omitempty"`

	Security_opt []string `yaml:"security_opt,omitempty" json:"security_opt,omitempty"`

	Ipc_mode string `yaml:"ipc_mode,omitempty" json:"ipc_mode,omitempty"`

	Shm_size ScSize `yaml:"shm_size,omitempty" json:"shm_size,omitempty"`

	Group_add []string `yaml:"group_add,omitempty" json:"group_add,omitempty"`

	Mount []string `yaml:"mount,omitempty" json:"mount,omitempty"`

	Memory_max ScSize `yaml:"memory_max,omitempty" json:"memory_max,omitempty"`

	Memory_high ScSize `yaml:"memory_high,omitempty" json:"memory_high,omitempty"`

	Memory_swap_max ScSize `yaml:"memory_swap_max,omitempty" json:"memory_swap_max,omitempty"`

	Cpus string `yaml:"cpus,omitempty" json:"cpus,omitempty"`
}

// reproduces #Size (schema/_common.cue) standalone.
type ScSize string
