// The charly plugin gRPC contract.
//
// Design (matches the unified Provider model in charly/provider.go): the wire
// carries JSON payloads for the domain types (Op / CheckResult / InstallPlan /
// decoded entities) so the generated `spec` Go structs stay the SINGLE source of
// truth — there is no parallel proto type system to drift (R3). Only the
// control / streaming / handshake envelopes are typed proto.
//
// ONE Provider service mirrors the ONE in-proc Provider interface: a uniform
// Invoke(reserved-word, op, params) keyed by reserved word, plus a streaming
// form for the genuinely-streaming verbs (record / logcat / execute). PluginMeta
// is read once on connect for capability advertisement + CalVer gating.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type Capabilities struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Calver          string                 `protobuf:"bytes,1,opt,name=calver,proto3" json:"calver,omitempty"`                                           // the plugin's CalVer (CalVer is the version authority)
	ProtocolVersion uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // thin secondary gate; never duplicates CalVer
	Provided        []*ProvidedCapability  `protobuf:"bytes,3,rep,name=provided,proto3" json:"provided,omitempty"`                                       // the unit's capabilities + the def validating each input
	SchemaCue       string                 `protobuf:"bytes,4,opt,name=schema_cue,json=schemaCue,proto3" json:"schema_cue,omitempty"`                    // the unit's package-less, SELF-CONTAINED .cue source text
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Capabilities) GetCalver() string {
	if x != nil {
		return x.Calver
	}
	return ""
}

func (x *Capabilities) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Capabilities) GetProvided() []*ProvidedCapability {
	if x != nil {
		return x.Provided
	}
	return nil
}

func (x *Capabilities) GetSchemaCue() string {
	if x != nil {
		return x.SchemaCue
	}
	return ""
}

// ProvidedCapability — one served capability plus the CUE def that validates its
// plugin_input. The schema travels with the plugin over Describe (the same channel
// for in-proc builtin and out-of-proc external — zero distinction), so the host
// validates authored plugin_input against `base ++ served` without ever reading a
// candy's schema/ dir. `input_def` is explicit (no Title-case naming convention).
type ProvidedCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`                       // "verb" / "kind" / "deploy" / "step" / "builder"
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`                         // the reserved word, e.g. "externalprobe"
	InputDef      string                 `protobuf:"bytes,3,opt,name=input_def,json=inputDef,proto3" json:"input_def,omitempty"` // the CUE def for this word's plugin_input, e.g. "#ExternalprobeInput"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvidedCapability) Reset() {
	*x = ProvidedCapability{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvidedCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvidedCapability) ProtoMessage() {}

func (x *ProvidedCapability) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvidedCapability.ProtoReflect.Descriptor instead.
func (*ProvidedCapability) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ProvidedCapability) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ProvidedCapability) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *ProvidedCapability) GetInputDef() string {
	if x != nil {
		return x.InputDef
	}
	return ""
}

type InvokeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Reserved         string                 `protobuf:"bytes,1,opt,name=reserved,proto3" json:"reserved,omitempty"`                                            // the reserved word, e.g. "exampleprobe","cdp","local"
	Op               string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`                                                        // operation selector for the word's class
	ParamsJson       []byte                 `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`                      // the CUE-generated params (Op for verbs/steps; entity for kinds)
	EnvJson          []byte                 `protobuf:"bytes,4,opt,name=env_json,json=envJson,proto3" json:"env_json,omitempty"`                               // snapshotCheckEnv / venue descriptor (serializable invocation ctx)
	Class            string                 `protobuf:"bytes,5,opt,name=class,proto3" json:"class,omitempty"`                                                  // the ProviderClass ("verb"/"kind"/...) — words aren't unique across classes
	ExecutorBrokerId uint32                 `protobuf:"varint,6,opt,name=executor_broker_id,json=executorBrokerId,proto3" json:"executor_broker_id,omitempty"` // E3b: the go-plugin broker id the host serves ExecutorService on for a deploy/step/builder op; 0 = none (verb/kind ops need no executor)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeRequest) GetReserved() string {
	if x != nil {
		return x.Reserved
	}
	return ""
}

func (x *InvokeRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *InvokeRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *InvokeRequest) GetEnvJson() []byte {
	if x != nil {
		return x.EnvJson
	}
	return nil
}

func (x *InvokeRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *InvokeRequest) GetExecutorBrokerId() uint32 {
	if x != nil {
		return x.ExecutorBrokerId
	}
	return 0
}

type InvokeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    []byte                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeReply) Reset() {
	*x = InvokeReply{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeReply) ProtoMessage() {}

func (x *InvokeReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeReply.ProtoReflect.Descriptor instead.
func (*InvokeReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeReply) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    []byte                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Frame) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type VenueReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Venue         string                 `protobuf:"bytes,1,opt,name=venue,proto3" json:"venue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VenueReply) Reset() {
	*x = VenueReply{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VenueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VenueReply) ProtoMessage() {}

func (x *VenueReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VenueReply.ProtoReflect.Descriptor instead.
func (*VenueReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *VenueReply) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	OptsJson      []byte                 `protobuf:"bytes,2,opt,name=opts_json,json=optsJson,proto3" json:"opts_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *RunRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *RunRequest) GetOptsJson() []byte {
	if x != nil {
		return x.OptsJson
	}
	return nil
}

type RunReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunReply) Reset() {
	*x = RunReply{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunReply) ProtoMessage() {}

func (x *RunReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunReply.ProtoReflect.Descriptor instead.
func (*RunReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *RunReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\fcharlyplugin\"\a\n" +
	"\x05Empty\"\xae\x01\n" +
	"\fCapabilities\x12\x16\n" +
	"\x06calver\x18\x01 \x01(\tR\x06calver\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12<\n" +
	"\bprovided\x18\x03 \x03(\v2 .charlyplugin.ProvidedCapabilityR\bprovided\x12\x1d\n" +
	"\n" +
	"schema_cue\x18\x04 \x01(\tR\tschemaCue\"[\n" +
	"\x12ProvidedCapability\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12\x1b\n" +
	"\tinput_def\x18\x03 \x01(\tR\binputDef\"\xbb\x01\n" +
	"\rInvokeRequest\x12\x1a\n" +
	"\breserved\x18\x01 \x01(\tR\breserved\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\fR\n" +
	"paramsJson\x12\x19\n" +
	"\benv_json\x18\x04 \x01(\fR\aenvJson\x12\x14\n" +
	"\x05class\x18\x05 \x01(\tR\x05class\x12,\n" +
	"\x12executor_broker_id\x18\x06 \x01(\rR\x10executorBrokerId\".\n" +
	"\vInvokeReply\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"(\n" +
	"\x05Frame\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson\"\"\n" +
	"\n" +
	"VenueReply\x12\x14\n" +
	"\x05venue\x18\x01 \x01(\tR\x05venue\"A\n" +
	"\n" +
	"RunRequest\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x1b\n" +
	"\topts_json\x18\x02 \x01(\fR\boptsJson\" \n" +
	"\bRunReply\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2I\n" +
	"\n" +
	"PluginMeta\x12;\n" +
	"\bDescribe\x12\x13.charlyplugin.Empty\x1a\x1a.charlyplugin.Capabilities2\x90\x01\n" +
	"\bProvider\x12@\n" +
	"\x06Invoke\x12\x1b.charlyplugin.InvokeRequest\x1a\x19.charlyplugin.InvokeReply\x12B\n" +
	"\fInvokeStream\x12\x1b.charlyplugin.InvokeRequest\x1a\x13.charlyplugin.Frame0\x012\xc5\x01\n" +
	"\x0fExecutorService\x126\n" +
	"\x05Venue\x12\x13.charlyplugin.Empty\x1a\x18.charlyplugin.VenueReply\x12=\n" +
	"\tRunSystem\x12\x18.charlyplugin.RunRequest\x1a\x16.charlyplugin.RunReply\x12;\n" +
	"\aRunUser\x12\x18.charlyplugin.RunRequest\x1a\x16.charlyplugin.RunReplyB6Z4github.com/overthinkos/overthink/charly/plugin/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),              // 0: charlyplugin.Empty
	(*Capabilities)(nil),       // 1: charlyplugin.Capabilities
	(*ProvidedCapability)(nil), // 2: charlyplugin.ProvidedCapability
	(*InvokeRequest)(nil),      // 3: charlyplugin.InvokeRequest
	(*InvokeReply)(nil),        // 4: charlyplugin.InvokeReply
	(*Frame)(nil),              // 5: charlyplugin.Frame
	(*VenueReply)(nil),         // 6: charlyplugin.VenueReply
	(*RunRequest)(nil),         // 7: charlyplugin.RunRequest
	(*RunReply)(nil),           // 8: charlyplugin.RunReply
}
var file_plugin_proto_depIdxs = []int32{
	2, // 0: charlyplugin.Capabilities.provided:type_name -> charlyplugin.ProvidedCapability
	0, // 1: charlyplugin.PluginMeta.Describe:input_type -> charlyplugin.Empty
	3, // 2: charlyplugin.Provider.Invoke:input_type -> charlyplugin.InvokeRequest
	3, // 3: charlyplugin.Provider.InvokeStream:input_type -> charlyplugin.InvokeRequest
	0, // 4: charlyplugin.ExecutorService.Venue:input_type -> charlyplugin.Empty
	7, // 5: charlyplugin.ExecutorService.RunSystem:input_type -> charlyplugin.RunRequest
	7, // 6: charlyplugin.ExecutorService.RunUser:input_type -> charlyplugin.RunRequest
	1, // 7: charlyplugin.PluginMeta.Describe:output_type -> charlyplugin.Capabilities
	4, // 8: charlyplugin.Provider.Invoke:output_type -> charlyplugin.InvokeReply
	5, // 9: charlyplugin.Provider.InvokeStream:output_type -> charlyplugin.Frame
	6, // 10: charlyplugin.ExecutorService.Venue:output_type -> charlyplugin.VenueReply
	8, // 11: charlyplugin.ExecutorService.RunSystem:output_type -> charlyplugin.RunReply
	8, // 12: charlyplugin.ExecutorService.RunUser:output_type -> charlyplugin.RunReply
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
