// The charly plugin gRPC contract.
//
// Design (matches the unified Provider model in charly/provider.go): the wire
// carries JSON payloads for the domain types (Op / CheckResult / InstallPlan /
// decoded entities) so the generated `spec` Go structs stay the SINGLE source of
// truth — there is no parallel proto type system to drift (R3). Only the
// control / streaming / handshake envelopes are typed proto.
//
// ONE Provider service mirrors the ONE in-proc Provider interface: a uniform
// Invoke(reserved-word, op, params) keyed by reserved word, plus a streaming
// form for the genuinely-streaming verbs (record / logcat / execute). PluginMeta
// is read once on connect for capability advertisement + CalVer gating.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PluginMeta_Describe_FullMethodName = "/charlyplugin.PluginMeta/Describe"
)

// PluginMetaClient is the client API for PluginMeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginMetaClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
}

type pluginMetaClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginMetaClient(cc grpc.ClientConnInterface) PluginMetaClient {
	return &pluginMetaClient{cc}
}

func (c *pluginMetaClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, PluginMeta_Describe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginMetaServer is the server API for PluginMeta service.
// All implementations must embed UnimplementedPluginMetaServer
// for forward compatibility
type PluginMetaServer interface {
	Describe(context.Context, *Empty) (*Capabilities, error)
	mustEmbedUnimplementedPluginMetaServer()
}

// UnimplementedPluginMetaServer must be embedded to have forward compatible implementations.
type UnimplementedPluginMetaServer struct {
}

func (UnimplementedPluginMetaServer) Describe(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginMetaServer) mustEmbedUnimplementedPluginMetaServer() {}

// UnsafePluginMetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginMetaServer will
// result in compilation errors.
type UnsafePluginMetaServer interface {
	mustEmbedUnimplementedPluginMetaServer()
}

func RegisterPluginMetaServer(s grpc.ServiceRegistrar, srv PluginMetaServer) {
	s.RegisterService(&PluginMeta_ServiceDesc, srv)
}

func _PluginMeta_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMetaServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMeta_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMetaServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginMeta_ServiceDesc is the grpc.ServiceDesc for PluginMeta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginMeta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.PluginMeta",
	HandlerType: (*PluginMetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PluginMeta_Describe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	Provider_Invoke_FullMethodName       = "/charlyplugin.Provider/Invoke"
	Provider_InvokeStream_FullMethodName = "/charlyplugin.Provider/InvokeStream"
)

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error)
	InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (Provider_InvokeStreamClient, error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error) {
	out := new(InvokeReply)
	err := c.cc.Invoke(ctx, Provider_Invoke_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (Provider_InvokeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[0], Provider_InvokeStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &providerInvokeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Provider_InvokeStreamClient interface {
	Recv() (*Frame, error)
	grpc.ClientStream
}

type providerInvokeStreamClient struct {
	grpc.ClientStream
}

func (x *providerInvokeStreamClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProviderServer is the server API for Provider service.
// All implementations must embed UnimplementedProviderServer
// for forward compatibility
type ProviderServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeReply, error)
	InvokeStream(*InvokeRequest, Provider_InvokeStreamServer) error
	mustEmbedUnimplementedProviderServer()
}

// UnimplementedProviderServer must be embedded to have forward compatible implementations.
type UnimplementedProviderServer struct {
}

func (UnimplementedProviderServer) Invoke(context.Context, *InvokeRequest) (*InvokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedProviderServer) InvokeStream(*InvokeRequest, Provider_InvokeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method InvokeStream not implemented")
}
func (UnimplementedProviderServer) mustEmbedUnimplementedProviderServer() {}

// UnsafeProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServer will
// result in compilation errors.
type UnsafeProviderServer interface {
	mustEmbedUnimplementedProviderServer()
}

func RegisterProviderServer(s grpc.ServiceRegistrar, srv ProviderServer) {
	s.RegisterService(&Provider_ServiceDesc, srv)
}

func _Provider_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_InvokeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServer).InvokeStream(m, &providerInvokeStreamServer{stream})
}

type Provider_InvokeStreamServer interface {
	Send(*Frame) error
	grpc.ServerStream
}

type providerInvokeStreamServer struct {
	grpc.ServerStream
}

func (x *providerInvokeStreamServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

// Provider_ServiceDesc is the grpc.ServiceDesc for Provider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Provider_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeStream",
			Handler:       _Provider_InvokeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
