// The charly plugin gRPC contract.
//
// Design (matches the unified Provider model in charly/provider.go): the wire
// carries JSON payloads for the domain types (Op / CheckResult / InstallPlan /
// decoded entities) so the generated `spec` Go structs stay the SINGLE source of
// truth — there is no parallel proto type system to drift (R3). Only the
// control / streaming / handshake envelopes are typed proto.
//
// ONE Provider service mirrors the ONE in-proc Provider interface: a uniform
// Invoke(reserved-word, op, params) keyed by reserved word, plus a streaming
// form for the genuinely-streaming verbs (record / logcat / execute). PluginMeta
// is read once on connect for capability advertisement + CalVer gating.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PluginMeta_Describe_FullMethodName = "/charlyplugin.PluginMeta/Describe"
)

// PluginMetaClient is the client API for PluginMeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginMetaClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
}

type pluginMetaClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginMetaClient(cc grpc.ClientConnInterface) PluginMetaClient {
	return &pluginMetaClient{cc}
}

func (c *pluginMetaClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, PluginMeta_Describe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginMetaServer is the server API for PluginMeta service.
// All implementations must embed UnimplementedPluginMetaServer
// for forward compatibility
type PluginMetaServer interface {
	Describe(context.Context, *Empty) (*Capabilities, error)
	mustEmbedUnimplementedPluginMetaServer()
}

// UnimplementedPluginMetaServer must be embedded to have forward compatible implementations.
type UnimplementedPluginMetaServer struct {
}

func (UnimplementedPluginMetaServer) Describe(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginMetaServer) mustEmbedUnimplementedPluginMetaServer() {}

// UnsafePluginMetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginMetaServer will
// result in compilation errors.
type UnsafePluginMetaServer interface {
	mustEmbedUnimplementedPluginMetaServer()
}

func RegisterPluginMetaServer(s grpc.ServiceRegistrar, srv PluginMetaServer) {
	s.RegisterService(&PluginMeta_ServiceDesc, srv)
}

func _PluginMeta_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMetaServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMeta_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMetaServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginMeta_ServiceDesc is the grpc.ServiceDesc for PluginMeta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginMeta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.PluginMeta",
	HandlerType: (*PluginMetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PluginMeta_Describe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	Provider_Invoke_FullMethodName       = "/charlyplugin.Provider/Invoke"
	Provider_InvokeStream_FullMethodName = "/charlyplugin.Provider/InvokeStream"
)

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error)
	InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (Provider_InvokeStreamClient, error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error) {
	out := new(InvokeReply)
	err := c.cc.Invoke(ctx, Provider_Invoke_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) InvokeStream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (Provider_InvokeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[0], Provider_InvokeStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &providerInvokeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Provider_InvokeStreamClient interface {
	Recv() (*Frame, error)
	grpc.ClientStream
}

type providerInvokeStreamClient struct {
	grpc.ClientStream
}

func (x *providerInvokeStreamClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProviderServer is the server API for Provider service.
// All implementations must embed UnimplementedProviderServer
// for forward compatibility
type ProviderServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeReply, error)
	InvokeStream(*InvokeRequest, Provider_InvokeStreamServer) error
	mustEmbedUnimplementedProviderServer()
}

// UnimplementedProviderServer must be embedded to have forward compatible implementations.
type UnimplementedProviderServer struct {
}

func (UnimplementedProviderServer) Invoke(context.Context, *InvokeRequest) (*InvokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedProviderServer) InvokeStream(*InvokeRequest, Provider_InvokeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method InvokeStream not implemented")
}
func (UnimplementedProviderServer) mustEmbedUnimplementedProviderServer() {}

// UnsafeProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServer will
// result in compilation errors.
type UnsafeProviderServer interface {
	mustEmbedUnimplementedProviderServer()
}

func RegisterProviderServer(s grpc.ServiceRegistrar, srv ProviderServer) {
	s.RegisterService(&Provider_ServiceDesc, srv)
}

func _Provider_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_InvokeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServer).InvokeStream(m, &providerInvokeStreamServer{stream})
}

type Provider_InvokeStreamServer interface {
	Send(*Frame) error
	grpc.ServerStream
}

type providerInvokeStreamServer struct {
	grpc.ServerStream
}

func (x *providerInvokeStreamServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

// Provider_ServiceDesc is the grpc.ServiceDesc for Provider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Provider_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeStream",
			Handler:       _Provider_InvokeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	ExecutorService_Venue_FullMethodName          = "/charlyplugin.ExecutorService/Venue"
	ExecutorService_RunSystem_FullMethodName      = "/charlyplugin.ExecutorService/RunSystem"
	ExecutorService_RunUser_FullMethodName        = "/charlyplugin.ExecutorService/RunUser"
	ExecutorService_PutFile_FullMethodName        = "/charlyplugin.ExecutorService/PutFile"
	ExecutorService_RunCapture_FullMethodName     = "/charlyplugin.ExecutorService/RunCapture"
	ExecutorService_GetFile_FullMethodName        = "/charlyplugin.ExecutorService/GetFile"
	ExecutorService_RunHostStep_FullMethodName    = "/charlyplugin.ExecutorService/RunHostStep"
	ExecutorService_InvokeProvider_FullMethodName = "/charlyplugin.ExecutorService/InvokeProvider"
	ExecutorService_HostBuild_FullMethodName      = "/charlyplugin.ExecutorService/HostBuild"
	ExecutorService_HostArbiter_FullMethodName    = "/charlyplugin.ExecutorService/HostArbiter"
)

// ExecutorServiceClient is the client API for ExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutorServiceClient interface {
	Venue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VenueReply, error)
	RunSystem(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error)
	RunUser(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error)
	PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileReply, error)
	RunCapture(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*CaptureReply, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileReply, error)
	RunHostStep(ctx context.Context, in *HostStepRequest, opts ...grpc.CallOption) (*HostStepReply, error)
	InvokeProvider(ctx context.Context, in *InvokeProviderRequest, opts ...grpc.CallOption) (*InvokeReply, error)
	HostBuild(ctx context.Context, in *HostBuildRequest, opts ...grpc.CallOption) (*HostBuildReply, error)
	HostArbiter(ctx context.Context, in *HostArbiterRequest, opts ...grpc.CallOption) (*HostArbiterReply, error)
}

type executorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutorServiceClient(cc grpc.ClientConnInterface) ExecutorServiceClient {
	return &executorServiceClient{cc}
}

func (c *executorServiceClient) Venue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VenueReply, error) {
	out := new(VenueReply)
	err := c.cc.Invoke(ctx, ExecutorService_Venue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunSystem(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error) {
	out := new(RunReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunSystem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunUser(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error) {
	out := new(RunReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) PutFile(ctx context.Context, in *PutFileRequest, opts ...grpc.CallOption) (*PutFileReply, error) {
	out := new(PutFileReply)
	err := c.cc.Invoke(ctx, ExecutorService_PutFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunCapture(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*CaptureReply, error) {
	out := new(CaptureReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunCapture_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileReply, error) {
	out := new(GetFileReply)
	err := c.cc.Invoke(ctx, ExecutorService_GetFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) RunHostStep(ctx context.Context, in *HostStepRequest, opts ...grpc.CallOption) (*HostStepReply, error) {
	out := new(HostStepReply)
	err := c.cc.Invoke(ctx, ExecutorService_RunHostStep_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) InvokeProvider(ctx context.Context, in *InvokeProviderRequest, opts ...grpc.CallOption) (*InvokeReply, error) {
	out := new(InvokeReply)
	err := c.cc.Invoke(ctx, ExecutorService_InvokeProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) HostBuild(ctx context.Context, in *HostBuildRequest, opts ...grpc.CallOption) (*HostBuildReply, error) {
	out := new(HostBuildReply)
	err := c.cc.Invoke(ctx, ExecutorService_HostBuild_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) HostArbiter(ctx context.Context, in *HostArbiterRequest, opts ...grpc.CallOption) (*HostArbiterReply, error) {
	out := new(HostArbiterReply)
	err := c.cc.Invoke(ctx, ExecutorService_HostArbiter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutorServiceServer is the server API for ExecutorService service.
// All implementations must embed UnimplementedExecutorServiceServer
// for forward compatibility
type ExecutorServiceServer interface {
	Venue(context.Context, *Empty) (*VenueReply, error)
	RunSystem(context.Context, *RunRequest) (*RunReply, error)
	RunUser(context.Context, *RunRequest) (*RunReply, error)
	PutFile(context.Context, *PutFileRequest) (*PutFileReply, error)
	RunCapture(context.Context, *RunRequest) (*CaptureReply, error)
	GetFile(context.Context, *GetFileRequest) (*GetFileReply, error)
	RunHostStep(context.Context, *HostStepRequest) (*HostStepReply, error)
	InvokeProvider(context.Context, *InvokeProviderRequest) (*InvokeReply, error)
	HostBuild(context.Context, *HostBuildRequest) (*HostBuildReply, error)
	HostArbiter(context.Context, *HostArbiterRequest) (*HostArbiterReply, error)
	mustEmbedUnimplementedExecutorServiceServer()
}

// UnimplementedExecutorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExecutorServiceServer struct {
}

func (UnimplementedExecutorServiceServer) Venue(context.Context, *Empty) (*VenueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Venue not implemented")
}
func (UnimplementedExecutorServiceServer) RunSystem(context.Context, *RunRequest) (*RunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSystem not implemented")
}
func (UnimplementedExecutorServiceServer) RunUser(context.Context, *RunRequest) (*RunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunUser not implemented")
}
func (UnimplementedExecutorServiceServer) PutFile(context.Context, *PutFileRequest) (*PutFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutFile not implemented")
}
func (UnimplementedExecutorServiceServer) RunCapture(context.Context, *RunRequest) (*CaptureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCapture not implemented")
}
func (UnimplementedExecutorServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedExecutorServiceServer) RunHostStep(context.Context, *HostStepRequest) (*HostStepReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunHostStep not implemented")
}
func (UnimplementedExecutorServiceServer) InvokeProvider(context.Context, *InvokeProviderRequest) (*InvokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeProvider not implemented")
}
func (UnimplementedExecutorServiceServer) HostBuild(context.Context, *HostBuildRequest) (*HostBuildReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostBuild not implemented")
}
func (UnimplementedExecutorServiceServer) HostArbiter(context.Context, *HostArbiterRequest) (*HostArbiterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostArbiter not implemented")
}
func (UnimplementedExecutorServiceServer) mustEmbedUnimplementedExecutorServiceServer() {}

// UnsafeExecutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutorServiceServer will
// result in compilation errors.
type UnsafeExecutorServiceServer interface {
	mustEmbedUnimplementedExecutorServiceServer()
}

func RegisterExecutorServiceServer(s grpc.ServiceRegistrar, srv ExecutorServiceServer) {
	s.RegisterService(&ExecutorService_ServiceDesc, srv)
}

func _ExecutorService_Venue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).Venue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_Venue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).Venue(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunSystem(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunUser(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_PutFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).PutFile(ctx, req.(*PutFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunCapture(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_RunHostStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).RunHostStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_RunHostStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).RunHostStep(ctx, req.(*HostStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_InvokeProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).InvokeProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_InvokeProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).InvokeProvider(ctx, req.(*InvokeProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_HostBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).HostBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_HostBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).HostBuild(ctx, req.(*HostBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_HostArbiter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostArbiterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).HostArbiter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_HostArbiter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).HostArbiter(ctx, req.(*HostArbiterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutorService_ServiceDesc is the grpc.ServiceDesc for ExecutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.ExecutorService",
	HandlerType: (*ExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Venue",
			Handler:    _ExecutorService_Venue_Handler,
		},
		{
			MethodName: "RunSystem",
			Handler:    _ExecutorService_RunSystem_Handler,
		},
		{
			MethodName: "RunUser",
			Handler:    _ExecutorService_RunUser_Handler,
		},
		{
			MethodName: "PutFile",
			Handler:    _ExecutorService_PutFile_Handler,
		},
		{
			MethodName: "RunCapture",
			Handler:    _ExecutorService_RunCapture_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _ExecutorService_GetFile_Handler,
		},
		{
			MethodName: "RunHostStep",
			Handler:    _ExecutorService_RunHostStep_Handler,
		},
		{
			MethodName: "InvokeProvider",
			Handler:    _ExecutorService_InvokeProvider_Handler,
		},
		{
			MethodName: "HostBuild",
			Handler:    _ExecutorService_HostBuild_Handler,
		},
		{
			MethodName: "HostArbiter",
			Handler:    _ExecutorService_HostArbiter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	CheckContextService_HTTPDo_FullMethodName        = "/charlyplugin.CheckContextService/HTTPDo"
	CheckContextService_AddBackground_FullMethodName = "/charlyplugin.CheckContextService/AddBackground"
)

// CheckContextServiceClient is the client API for CheckContextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckContextServiceClient interface {
	HTTPDo(ctx context.Context, in *HTTPDoRequest, opts ...grpc.CallOption) (*HTTPDoReply, error)
	AddBackground(ctx context.Context, in *AddBackgroundRequest, opts ...grpc.CallOption) (*Empty, error)
}

type checkContextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckContextServiceClient(cc grpc.ClientConnInterface) CheckContextServiceClient {
	return &checkContextServiceClient{cc}
}

func (c *checkContextServiceClient) HTTPDo(ctx context.Context, in *HTTPDoRequest, opts ...grpc.CallOption) (*HTTPDoReply, error) {
	out := new(HTTPDoReply)
	err := c.cc.Invoke(ctx, CheckContextService_HTTPDo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkContextServiceClient) AddBackground(ctx context.Context, in *AddBackgroundRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CheckContextService_AddBackground_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckContextServiceServer is the server API for CheckContextService service.
// All implementations must embed UnimplementedCheckContextServiceServer
// for forward compatibility
type CheckContextServiceServer interface {
	HTTPDo(context.Context, *HTTPDoRequest) (*HTTPDoReply, error)
	AddBackground(context.Context, *AddBackgroundRequest) (*Empty, error)
	mustEmbedUnimplementedCheckContextServiceServer()
}

// UnimplementedCheckContextServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCheckContextServiceServer struct {
}

func (UnimplementedCheckContextServiceServer) HTTPDo(context.Context, *HTTPDoRequest) (*HTTPDoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HTTPDo not implemented")
}
func (UnimplementedCheckContextServiceServer) AddBackground(context.Context, *AddBackgroundRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBackground not implemented")
}
func (UnimplementedCheckContextServiceServer) mustEmbedUnimplementedCheckContextServiceServer() {}

// UnsafeCheckContextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckContextServiceServer will
// result in compilation errors.
type UnsafeCheckContextServiceServer interface {
	mustEmbedUnimplementedCheckContextServiceServer()
}

func RegisterCheckContextServiceServer(s grpc.ServiceRegistrar, srv CheckContextServiceServer) {
	s.RegisterService(&CheckContextService_ServiceDesc, srv)
}

func _CheckContextService_HTTPDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPDoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckContextServiceServer).HTTPDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckContextService_HTTPDo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckContextServiceServer).HTTPDo(ctx, req.(*HTTPDoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckContextService_AddBackground_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBackgroundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckContextServiceServer).AddBackground(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckContextService_AddBackground_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckContextServiceServer).AddBackground(ctx, req.(*AddBackgroundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckContextService_ServiceDesc is the grpc.ServiceDesc for CheckContextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckContextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "charlyplugin.CheckContextService",
	HandlerType: (*CheckContextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HTTPDo",
			Handler:    _CheckContextService_HTTPDo_Handler,
		},
		{
			MethodName: "AddBackground",
			Handler:    _CheckContextService_AddBackground_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
