// Command plugin-example-external is the reference OUT-OF-TREE charly plugin: a
// standalone binary (its own Go module) that serves the `externalprobe` check verb
// over go-plugin gRPC via the charly plugin SDK. charly's git-repo plugin loader
// fetches this candy's repo, `go build`s it on the host, and connects to it
// out-of-process — proving an external plugin's verb dispatches transport-
// invisibly through the provider registry, exactly like a built-in.
package main

import (
	"context"
	"embed"
	"encoding/json"

	"github.com/overthinkos/overthink/candy/plugin-example-external/params"
	pb "github.com/overthinkos/overthink/charly/plugin/proto"
	"github.com/overthinkos/overthink/charly/plugin/sdk"
)

//go:embed schema/*.cue
var schemaFS embed.FS

func main() { sdk.Serve(&provider{}, &meta{}) }

type provider struct{ pb.UnimplementedProviderServer }

// Invoke handles the `externalprobe` verb: returns a deterministic pass, echoing
// plugin_input.marker so a bed can assert the value travelled author → wire →
// external process → result (the params round-trip across the process boundary).
func (provider) Invoke(_ context.Context, req *pb.InvokeRequest) (*pb.InvokeReply, error) {
	// Decode plugin_input into the CUE-GENERATED typed struct (params.ExternalprobeInput,
	// generated by `cue exp gengotypes` from schema/externalprobe.cue) — never a
	// hand-parsed map. The host has already validated the authored input against the
	// same CUE def (base ++ plugin), so Marker is well-formed here.
	var in struct {
		PluginInput params.ExternalprobeInput `json:"plugin_input"`
	}
	if len(req.GetParamsJson()) > 0 {
		_ = json.Unmarshal(req.GetParamsJson(), &in)
	}
	marker := in.PluginInput.Marker
	if marker == "" {
		marker = "externalprobe-ok"
	}
	j, err := json.Marshal(map[string]string{"status": "pass", "message": marker})
	if err != nil {
		return nil, err
	}
	return &pb.InvokeReply{ResultJson: j}, nil
}

type meta struct {
	pb.UnimplementedPluginMetaServer
}

// Describe ships the plugin's capabilities AND its self-contained CUE schema over
// the wire via sdk.BuildCapabilities — the schema travels with the plugin, so the
// host validates authored plugin_input against base ++ this schema, identically to
// a built-in. The SDK compiles the schema standalone here, failing loudly before
// serving if it is broken or empty.
func (meta) Describe(context.Context, *pb.Empty) (*pb.Capabilities, error) {
	return sdk.BuildCapabilities("2026.172.0001",
		[]sdk.ProvidedCapability{{Class: "verb", Word: "externalprobe", InputDef: "#ExternalprobeInput"}},
		schemaFS, "schema")
}
