package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// QuadletConfig holds the parameters for generating a quadlet .container file
type QuadletConfig struct {
	ImageName   string              // image name from images.yml (e.g. "fedora-test")
	ImageRef    string              // full image reference (e.g. "ghcr.io/overthinkos/fedora-test:latest")
	Workspace   string              // absolute host path to mount at /workspace
	Ports       []string            // port mappings from images.yml (e.g. ["8000:8000", "8080:8080"])
	Volumes     []VolumeMount       // named volumes from layer.yml declarations
	BindMounts  []ResolvedBindMount // bind mounts from images.yml
	GPU         bool                // enable GPU passthrough via CDI (AddDevice=nvidia.com/gpu=all)
	BindAddress string              // host bind address for port publishing (e.g. "127.0.0.1" or "0.0.0.0")
	Tunnel      *TunnelConfig       // tunnel configuration (nil if no tunnel)
	UID         int                 // container user UID (for UserNS keep-id mapping)
	GID         int                 // container user GID (for UserNS keep-id mapping)
	Env         []string            // runtime env vars (KEY=VALUE pairs)
	EnvFile     string              // absolute path to env file for EnvironmentFile= directive
	Instance    string              // instance name for running multiple containers of same image
	Security    SecurityConfig      // container security options
	Network     string              // container network mode (e.g. "host", "none")
	Version     string              // image definition version (CalVer)
	Status      string              // effective status (working, testing, broken)
	Info        string              // status description
	Secrets     []CollectedSecret   // container secrets (podman Secret= directives)
}

// generateQuadlet produces the contents of a quadlet .container file.
func generateQuadlet(cfg QuadletConfig) string {
	name := containerNameInstance(cfg.ImageName, cfg.Instance)
	var b strings.Builder

	desc := cfg.ImageName
	if cfg.Instance != "" {
		desc = cfg.ImageName + " (" + cfg.Instance + ")"
	}
	b.WriteString(fmt.Sprintf("# %s.container (generated by ov enable)\n", name))
	if cfg.Version != "" {
		b.WriteString(fmt.Sprintf("# Version: %s\n", cfg.Version))
	}
	status := resolveStatus(cfg.Status)
	if status != "working" {
		b.WriteString(fmt.Sprintf("# Status: %s\n", status))
		if cfg.Info != "" {
			b.WriteString(fmt.Sprintf("# Info: %s\n", cfg.Info))
		}
	}
	b.WriteString("[Unit]\n")
	b.WriteString(fmt.Sprintf("Description=Overthink %s\n", desc))
	b.WriteString("After=network-online.target\n")
	if hasEncryptedBindMounts(cfg.BindMounts) {
		encSvc := encServiceFilename(cfg.ImageName)
		b.WriteString(fmt.Sprintf("Requires=%s\n", encSvc))
		b.WriteString(fmt.Sprintf("After=%s\n", encSvc))
	}

	b.WriteString("\n[Container]\n")
	b.WriteString(fmt.Sprintf("Image=%s\n", cfg.ImageRef))
	b.WriteString(fmt.Sprintf("ContainerName=%s\n", name))
	b.WriteString(fmt.Sprintf("Volume=%s:/workspace\n", cfg.Workspace))
	b.WriteString("WorkingDir=/workspace\n")
	if cfg.Network != "" {
		b.WriteString(fmt.Sprintf("Network=%s\n", cfg.Network))
	}
	for _, port := range cfg.Ports {
		b.WriteString(fmt.Sprintf("PublishPort=%s\n", localizePort(port, cfg.BindAddress)))
	}
	for _, vol := range cfg.Volumes {
		b.WriteString(fmt.Sprintf("Volume=%s:%s\n", vol.VolumeName, vol.ContainerPath))
	}
	for _, bm := range cfg.BindMounts {
		b.WriteString(fmt.Sprintf("Volume=%s:%s\n", bm.HostPath, bm.ContPath))
	}
	for _, m := range cfg.Security.Mounts {
		if strings.HasPrefix(m, "tmpfs:") {
			// tmpfs:/path:options → Tmpfs=/path:options
			b.WriteString(fmt.Sprintf("Tmpfs=%s\n", strings.TrimPrefix(m, "tmpfs:")))
		} else {
			b.WriteString(fmt.Sprintf("Volume=%s\n", m))
		}
	}
	for _, s := range cfg.Secrets {
		b.WriteString(fmt.Sprintf("Secret=%s,target=%s\n", s.Name, s.Target))
	}
	if cfg.GPU && !cfg.Security.Privileged {
		b.WriteString("AddDevice=nvidia.com/gpu=all\n")
	}
	if cfg.Security.Privileged {
		b.WriteString("SecurityLabelDisable=true\n")
		b.WriteString("PodmanArgs=--privileged\n")
		// Pass security_opt even when privileged — nested containers need explicit opts
		for _, opt := range cfg.Security.SecurityOpt {
			if opt != "label=disable" { // already handled by SecurityLabelDisable
				b.WriteString(fmt.Sprintf("PodmanArgs=--security-opt %s\n", opt))
			}
		}
	} else {
		for _, cap := range cfg.Security.CapAdd {
			b.WriteString(fmt.Sprintf("AddCapability=%s\n", cap))
		}
		for _, dev := range cfg.Security.Devices {
			b.WriteString(fmt.Sprintf("AddDevice=%s\n", dev))
		}
		for _, opt := range cfg.Security.SecurityOpt {
			if opt == "label=disable" {
				b.WriteString("SecurityLabelDisable=true\n")
			} else {
				b.WriteString(fmt.Sprintf("PodmanArgs=--security-opt %s\n", opt))
			}
		}
	}
	for _, group := range cfg.Security.GroupAdd {
		b.WriteString(fmt.Sprintf("GroupAdd=%s\n", group))
	}
	if cfg.Security.ShmSize != "" {
		b.WriteString(fmt.Sprintf("ShmSize=%s\n", cfg.Security.ShmSize))
	}
	if len(cfg.BindMounts) > 0 {
		b.WriteString(fmt.Sprintf("UserNS=keep-id:uid=%d,gid=%d\n", cfg.UID, cfg.GID))
	}
	for _, e := range cfg.Env {
		b.WriteString(fmt.Sprintf("Environment=%s\n", e))
	}
	if cfg.EnvFile != "" {
		b.WriteString(fmt.Sprintf("EnvironmentFile=%s\n", cfg.EnvFile))
	}
	b.WriteString("Exec=supervisord -n -c /etc/supervisord.conf\n")

	b.WriteString("\n[Service]\n")
	b.WriteString("Restart=always\n")
	b.WriteString("TimeoutStartSec=900\n")
	if cfg.Tunnel != nil && cfg.Tunnel.Provider == "tailscale" && len(cfg.Tunnel.Ports) > 0 {
		for _, tp := range cfg.Tunnel.Ports {
			port := fmt.Sprintf("%d", tp.Port)
			if tp.Protocol == "udp" {
				b.WriteString(fmt.Sprintf("# Port %s: UDP — not tunneled (tailscale serve does not support UDP; accessible directly between tailnet nodes)\n", port))
			} else if tp.Public {
				b.WriteString(fmt.Sprintf("# Port %s: public (internet-accessible)\n", port))
				b.WriteString(fmt.Sprintf("ExecStartPost=tailscale funnel --bg --https=%s http://127.0.0.1:%s\n", port, port))
			} else if tp.Protocol == "tcp" {
				b.WriteString(fmt.Sprintf("# Port %s: private (tailnet-only, tcp)\n", port))
				b.WriteString(fmt.Sprintf("ExecStartPost=tailscale serve --bg --tcp=%s tcp://127.0.0.1:%s\n", port, port))
			} else {
				b.WriteString(fmt.Sprintf("# Port %s: private (tailnet-only)\n", port))
				b.WriteString(fmt.Sprintf("ExecStartPost=tailscale serve --bg --https=%s http://127.0.0.1:%s\n", port, port))
			}
		}
		for _, tp := range cfg.Tunnel.Ports {
			if tp.Protocol == "udp" {
				continue // UDP ports have no tunnel commands to stop
			}
			port := fmt.Sprintf("%d", tp.Port)
			if tp.Public {
				b.WriteString(fmt.Sprintf("ExecStopPost=-tailscale funnel %s off\n", port))
			} else if tp.Protocol == "tcp" {
				b.WriteString(fmt.Sprintf("ExecStopPost=-tailscale serve --tcp=%s off\n", port))
			} else {
				b.WriteString(fmt.Sprintf("ExecStopPost=-tailscale serve --https=%s off\n", port))
			}
		}
	}

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")

	return b.String()
}

// generateTunnelUnit produces a companion systemd service unit for cloudflare tunnels.
func generateTunnelUnit(cfg QuadletConfig) string {
	if cfg.Tunnel == nil || cfg.Tunnel.Provider != "cloudflare" {
		return ""
	}

	name := containerName(cfg.ImageName)
	tunnelName := cfg.Tunnel.TunnelName

	cfgPath, _ := tunnelConfigPath(tunnelName)

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# %s-tunnel.service (generated by ov enable)\n", name))
	b.WriteString("[Unit]\n")
	b.WriteString(fmt.Sprintf("Description=Cloudflare Tunnel for %s\n", name))
	b.WriteString(fmt.Sprintf("BindsTo=%s.service\n", name))
	b.WriteString(fmt.Sprintf("After=%s.service\n", name))

	b.WriteString("\n[Service]\n")
	b.WriteString(fmt.Sprintf("ExecStart=cloudflared tunnel --config %s run %s\n", cfgPath, tunnelName))
	b.WriteString("Restart=always\n")

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")

	return b.String()
}

// tunnelServiceFilename returns the systemd service filename for a tunnel companion unit.
func tunnelServiceFilename(imageName string) string {
	return containerName(imageName) + "-tunnel.service"
}

// quadletDir returns the user-level quadlet directory.
func quadletDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("determining home directory: %w", err)
	}
	return filepath.Join(home, ".config", "containers", "systemd"), nil
}

// systemdUserDir returns the user-level systemd unit directory (~/.config/systemd/user/).
func systemdUserDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("determining home directory: %w", err)
	}
	return filepath.Join(home, ".config", "systemd", "user"), nil
}

// quadletFilename returns the quadlet filename for an image.
func quadletFilename(imageName string) string {
	return containerName(imageName) + ".container"
}

// quadletFilenameInstance returns the quadlet filename for an image with optional instance.
func quadletFilenameInstance(imageName, instance string) string {
	return containerNameInstance(imageName, instance) + ".container"
}

// serviceName returns the systemd service name for an image.
func serviceName(imageName string) string {
	return containerName(imageName) + ".service"
}

// serviceNameInstance returns the systemd service name for an image with optional instance.
func serviceNameInstance(imageName, instance string) string {
	return containerNameInstance(imageName, instance) + ".service"
}

// quadletExists checks whether a .container file exists for the given image.
func quadletExists(imageName string) (bool, error) {
	return quadletExistsInstance(imageName, "")
}

// quadletExistsInstance checks whether a .container file exists for the given image/instance.
func quadletExistsInstance(imageName, instance string) (bool, error) {
	qdir, err := quadletDir()
	if err != nil {
		return false, err
	}
	qpath := filepath.Join(qdir, quadletFilenameInstance(imageName, instance))
	_, err = os.Stat(qpath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}
