package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// QuadletConfig holds the parameters for generating a quadlet .container file
type QuadletConfig struct {
	ImageName   string              // image name from image.yml (e.g. "fedora-test")
	ImageRef    string              // full image reference (e.g. "ghcr.io/overthinkos/fedora-test:latest")
	Home        string              // container home directory (for WorkingDir resolution)
	Ports       []string            // port mappings from image.yml (e.g. ["8000:8000", "8080:8080"])
	Volumes     []VolumeMount       // named volumes from layer.yml declarations
	BindMounts  []ResolvedBindMount // bind-backed volumes from deploy config
	GPU         bool                // enable GPU passthrough via CDI (AddDevice=nvidia.com/gpu=all)
	BindAddress string              // host bind address for port publishing (e.g. "127.0.0.1" or "0.0.0.0")
	Tunnel      *TunnelConfig       // tunnel configuration (nil if no tunnel)
	UID         int                 // container user UID (for UserNS keep-id mapping)
	GID         int                 // container user GID (for UserNS keep-id mapping)
	Env         []string            // runtime env vars (KEY=VALUE pairs)
	EnvFile     string              // absolute path to env file for EnvironmentFile= directive
	Instance    string              // instance name for running multiple containers of same image
	Security       SecurityConfig      // container security options
	Network        string              // container network mode (e.g. "host", "none")
	Version        string              // image definition version (CalVer)
	Status         string              // effective status (working, testing, broken)
	Info           string              // status description
	Secrets        []CollectedSecret   // container secrets (podman Secret= directives)
	Entrypoint     []string            // init system entrypoint (e.g., ["supervisord", "-n", "-c", "/etc/supervisord.conf"])
	OvBin          string              // absolute path to ov binary (for ExecStartPre)
	EncryptedMounts bool               // true when any bind mount is encrypted
	KeyringBackend  bool               // true when credential store is Secret Service (keyring)
	PodName        string              // non-empty when this container belongs to a pod (sidecar mode)
	Sidecars       []ResolvedSidecar   // sidecar definitions (used to detect tailscale sidecar for tunnel)
}

// generateQuadlet produces the contents of a quadlet .container file.
func generateQuadlet(cfg QuadletConfig) string {
	name := containerNameInstance(cfg.ImageName, cfg.Instance)
	var b strings.Builder

	desc := cfg.ImageName
	if cfg.Instance != "" {
		desc = cfg.ImageName + " (" + cfg.Instance + ")"
	}
	b.WriteString(fmt.Sprintf("# %s.container (generated by ov config)\n", name))
	if cfg.Version != "" {
		b.WriteString(fmt.Sprintf("# Version: %s\n", cfg.Version))
	}
	status := resolveStatus(cfg.Status)
	if status != "working" {
		b.WriteString(fmt.Sprintf("# Status: %s\n", status))
		if cfg.Info != "" {
			b.WriteString(fmt.Sprintf("# Info: %s\n", cfg.Info))
		}
	}
	b.WriteString("[Unit]\n")
	b.WriteString(fmt.Sprintf("Description=Overthink %s\n", desc))
	b.WriteString("After=network-online.target\n")
	if cfg.Tunnel != nil && cfg.Tunnel.Provider == "cloudflare" {
		tunnelSvc := tunnelServiceFilename(cfg.ImageName)
		b.WriteString(fmt.Sprintf("Wants=%s\n", tunnelSvc))
	}

	b.WriteString("\n[Container]\n")
	if cfg.PodName != "" {
		b.WriteString(fmt.Sprintf("Pod=%s.pod\n", cfg.PodName))
	}
	b.WriteString(fmt.Sprintf("Image=%s\n", cfg.ImageRef))
	b.WriteString(fmt.Sprintf("ContainerName=%s\n", name))
	workDir := resolveWorkingDir(cfg.Volumes, cfg.BindMounts, cfg.Home)
	b.WriteString(fmt.Sprintf("WorkingDir=%s\n", workDir))
	// When in a pod, network and ports are owned by the pod (shared namespace)
	if cfg.PodName == "" {
		if cfg.Network != "" {
			b.WriteString(fmt.Sprintf("Network=%s\n", cfg.Network))
		}
		for _, port := range cfg.Ports {
			b.WriteString(fmt.Sprintf("PublishPort=%s\n", localizePort(port, cfg.BindAddress)))
		}
	}
	for _, vol := range cfg.Volumes {
		b.WriteString(fmt.Sprintf("Volume=%s:%s\n", vol.VolumeName, vol.ContainerPath))
	}
	for _, bm := range cfg.BindMounts {
		b.WriteString(fmt.Sprintf("Volume=%s:%s\n", bm.HostPath, bm.ContPath))
	}
	for _, m := range cfg.Security.Mounts {
		if strings.HasPrefix(m, "tmpfs:") {
			// tmpfs:/path:options → Tmpfs=/path:options
			b.WriteString(fmt.Sprintf("Tmpfs=%s\n", strings.TrimPrefix(m, "tmpfs:")))
		} else {
			b.WriteString(fmt.Sprintf("Volume=%s\n", m))
		}
	}
	for _, s := range cfg.Secrets {
		if s.Env != "" {
			b.WriteString(fmt.Sprintf("Secret=%s,type=env,target=%s\n", s.Name, s.Env))
		} else {
			b.WriteString(fmt.Sprintf("Secret=%s,target=%s\n", s.Name, s.Target))
		}
	}
	if cfg.GPU && !cfg.Security.Privileged {
		b.WriteString("AddDevice=nvidia.com/gpu=all\n")
	}
	if cfg.Security.Privileged {
		b.WriteString("SecurityLabelDisable=true\n")
		b.WriteString("PodmanArgs=--privileged\n")
		// Pass security_opt even when privileged — nested containers need explicit opts
		for _, opt := range cfg.Security.SecurityOpt {
			if opt != "label=disable" { // already handled by SecurityLabelDisable
				b.WriteString(fmt.Sprintf("PodmanArgs=--security-opt %s\n", opt))
			}
		}
	} else {
		for _, cap := range cfg.Security.CapAdd {
			b.WriteString(fmt.Sprintf("AddCapability=%s\n", cap))
		}
		for _, dev := range cfg.Security.Devices {
			b.WriteString(fmt.Sprintf("AddDevice=%s\n", dev))
		}
		for _, opt := range cfg.Security.SecurityOpt {
			if opt == "label=disable" {
				b.WriteString("SecurityLabelDisable=true\n")
			} else {
				b.WriteString(fmt.Sprintf("PodmanArgs=--security-opt %s\n", opt))
			}
		}
	}
	for _, group := range cfg.Security.GroupAdd {
		b.WriteString(fmt.Sprintf("GroupAdd=%s\n", group))
	}
	if cfg.Security.ShmSize != "" && cfg.PodName == "" {
		// In pod mode, ShmSize is set on the pod (infra container owns /dev/shm)
		b.WriteString(fmt.Sprintf("ShmSize=%s\n", cfg.Security.ShmSize))
	}
	if len(cfg.BindMounts) > 0 {
		b.WriteString(fmt.Sprintf("UserNS=keep-id:uid=%d,gid=%d\n", cfg.UID, cfg.GID))
	}
	for _, e := range cfg.Env {
		// Quote the value if it contains characters that systemd would interpret
		if idx := strings.IndexByte(e, '='); idx >= 0 {
			key := e[:idx]
			val := e[idx+1:]
			if strings.ContainsAny(val, `"{}[] `) {
				b.WriteString(fmt.Sprintf("Environment=%s=%q\n", key, val))
			} else {
				b.WriteString(fmt.Sprintf("Environment=%s\n", e))
			}
		} else {
			b.WriteString(fmt.Sprintf("Environment=%s\n", e))
		}
	}
	if cfg.EnvFile != "" {
		b.WriteString(fmt.Sprintf("EnvironmentFile=%s\n", cfg.EnvFile))
	}
	if len(cfg.Entrypoint) > 0 {
		b.WriteString(fmt.Sprintf("Exec=%s\n", strings.Join(cfg.Entrypoint, " ")))
	} else {
		b.WriteString("Exec=sleep infinity\n")
	}

	b.WriteString("\n[Service]\n")
	b.WriteString("Restart=always\n")
	// Resource caps. Emitted as native systemd cgroup directives so they apply
	// to the container's cgroup slice regardless of podman version. MemoryHigh
	// acts as a soft limit (reclaim pressure), MemoryMax is the hard OOM line.
	// Size values are normalized to uppercase suffixes (K/M/G/T) because systemd
	// silently rejects lowercase and falls back to "infinity" — verified the hard
	// way against a live systemctl show against this exact unit.
	if v := normalizeCgroupSize(cfg.Security.MemoryMax); v != "" {
		b.WriteString(fmt.Sprintf("MemoryMax=%s\n", v))
	}
	if v := normalizeCgroupSize(cfg.Security.MemoryHigh); v != "" {
		b.WriteString(fmt.Sprintf("MemoryHigh=%s\n", v))
	}
	if v := normalizeCgroupSize(cfg.Security.MemorySwapMax); v != "" {
		b.WriteString(fmt.Sprintf("MemorySwapMax=%s\n", v))
	}
	if q := formatCPUQuota(cfg.Security.Cpus); q != "" {
		b.WriteString(fmt.Sprintf("CPUQuota=%s\n", q))
	}
	if cfg.EncryptedMounts && cfg.OvBin != "" {
		imgArg := cfg.ImageName
		if cfg.Instance != "" {
			imgArg = cfg.ImageName + " -i " + cfg.Instance
		}
		b.WriteString(fmt.Sprintf("ExecStartPre=%s config mount %s\n", cfg.OvBin, imgArg))
		if cfg.KeyringBackend {
			// Wait indefinitely for keyring unlock (PAM login)
			b.WriteString("TimeoutStartSec=0\n")
		} else {
			b.WriteString("TimeoutStartSec=900\n")
		}
	} else {
		b.WriteString("TimeoutStartSec=900\n")
	}
	// Host-based tailscale serve/funnel: always generated when tunnel: tailscale is configured.
	// Independent of sidecars — the host tunnel serves ports on the host's tailnet,
	// while the sidecar handles exit node routing on a potentially different tailnet.
	if cfg.Tunnel != nil && cfg.Tunnel.Provider == "tailscale" && len(cfg.Tunnel.Ports) > 0 {
		for _, tp := range cfg.Tunnel.Ports {
			port := fmt.Sprintf("%d", tp.Port)
			if tp.Protocol == "udp" {
				b.WriteString(fmt.Sprintf("# Port %s: UDP — not tunneled (tailscale serve does not support UDP; accessible directly between tailnet nodes)\n", port))
			} else if tp.Public {
				flag := tailscaleFlag(tp.Protocol)
				target := schemeTarget(tp.Protocol, tp.backend())
				b.WriteString(fmt.Sprintf("# Port %s: public (internet-accessible)\n", port))
				b.WriteString(fmt.Sprintf("ExecStartPost=tailscale funnel --bg %s=%s %s\n", flag, port, target))
			} else {
				flag := tailscaleFlag(tp.Protocol)
				target := schemeTarget(tp.Protocol, tp.backend())
				proto := "https"
				if isTCPFamily(tp.Protocol) {
					proto = "tcp"
				}
				b.WriteString(fmt.Sprintf("# Port %s: private (tailnet-only, %s)\n", port, proto))
				b.WriteString(fmt.Sprintf("ExecStartPost=tailscale serve --bg %s=%s %s\n", flag, port, target))
			}
		}
		for _, tp := range cfg.Tunnel.Ports {
			if tp.Protocol == "udp" {
				continue // UDP ports have no tunnel commands to stop
			}
			port := fmt.Sprintf("%d", tp.Port)
			flag := tailscaleFlag(tp.Protocol)
			if tp.Public {
				b.WriteString(fmt.Sprintf("ExecStopPost=-tailscale funnel %s=%s off\n", flag, port))
			} else {
				b.WriteString(fmt.Sprintf("ExecStopPost=-tailscale serve %s=%s off\n", flag, port))
			}
		}
	}

	b.WriteString("\n[Install]\n")
	if cfg.EncryptedMounts && !cfg.KeyringBackend {
		// Non-keyring backends can't auto-unlock at boot; require manual ov start
		b.WriteString("# Encrypted volumes require 'ov start' (no keyring auto-unlock)\n")
	} else {
		b.WriteString("WantedBy=default.target\n")
	}

	return b.String()
}

// generateTunnelUnit produces a companion systemd service unit for cloudflare tunnels.
func generateTunnelUnit(cfg QuadletConfig) string {
	if cfg.Tunnel == nil || cfg.Tunnel.Provider != "cloudflare" {
		return ""
	}

	name := containerName(cfg.ImageName)
	tunnelName := cfg.Tunnel.TunnelName

	cfgPath, _ := tunnelConfigPath(tunnelName)

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# %s-tunnel.service (generated by ov config)\n", name))
	b.WriteString("[Unit]\n")
	b.WriteString(fmt.Sprintf("Description=Cloudflare Tunnel for %s\n", name))
	b.WriteString(fmt.Sprintf("BindsTo=%s.service\n", name))
	b.WriteString(fmt.Sprintf("After=%s.service\n", name))

	b.WriteString("\n[Service]\n")
	b.WriteString(fmt.Sprintf("ExecStart=cloudflared tunnel --config %s run %s\n", cfgPath, tunnelName))
	b.WriteString("Restart=always\n")

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")

	return b.String()
}

// tunnelServiceFilename returns the systemd service filename for a tunnel companion unit.
func tunnelServiceFilename(imageName string) string {
	return containerName(imageName) + "-tunnel.service"
}

// quadletDir returns the user-level quadlet directory.
func quadletDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("determining home directory: %w", err)
	}
	return filepath.Join(home, ".config", "containers", "systemd"), nil
}

// systemdUserDir returns the user-level systemd unit directory (~/.config/systemd/user/).
func systemdUserDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("determining home directory: %w", err)
	}
	return filepath.Join(home, ".config", "systemd", "user"), nil
}

// quadletFilename returns the quadlet filename for an image.
func quadletFilename(imageName string) string {
	return containerName(imageName) + ".container"
}

// quadletFilenameInstance returns the quadlet filename for an image with optional instance.
func quadletFilenameInstance(imageName, instance string) string {
	return containerNameInstance(imageName, instance) + ".container"
}

// serviceName returns the systemd service name for an image.
func serviceName(imageName string) string {
	return containerName(imageName) + ".service"
}

// serviceNameInstance returns the systemd service name for an image with optional instance.
func serviceNameInstance(imageName, instance string) string {
	return containerNameInstance(imageName, instance) + ".service"
}

// quadletExists checks whether a .container file exists for the given image.
func quadletExists(imageName string) (bool, error) {
	return quadletExistsInstance(imageName, "")
}

// quadletExistsInstance checks whether a .container file exists for the given image/instance.
func quadletExistsInstance(imageName, instance string) (bool, error) {
	qdir, err := quadletDir()
	if err != nil {
		return false, err
	}
	qpath := filepath.Join(qdir, quadletFilenameInstance(imageName, instance))
	_, err = os.Stat(qpath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// normalizeCgroupSize converts a podman-style size string ("6g", "512m") into
// the form systemd's cgroup directives require: uppercase K/M/G/T suffixes.
// Systemd silently rejects lowercase suffixes on MemoryMax/MemoryHigh/
// MemorySwapMax and falls back to "infinity", which would mean the quadlet
// file looks correct but the cap never takes effect. Returns an empty string
// for empty/zero input so callers can skip emitting the directive.
func normalizeCgroupSize(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	n := len(s)
	last := s[n-1]
	// Already uppercase suffix → pass through.
	if last == 'K' || last == 'M' || last == 'G' || last == 'T' {
		return s
	}
	// Lowercase suffix → uppercase.
	if last == 'k' || last == 'm' || last == 'g' || last == 't' {
		return s[:n-1] + strings.ToUpper(string(last))
	}
	// No suffix (pure digits) → pass through (systemd accepts raw bytes).
	return s
}

// formatCPUQuota converts a podman-style --cpus value ("2.5") into the
// percentage form systemd's CPUQuota= directive expects ("250%"). Returns an
// empty string if the input is empty or unparseable, so callers can skip
// emitting the directive entirely.
func formatCPUQuota(cpus string) string {
	cpus = strings.TrimSpace(cpus)
	if cpus == "" {
		return ""
	}
	f, err := strconv.ParseFloat(cpus, 64)
	if err != nil || f <= 0 {
		return ""
	}
	return fmt.Sprintf("%d%%", int(f*100+0.5))
}
