package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateQuadlet(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "fedora-test",
		ImageRef:    "ghcr.io/overthinkos/fedora-test:latest",
		Workspace:   "/home/user/project",
		Ports:       []string{"8000:8000", "8080:8080"},
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	want := `# ov-fedora-test.container (generated by ov enable)
[Unit]
Description=Overthink fedora-test
After=network-online.target

[Container]
Image=ghcr.io/overthinkos/fedora-test:latest
ContainerName=ov-fedora-test
Volume=/home/user/project:/workspace
WorkingDir=/workspace
PublishPort=127.0.0.1:8000:8000
PublishPort=127.0.0.1:8080:8080
Exec=supervisord -n -c /etc/supervisord.conf

[Service]
Restart=always
TimeoutStartSec=900

[Install]
WantedBy=default.target
`

	if got != want {
		t.Errorf("generateQuadlet() =\n%s\nwant\n%s", got, want)
	}
}

func TestGenerateQuadletNoPorts(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "fedora",
		ImageRef:    "ghcr.io/overthinkos/fedora:latest",
		Workspace:   "/tmp/workspace",
		Ports:       nil,
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if strings.Contains(got, "PublishPort") {
		t.Error("expected no PublishPort lines when ports are nil")
	}
	if !strings.Contains(got, "ContainerName=ov-fedora") {
		t.Error("expected ContainerName=ov-fedora")
	}
	if !strings.Contains(got, "Volume=/tmp/workspace:/workspace") {
		t.Error("expected Volume with workspace path")
	}
}

func TestGenerateQuadletSinglePort(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "myapp",
		ImageRef:    "myapp:latest",
		Workspace:   "/home/user",
		Ports:       []string{"9090"},
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "PublishPort=127.0.0.1:9090:9090") {
		t.Errorf("expected single port to expand to 127.0.0.1:9090:9090, got:\n%s", got)
	}
	count := strings.Count(got, "PublishPort=")
	if count != 1 {
		t.Errorf("expected 1 PublishPort line, got %d", count)
	}
}

func TestGenerateQuadletWithVolumes(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "openclaw",
		ImageRef:    "ghcr.io/overthinkos/openclaw:latest",
		Workspace:   "/home/user/project",
		Ports:       []string{"18789:18789"},
		BindAddress: "127.0.0.1",
		Volumes: []VolumeMount{
			{VolumeName: "ov-openclaw-data", ContainerPath: "/home/user/.openclaw"},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "Volume=ov-openclaw-data:/home/user/.openclaw") {
		t.Errorf("expected Volume line for openclaw data, got:\n%s", got)
	}
	if !strings.Contains(got, "Volume=/home/user/project:/workspace") {
		t.Error("expected workspace Volume line")
	}
	if !strings.Contains(got, "PublishPort=127.0.0.1:18789:18789") {
		t.Error("expected PublishPort line")
	}
}

func TestGenerateQuadletWithGPU(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "ollama",
		ImageRef:    "ghcr.io/overthinkos/ollama:latest",
		Workspace:   "/home/user/project",
		GPU:         true,
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "AddDevice=nvidia.com/gpu=all") {
		t.Errorf("expected AddDevice=nvidia.com/gpu=all when GPU=true, got:\n%s", got)
	}
}

func TestGenerateQuadletWithoutGPU(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "fedora",
		ImageRef:    "ghcr.io/overthinkos/fedora:latest",
		Workspace:   "/home/user/project",
		GPU:         false,
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if strings.Contains(got, "AddDevice") {
		t.Errorf("expected no AddDevice when GPU=false, got:\n%s", got)
	}
}

func TestGenerateQuadletWithLANBindAddress(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "fedora-test",
		ImageRef:    "ghcr.io/overthinkos/fedora-test:latest",
		Workspace:   "/home/user/project",
		Ports:       []string{"8000:8000", "8080"},
		BindAddress: "0.0.0.0",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "PublishPort=0.0.0.0:8000:8000") {
		t.Errorf("expected PublishPort with 0.0.0.0 bind address, got:\n%s", got)
	}
	if !strings.Contains(got, "PublishPort=0.0.0.0:8080:8080") {
		t.Errorf("expected single port expanded with 0.0.0.0, got:\n%s", got)
	}
}

func TestServiceName(t *testing.T) {
	tests := []struct {
		image string
		want  string
	}{
		{"fedora", "ov-fedora.service"},
		{"fedora-test", "ov-fedora-test.service"},
		{"ubuntu", "ov-ubuntu.service"},
	}
	for _, tt := range tests {
		t.Run(tt.image, func(t *testing.T) {
			got := serviceName(tt.image)
			if got != tt.want {
				t.Errorf("serviceName(%q) = %q, want %q", tt.image, got, tt.want)
			}
		})
	}
}

func TestQuadletFilename(t *testing.T) {
	tests := []struct {
		image string
		want  string
	}{
		{"fedora", "ov-fedora.container"},
		{"fedora-test", "ov-fedora-test.container"},
	}
	for _, tt := range tests {
		t.Run(tt.image, func(t *testing.T) {
			got := quadletFilename(tt.image)
			if got != tt.want {
				t.Errorf("quadletFilename(%q) = %q, want %q", tt.image, got, tt.want)
			}
		})
	}
}

func TestQuadletDir(t *testing.T) {
	got, err := quadletDir()
	if err != nil {
		t.Fatalf("quadletDir() error: %v", err)
	}

	home, _ := os.UserHomeDir()
	want := filepath.Join(home, ".config", "containers", "systemd")
	if got != want {
		t.Errorf("quadletDir() = %q, want %q", got, want)
	}
}

func TestSystemdUserDir(t *testing.T) {
	got, err := systemdUserDir()
	if err != nil {
		t.Fatalf("systemdUserDir() error: %v", err)
	}

	home, _ := os.UserHomeDir()
	want := filepath.Join(home, ".config", "systemd", "user")
	if got != want {
		t.Errorf("systemdUserDir() = %q, want %q", got, want)
	}
}

func TestQuadletExists(t *testing.T) {
	tmpDir := t.TempDir()
	// Write a fake .container file
	systemdDir := filepath.Join(tmpDir, ".config", "containers", "systemd")
	os.MkdirAll(systemdDir, 0755)
	os.WriteFile(filepath.Join(systemdDir, "ov-testimg.container"), []byte("test"), 0644)

	// Override HOME so quadletDir resolves to our temp dir
	origHome := os.Getenv("HOME")
	os.Setenv("HOME", tmpDir)
	defer os.Setenv("HOME", origHome)

	exists, err := quadletExists("testimg")
	if err != nil {
		t.Fatalf("quadletExists() error: %v", err)
	}
	if !exists {
		t.Error("expected quadletExists to return true for existing file")
	}

	exists, err = quadletExists("nonexistent")
	if err != nil {
		t.Fatalf("quadletExists() error: %v", err)
	}
	if exists {
		t.Error("expected quadletExists to return false for nonexistent file")
	}
}

func TestGenerateQuadletWithTailscaleTunnel(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Workspace:   "/home/user/project",
		Ports:       []string{"8080:8080"},
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Port:     8080,
			HTTPS:    443,
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale funnel --bg --https=443 localhost:8080") {
		t.Errorf("expected ExecStartPost for tailscale funnel, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale funnel 443 off") {
		t.Errorf("expected ExecStopPost for tailscale funnel, got:\n%s", got)
	}
}

func TestGenerateQuadletWithTailscaleTunnelCustomPort(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Workspace:   "/home/user/project",
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Port:     3001,
			HTTPS:    8443,
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale funnel --bg --https=8443 localhost:3001") {
		t.Errorf("expected ExecStartPost with port 8443, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale funnel 8443 off") {
		t.Errorf("expected ExecStopPost with port 8443, got:\n%s", got)
	}
}

func TestGenerateQuadletWithCloudflareTunnelNoExecPost(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Workspace:   "/home/user/project",
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider:   "cloudflare",
			Port:       3001,
			TunnelName: "ov-myapp",
			Hostname:   "app.example.com",
		},
	}

	got := generateQuadlet(cfg)

	// Cloudflare uses a companion service, not ExecStartPost
	if strings.Contains(got, "ExecStartPost") {
		t.Errorf("cloudflare tunnel should not have ExecStartPost in container file, got:\n%s", got)
	}
}

func TestGenerateTunnelUnit(t *testing.T) {
	cfg := QuadletConfig{
		ImageName: "immich",
		ImageRef:  "ghcr.io/test/immich:latest",
		Workspace: "/home/user/project",
		Tunnel: &TunnelConfig{
			Provider:   "cloudflare",
			Port:       3001,
			TunnelName: "ov-immich",
			Hostname:   "im.example.com",
		},
	}

	got := generateTunnelUnit(cfg)

	if !strings.Contains(got, "ov-immich-tunnel.service") {
		t.Errorf("expected filename in comment, got:\n%s", got)
	}
	if !strings.Contains(got, "BindsTo=ov-immich.service") {
		t.Errorf("expected BindsTo, got:\n%s", got)
	}
	if !strings.Contains(got, "After=ov-immich.service") {
		t.Errorf("expected After, got:\n%s", got)
	}
	if !strings.Contains(got, "cloudflared tunnel --config") {
		t.Errorf("expected cloudflared ExecStart, got:\n%s", got)
	}
	if !strings.Contains(got, "run ov-immich") {
		t.Errorf("expected tunnel name in ExecStart, got:\n%s", got)
	}
	if !strings.Contains(got, "WantedBy=default.target") {
		t.Errorf("expected WantedBy, got:\n%s", got)
	}
}

func TestGenerateTunnelUnitNilTunnel(t *testing.T) {
	cfg := QuadletConfig{
		ImageName: "myapp",
		Tunnel:    nil,
	}

	got := generateTunnelUnit(cfg)
	if got != "" {
		t.Errorf("expected empty string for nil tunnel, got: %s", got)
	}
}

func TestTunnelServiceFilename(t *testing.T) {
	tests := []struct {
		image string
		want  string
	}{
		{"myapp", "ov-myapp-tunnel.service"},
		{"immich", "ov-immich-tunnel.service"},
	}
	for _, tt := range tests {
		t.Run(tt.image, func(t *testing.T) {
			got := tunnelServiceFilename(tt.image)
			if got != tt.want {
				t.Errorf("tunnelServiceFilename(%q) = %q, want %q", tt.image, got, tt.want)
			}
		})
	}
}
