package main

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
)

// generatePodQuadlet produces the contents of a quadlet .pod file.
// The pod owns the shared network namespace: ports, network, and Tailscale tun interface.
//
// Dual networking: the pod stays on the "ov" bridge (reachable by other containers)
// while the Tailscale sidecar adds a tun interface for exit node routing.
// --exit-node-allow-lan-access exempts bridge subnets from the tunnel.
func generatePodQuadlet(cfg QuadletConfig) string {
	podName := PodNameInstance(cfg.ImageName, cfg.Instance)

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# %s.pod (generated by ov config)\n", podName))

	b.WriteString("[Pod]\n")
	b.WriteString(fmt.Sprintf("PodName=%s\n", podName))

	// Network: keep the pod on the bridge for container-to-container connectivity.
	// The Tailscale sidecar creates a tun interface for exit node routing;
	// --exit-node-allow-lan-access preserves bridge subnet access.
	if cfg.Network != "" {
		b.WriteString(fmt.Sprintf("Network=%s\n", cfg.Network))
	}

	// DNS: when Tailscale sidecar is present, configure dual DNS.
	// TS_ACCEPT_DNS=false prevents Tailscale from rewriting /etc/resolv.conf.
	// Pod-level --dns flags provide both resolvers:
	//   10.89.0.1       — aardvark-dns (container DNS + external forwarding)
	//   100.100.100.100 — Tailscale MagicDNS (.ts.net names)
	if hasTailscaleSidecar(cfg.Sidecars) {
		b.WriteString("PodmanArgs=--dns=10.89.0.1\n")
		b.WriteString("PodmanArgs=--dns=100.100.100.100\n")
		b.WriteString("PodmanArgs=--dns-search=dns.podman\n")
	}

	// Shared memory size: must be set on the pod (per-container ShmSize is ignored in pod mode)
	if cfg.Security.ShmSize != "" {
		b.WriteString(fmt.Sprintf("PodmanArgs=--shm-size=%s\n", cfg.Security.ShmSize))
	}

	// Port mappings from the app container go on the pod (shared network namespace)
	for _, port := range cfg.Ports {
		b.WriteString(fmt.Sprintf("PodmanArgs=-p %s\n", localizePort(port, cfg.BindAddress)))
	}

	b.WriteString("\n[Install]\n")
	if cfg.EncryptedMounts && !cfg.KeyringBackend {
		b.WriteString("# Encrypted volumes require 'ov start' (no keyring auto-unlock)\n")
	} else {
		b.WriteString("WantedBy=default.target\n")
	}

	return b.String()
}

// hasTailscaleSidecar checks if any resolved sidecar is a Tailscale sidecar.
func hasTailscaleSidecar(sidecars []ResolvedSidecar) bool {
	for _, sc := range sidecars {
		if sc.Name == "tailscale" {
			return true
		}
	}
	return false
}

// generateSidecarQuadlet produces the contents of a sidecar .container file.
func generateSidecarQuadlet(sc ResolvedSidecar, podName string) string {
	var b strings.Builder

	ctrName := podName + "-" + sc.Name

	b.WriteString(fmt.Sprintf("# %s.container (generated by ov config)\n", ctrName))
	b.WriteString("[Unit]\n")
	b.WriteString(fmt.Sprintf("Description=Overthink %s sidecar: %s\n", podName, sc.Name))

	b.WriteString("\n[Container]\n")
	b.WriteString(fmt.Sprintf("Pod=%s.pod\n", podName))
	b.WriteString(fmt.Sprintf("Image=%s\n", sc.Image))
	b.WriteString(fmt.Sprintf("ContainerName=%s\n", ctrName))

	// Volumes
	for _, vol := range sc.Volumes {
		b.WriteString(fmt.Sprintf("Volume=%s:%s\n", vol.VolumeName, vol.ContainerPath))
	}

	// Environment variables (sorted for deterministic output)
	for _, kv := range SortedSidecarEnv(sc.Env) {
		if idx := strings.IndexByte(kv, '='); idx >= 0 {
			key := kv[:idx]
			val := kv[idx+1:]
			if IsSidecarEnvQuotable(val) {
				b.WriteString(fmt.Sprintf("Environment=%s=%q\n", key, val))
			} else {
				b.WriteString(fmt.Sprintf("Environment=%s\n", kv))
			}
		} else {
			b.WriteString(fmt.Sprintf("Environment=%s\n", kv))
		}
	}

	// Secrets (podman Secret= directives)
	for _, s := range sc.Secrets {
		if s.Env != "" {
			b.WriteString(fmt.Sprintf("Secret=%s,type=env,target=%s\n", s.Name, s.Env))
		} else if s.Target != "" {
			b.WriteString(fmt.Sprintf("Secret=%s,target=%s\n", s.Name, s.Target))
		}
	}

	// Security: capabilities
	for _, cap := range sc.Security.CapAdd {
		b.WriteString(fmt.Sprintf("AddCapability=%s\n", cap))
	}
	// Security: devices
	for _, dev := range sc.Security.Devices {
		b.WriteString(fmt.Sprintf("AddDevice=%s\n", dev))
	}
	// Security: privileged
	if sc.Security.Privileged {
		b.WriteString("SecurityLabelDisable=true\n")
		b.WriteString("PodmanArgs=--privileged\n")
	}
	// Security: security_opt
	for _, opt := range sc.Security.SecurityOpt {
		if opt == "label=disable" {
			b.WriteString("SecurityLabelDisable=true\n")
		} else {
			b.WriteString(fmt.Sprintf("PodmanArgs=--security-opt %s\n", opt))
		}
	}

	b.WriteString("\n[Service]\n")
	b.WriteString("Restart=always\n")
	b.WriteString("TimeoutStartSec=120\n")

	return b.String()
}

// tailscaleServeConfigPath returns the host path for a Tailscale serve config file.
func tailscaleServeConfigPath(podName string) string {
	dir, _ := sidecarConfigDir()
	return filepath.Join(dir, podName+"-tailscale-serve.json")
}

// TailscaleServeConfig represents the JSON structure for TS_SERVE_CONFIG.
// Uses Tailscale's ipn.ServeConfig format.
type TailscaleServeConfig struct {
	TCP         map[string]TailscaleTCPConfig `json:"TCP,omitempty"`
	Web         map[string]TailscaleWebConfig `json:"Web,omitempty"`
	AllowFunnel map[string]bool               `json:"AllowFunnel,omitempty"`
}

// TailscaleTCPConfig represents a TCP port configuration in serve config.
type TailscaleTCPConfig struct {
	HTTPS bool `json:"HTTPS,omitempty"`
}

// TailscaleWebConfig represents a web handler configuration in serve config.
type TailscaleWebConfig struct {
	Handlers map[string]TailscaleHandler `json:"Handlers,omitempty"`
}

// TailscaleHandler represents a single handler in serve config.
type TailscaleHandler struct {
	Proxy string `json:"Proxy,omitempty"`
}

// GenerateTailscaleServeConfig creates a TS_SERVE_CONFIG JSON from tunnel config.
// The config uses ${TS_CERT_DOMAIN} placeholder which Tailscale's containerboot
// substitutes with the node's FQDN at startup.
func GenerateTailscaleServeConfig(tunnel *TunnelConfig) ([]byte, error) {
	if tunnel == nil || len(tunnel.Ports) == 0 {
		return nil, nil
	}

	cfg := TailscaleServeConfig{
		TCP:         make(map[string]TailscaleTCPConfig),
		Web:         make(map[string]TailscaleWebConfig),
		AllowFunnel: make(map[string]bool),
	}

	for _, tp := range tunnel.Ports {
		if tp.Protocol == "udp" {
			continue // UDP not supported by tailscale serve
		}

		port := fmt.Sprintf("%d", tp.Port)
		backendPort := tp.backend()
		backendScheme := "http"
		if tp.Protocol == "https" || tp.Protocol == "https+insecure" {
			backendScheme = "https"
		}

		if isTCPFamily(tp.Protocol) {
			// TCP ports: use raw TCP proxying (TS_SERVE_CONFIG doesn't have a
			// direct TCP proxy equivalent; for TCP, ExecStartPost is still needed)
			continue
		}

		// HTTPS port: configure TLS termination + web proxy
		cfg.TCP[port] = TailscaleTCPConfig{HTTPS: true}

		hostPort := fmt.Sprintf("${TS_CERT_DOMAIN}:%s", port)
		cfg.Web[hostPort] = TailscaleWebConfig{
			Handlers: map[string]TailscaleHandler{
				"/": {Proxy: fmt.Sprintf("%s://127.0.0.1:%d", backendScheme, backendPort)},
			},
		}

		cfg.AllowFunnel[hostPort] = tp.Public
	}

	// Only return config if we have any web entries
	if len(cfg.Web) == 0 {
		return nil, nil
	}

	return json.MarshalIndent(cfg, "", "  ")
}

// --- Filename helpers ---

// podQuadletFilename returns the quadlet filename for a pod.
func podQuadletFilename(imageName string) string {
	return PodName(imageName) + ".pod"
}

// podQuadletFilenameInstance returns the quadlet filename for a pod with optional instance.
func podQuadletFilenameInstance(imageName, instance string) string {
	return PodNameInstance(imageName, instance) + ".pod"
}

// sidecarQuadletFilename returns the quadlet filename for a sidecar container.
func sidecarQuadletFilename(imageName, sidecarName string) string {
	return SidecarContainerName(imageName, sidecarName) + ".container"
}

// sidecarQuadletFilenameInstance returns the quadlet filename for a sidecar with optional instance.
func sidecarQuadletFilenameInstance(imageName, instance, sidecarName string) string {
	return SidecarContainerNameInstance(imageName, instance, sidecarName) + ".container"
}
