package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateQuadlet(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "fedora-test",
		ImageRef:    "ghcr.io/overthinkos/fedora-test:latest",
		Workspace:   "/home/user/project",
		Ports:       []string{"8000:8000", "8080:8080"},
		BindAddress: "127.0.0.1",
		Entrypoint:  []string{"supervisord", "-n", "-c", "/etc/supervisord.conf"},
	}

	got := generateQuadlet(cfg)

	want := `# ov-fedora-test.container (generated by ov config)
# Status: testing
[Unit]
Description=Overthink fedora-test
After=network-online.target

[Container]
Image=ghcr.io/overthinkos/fedora-test:latest
ContainerName=ov-fedora-test
Volume=/home/user/project:/workspace
WorkingDir=/workspace
PublishPort=127.0.0.1:8000:8000
PublishPort=127.0.0.1:8080:8080
Exec=supervisord -n -c /etc/supervisord.conf

[Service]
Restart=always
TimeoutStartSec=900

[Install]
WantedBy=default.target
`

	if got != want {
		t.Errorf("generateQuadlet() =\n%s\nwant\n%s", got, want)
	}
}

func TestGenerateQuadletNoPorts(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "fedora",
		ImageRef:    "ghcr.io/overthinkos/fedora:latest",
		Workspace:   "/tmp/workspace",
		Ports:       nil,
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if strings.Contains(got, "PublishPort") {
		t.Error("expected no PublishPort lines when ports are nil")
	}
	if !strings.Contains(got, "ContainerName=ov-fedora") {
		t.Error("expected ContainerName=ov-fedora")
	}
	if !strings.Contains(got, "Volume=/tmp/workspace:/workspace") {
		t.Error("expected Volume with workspace path")
	}
}

func TestGenerateQuadletSinglePort(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "myapp",
		ImageRef:    "myapp:latest",
		Workspace:   "/home/user",
		Ports:       []string{"9090"},
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "PublishPort=127.0.0.1:9090:9090") {
		t.Errorf("expected single port to expand to 127.0.0.1:9090:9090, got:\n%s", got)
	}
	count := strings.Count(got, "PublishPort=")
	if count != 1 {
		t.Errorf("expected 1 PublishPort line, got %d", count)
	}
}

func TestGenerateQuadletWithVolumes(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "openclaw",
		ImageRef:    "ghcr.io/overthinkos/openclaw:latest",
		Workspace:   "/home/user/project",
		Ports:       []string{"18789:18789"},
		BindAddress: "127.0.0.1",
		Volumes: []VolumeMount{
			{VolumeName: "ov-openclaw-data", ContainerPath: "/home/user/.openclaw"},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "Volume=ov-openclaw-data:/home/user/.openclaw") {
		t.Errorf("expected Volume line for openclaw data, got:\n%s", got)
	}
	if !strings.Contains(got, "Volume=/home/user/project:/workspace") {
		t.Error("expected workspace Volume line")
	}
	if !strings.Contains(got, "PublishPort=127.0.0.1:18789:18789") {
		t.Error("expected PublishPort line")
	}
}

func TestGenerateQuadletWithGPU(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "ollama",
		ImageRef:    "ghcr.io/overthinkos/ollama:latest",
		Workspace:   "/home/user/project",
		GPU:         true,
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "AddDevice=nvidia.com/gpu=all") {
		t.Errorf("expected AddDevice=nvidia.com/gpu=all when GPU=true, got:\n%s", got)
	}
}

func TestGenerateQuadletWithoutGPU(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "fedora",
		ImageRef:    "ghcr.io/overthinkos/fedora:latest",
		Workspace:   "/home/user/project",
		GPU:         false,
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if strings.Contains(got, "AddDevice") {
		t.Errorf("expected no AddDevice when GPU=false, got:\n%s", got)
	}
}

func TestGenerateQuadletWithLANBindAddress(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "fedora-test",
		ImageRef:    "ghcr.io/overthinkos/fedora-test:latest",
		Workspace:   "/home/user/project",
		Ports:       []string{"8000:8000", "8080"},
		BindAddress: "0.0.0.0",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "PublishPort=0.0.0.0:8000:8000") {
		t.Errorf("expected PublishPort with 0.0.0.0 bind address, got:\n%s", got)
	}
	if !strings.Contains(got, "PublishPort=0.0.0.0:8080:8080") {
		t.Errorf("expected single port expanded with 0.0.0.0, got:\n%s", got)
	}
}

func TestServiceName(t *testing.T) {
	tests := []struct {
		image string
		want  string
	}{
		{"fedora", "ov-fedora.service"},
		{"fedora-test", "ov-fedora-test.service"},
		{"ubuntu", "ov-ubuntu.service"},
	}
	for _, tt := range tests {
		t.Run(tt.image, func(t *testing.T) {
			got := serviceName(tt.image)
			if got != tt.want {
				t.Errorf("serviceName(%q) = %q, want %q", tt.image, got, tt.want)
			}
		})
	}
}

func TestQuadletFilename(t *testing.T) {
	tests := []struct {
		image string
		want  string
	}{
		{"fedora", "ov-fedora.container"},
		{"fedora-test", "ov-fedora-test.container"},
	}
	for _, tt := range tests {
		t.Run(tt.image, func(t *testing.T) {
			got := quadletFilename(tt.image)
			if got != tt.want {
				t.Errorf("quadletFilename(%q) = %q, want %q", tt.image, got, tt.want)
			}
		})
	}
}

func TestQuadletDir(t *testing.T) {
	got, err := quadletDir()
	if err != nil {
		t.Fatalf("quadletDir() error: %v", err)
	}

	home, _ := os.UserHomeDir()
	want := filepath.Join(home, ".config", "containers", "systemd")
	if got != want {
		t.Errorf("quadletDir() = %q, want %q", got, want)
	}
}

func TestSystemdUserDir(t *testing.T) {
	got, err := systemdUserDir()
	if err != nil {
		t.Fatalf("systemdUserDir() error: %v", err)
	}

	home, _ := os.UserHomeDir()
	want := filepath.Join(home, ".config", "systemd", "user")
	if got != want {
		t.Errorf("systemdUserDir() = %q, want %q", got, want)
	}
}

func TestQuadletExists(t *testing.T) {
	tmpDir := t.TempDir()
	// Write a fake .container file
	systemdDir := filepath.Join(tmpDir, ".config", "containers", "systemd")
	os.MkdirAll(systemdDir, 0755)
	os.WriteFile(filepath.Join(systemdDir, "ov-testimg.container"), []byte("test"), 0644)

	// Override HOME so quadletDir resolves to our temp dir
	origHome := os.Getenv("HOME")
	os.Setenv("HOME", tmpDir)
	defer os.Setenv("HOME", origHome)

	exists, err := quadletExists("testimg")
	if err != nil {
		t.Fatalf("quadletExists() error: %v", err)
	}
	if !exists {
		t.Error("expected quadletExists to return true for existing file")
	}

	exists, err = quadletExists("nonexistent")
	if err != nil {
		t.Fatalf("quadletExists() error: %v", err)
	}
	if exists {
		t.Error("expected quadletExists to return false for nonexistent file")
	}
}

func TestGenerateQuadletWithTailscalePublic(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Workspace:   "/home/user/project",
		Ports:       []string{"443:8080"},
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Ports: []TunnelPort{
				{Port: 443, Protocol: "http", Public: true},
			},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale funnel --bg --https=443 http://127.0.0.1:443") {
		t.Errorf("expected ExecStartPost for public port, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale funnel 443 off") {
		t.Errorf("expected ExecStopPost for public port, got:\n%s", got)
	}
}

func TestGenerateQuadletWithTailscalePublicCustomPort(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Workspace:   "/home/user/project",
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Ports: []TunnelPort{
				{Port: 8443, Protocol: "http", Public: true},
			},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale funnel --bg --https=8443 http://127.0.0.1:8443") {
		t.Errorf("expected ExecStartPost with port 8443, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale funnel 8443 off") {
		t.Errorf("expected ExecStopPost with port 8443, got:\n%s", got)
	}
}

func TestGenerateQuadletWithTailscalePrivate(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "immich-cuda",
		ImageRef:    "ghcr.io/overthinkos/immich-cuda:latest",
		Workspace:   "/home/user/project",
		Ports:       []string{"2283:2283"},
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Ports: []TunnelPort{
				{Port: 2283, Protocol: "http", Public: false},
			},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale serve --bg --https=2283 http://127.0.0.1:2283") {
		t.Errorf("expected ExecStartPost for private port, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale serve --https=2283 off") {
		t.Errorf("expected ExecStopPost for private port, got:\n%s", got)
	}
	// Private ports should not use tailscale funnel
	if strings.Contains(got, "tailscale funnel") {
		t.Errorf("private mode should not contain 'tailscale funnel', got:\n%s", got)
	}
}

func TestGenerateQuadletWithCloudflareTunnelNoExecPost(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Workspace:   "/home/user/project",
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider:   "cloudflare",
			TunnelName: "ov-myapp",
			Hostname:   "app.example.com",
			Ports: []TunnelPort{
				{Port: 3001, Protocol: "http", Public: true},
			},
		},
	}

	got := generateQuadlet(cfg)

	// Cloudflare uses a companion service, not ExecStartPost
	if strings.Contains(got, "ExecStartPost") {
		t.Errorf("cloudflare tunnel should not have ExecStartPost in container file, got:\n%s", got)
	}
}

func TestGenerateTunnelUnit(t *testing.T) {
	cfg := QuadletConfig{
		ImageName: "immich",
		ImageRef:  "ghcr.io/test/immich:latest",
		Workspace: "/home/user/project",
		Tunnel: &TunnelConfig{
			Provider:   "cloudflare",
			TunnelName: "ov-immich",
			Hostname:   "im.example.com",
			Ports: []TunnelPort{
				{Port: 3001, Protocol: "http", Public: true},
			},
		},
	}

	got := generateTunnelUnit(cfg)

	if !strings.Contains(got, "ov-immich-tunnel.service") {
		t.Errorf("expected filename in comment, got:\n%s", got)
	}
	if !strings.Contains(got, "BindsTo=ov-immich.service") {
		t.Errorf("expected BindsTo, got:\n%s", got)
	}
	if !strings.Contains(got, "After=ov-immich.service") {
		t.Errorf("expected After, got:\n%s", got)
	}
	if !strings.Contains(got, "cloudflared tunnel --config") {
		t.Errorf("expected cloudflared ExecStart, got:\n%s", got)
	}
	if !strings.Contains(got, "run ov-immich") {
		t.Errorf("expected tunnel name in ExecStart, got:\n%s", got)
	}
	if !strings.Contains(got, "WantedBy=default.target") {
		t.Errorf("expected WantedBy, got:\n%s", got)
	}
}

func TestGenerateTunnelUnitNilTunnel(t *testing.T) {
	cfg := QuadletConfig{
		ImageName: "myapp",
		Tunnel:    nil,
	}

	got := generateTunnelUnit(cfg)
	if got != "" {
		t.Errorf("expected empty string for nil tunnel, got: %s", got)
	}
}

func TestTunnelServiceFilename(t *testing.T) {
	tests := []struct {
		image string
		want  string
	}{
		{"myapp", "ov-myapp-tunnel.service"},
		{"immich", "ov-immich-tunnel.service"},
	}
	for _, tt := range tests {
		t.Run(tt.image, func(t *testing.T) {
			got := tunnelServiceFilename(tt.image)
			if got != tt.want {
				t.Errorf("tunnelServiceFilename(%q) = %q, want %q", tt.image, got, tt.want)
			}
		})
	}
}

func TestGenerateQuadletWithNetwork(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "githubrunner",
		ImageRef:    "ghcr.io/overthinkos/githubrunner:latest",
		Workspace:   "/home/user/project",
		BindAddress: "127.0.0.1",
		Network:     "host",
		Security:    SecurityConfig{Privileged: true},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "Network=host\n") {
		t.Errorf("expected Network=host, got:\n%s", got)
	}
	if !strings.Contains(got, "PodmanArgs=--privileged") {
		t.Errorf("expected PodmanArgs=--privileged, got:\n%s", got)
	}
}

func TestGenerateQuadletWithoutNetwork(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "fedora",
		ImageRef:    "ghcr.io/overthinkos/fedora:latest",
		Workspace:   "/home/user/project",
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if strings.Contains(got, "Network=") {
		t.Errorf("expected no Network= when network is empty, got:\n%s", got)
	}
}

func TestGenerateQuadletWithEnvVars(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "githubrunner",
		ImageRef:    "ghcr.io/overthinkos/githubrunner:latest",
		Workspace:   "/home/user/project",
		BindAddress: "127.0.0.1",
		Env:         []string{"RUNNER_TOKEN=abc123", "RUNNER_NAME=r1"},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "Environment=RUNNER_TOKEN=abc123") {
		t.Errorf("expected Environment=RUNNER_TOKEN=abc123, got:\n%s", got)
	}
	if !strings.Contains(got, "Environment=RUNNER_NAME=r1") {
		t.Errorf("expected Environment=RUNNER_NAME=r1, got:\n%s", got)
	}
}

func TestGenerateQuadletWithEnvFile(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "githubrunner",
		ImageRef:    "ghcr.io/overthinkos/githubrunner:latest",
		Workspace:   "/home/user/project",
		BindAddress: "127.0.0.1",
		EnvFile:     "/home/user/.config/ov/githubrunner.env",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "EnvironmentFile=/home/user/.config/ov/githubrunner.env") {
		t.Errorf("expected EnvironmentFile line, got:\n%s", got)
	}
}

func TestGenerateQuadletWithInstance(t *testing.T) {
	cfg := QuadletConfig{
		ImageName:   "githubrunner",
		ImageRef:    "ghcr.io/overthinkos/githubrunner:latest",
		Workspace:   "/home/user/project",
		BindAddress: "127.0.0.1",
		Instance:    "runner-1",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ContainerName=ov-githubrunner-runner-1") {
		t.Errorf("expected instance container name, got:\n%s", got)
	}
	if !strings.Contains(got, "Description=Overthink githubrunner (runner-1)") {
		t.Errorf("expected instance description, got:\n%s", got)
	}
	if !strings.Contains(got, "# ov-githubrunner-runner-1.container") {
		t.Errorf("expected instance filename in comment, got:\n%s", got)
	}
}

func TestServiceNameInstance(t *testing.T) {
	tests := []struct {
		image    string
		instance string
		want     string
	}{
		{"fedora", "", "ov-fedora.service"},
		{"githubrunner", "runner-1", "ov-githubrunner-runner-1.service"},
	}
	for _, tt := range tests {
		got := serviceNameInstance(tt.image, tt.instance)
		if got != tt.want {
			t.Errorf("serviceNameInstance(%q, %q) = %q, want %q", tt.image, tt.instance, got, tt.want)
		}
	}
}

func TestQuadletFilenameInstance(t *testing.T) {
	tests := []struct {
		image    string
		instance string
		want     string
	}{
		{"fedora", "", "ov-fedora.container"},
		{"githubrunner", "runner-2", "ov-githubrunner-runner-2.container"},
	}
	for _, tt := range tests {
		got := quadletFilenameInstance(tt.image, tt.instance)
		if got != tt.want {
			t.Errorf("quadletFilenameInstance(%q, %q) = %q, want %q", tt.image, tt.instance, got, tt.want)
		}
	}
}
