package main

import (
	"os"
	"path/filepath"
	"testing"
)

// TestParseQuadletDescription_ImageOnly covers the no-instance shape.
func TestParseQuadletDescription_ImageOnly(t *testing.T) {
	dir := t.TempDir()
	unitPath := filepath.Join(dir, "ov-redis.container")
	body := `# ov-redis.container (generated by ov config)
[Unit]
Description=Overthink redis
After=network-online.target

[Container]
Image=ghcr.io/overthinkos/redis:latest
ContainerName=ov-redis
`
	if err := os.WriteFile(unitPath, []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	image, instance := parseQuadletDescription(unitPath)
	if image != "redis" {
		t.Errorf("image = %q, want %q", image, "redis")
	}
	if instance != "" {
		t.Errorf("instance = %q, want empty", instance)
	}
}

// TestParseQuadletDescription_ImageAndInstance covers the canonical
// `Description=Overthink <image> (<instance>)` shape ov config emits.
func TestParseQuadletDescription_ImageAndInstance(t *testing.T) {
	dir := t.TempDir()
	unitPath := filepath.Join(dir, "ov-jupyter-concurrency-test.container")
	body := `# ov-jupyter-concurrency-test.container (generated by ov config)
[Unit]
Description=Overthink jupyter (concurrency-test)
After=network-online.target

[Container]
Image=ghcr.io/overthinkos/jupyter:latest
ContainerName=ov-jupyter-concurrency-test
`
	if err := os.WriteFile(unitPath, []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	image, instance := parseQuadletDescription(unitPath)
	if image != "jupyter" {
		t.Errorf("image = %q, want %q", image, "jupyter")
	}
	if instance != "concurrency-test" {
		t.Errorf("instance = %q, want %q", instance, "concurrency-test")
	}
}

// TestParseQuadletDescription_HyphenInImage covers an image whose
// own name contains hyphens (e.g. selkies-desktop). Disambiguation
// must use the literal " (" delimiter, not last-hyphen heuristics.
func TestParseQuadletDescription_HyphenInImage(t *testing.T) {
	dir := t.TempDir()
	unitPath := filepath.Join(dir, "ov-selkies-desktop-tailnet1.container")
	body := `[Unit]
Description=Overthink selkies-desktop (tailnet1)
`
	if err := os.WriteFile(unitPath, []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	image, instance := parseQuadletDescription(unitPath)
	if image != "selkies-desktop" {
		t.Errorf("image = %q, want %q", image, "selkies-desktop")
	}
	if instance != "tailnet1" {
		t.Errorf("instance = %q, want %q", instance, "tailnet1")
	}
}

// TestParseQuadletDescription_Missing returns ("","") for any
// unparseable input — caller falls back to filename joined name.
func TestParseQuadletDescription_Missing(t *testing.T) {
	dir := t.TempDir()
	cases := []struct {
		name string
		body string
	}{
		{"no Description line", "[Unit]\nAfter=network-online.target\n"},
		{"non-Overthink Description", "[Unit]\nDescription=Some other service\n"},
		{"missing file", "DOES_NOT_EXIST"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(dir, tc.name+".container")
			if tc.body != "DOES_NOT_EXIST" {
				if err := os.WriteFile(path, []byte(tc.body), 0o644); err != nil {
					t.Fatalf("write: %v", err)
				}
			} else {
				path = filepath.Join(dir, "no-such.container")
			}
			image, instance := parseQuadletDescription(path)
			if image != "" || instance != "" {
				t.Errorf("expected empty, got image=%q instance=%q", image, instance)
			}
		})
	}
}
