package main

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"

	"golang.org/x/sys/unix"
)

const udevRuleFile = "/etc/udev/rules.d/99-ov-container-access.rules"

const udevRuleContent = `# Generated by ov udev install — GPU device access for rootless containers.
# Render nodes (renderD*) are already group=render mode=0666.
# Card nodes need render group access for NVENC hardware encoding.
# Rootless Podman user namespace prevents DRM master abuse.
SUBSYSTEM=="drm", KERNEL=="card[0-9]*", GROUP="render", MODE="0660"
# AMD KFD (Kernel Fusion Driver) for ROCm compute access.
SUBSYSTEM=="kfd", KERNEL=="kfd", GROUP="render", MODE="0660"
`

// UdevCmd manages udev rules for GPU device access in containers.
type UdevCmd struct {
	Generate UdevGenerateCmd `cmd:"" help:"Print udev rules to stdout"`
	Install  UdevInstallCmd  `cmd:"" help:"Install udev rules (requires sudo)"`
	Remove   UdevRemoveCmd   `cmd:"" help:"Remove installed udev rules"`
	Status   UdevStatusCmd   `cmd:"" help:"Show device access and udev rule status"`
}

// drmDevice holds info about a /dev/dri/* device.
type drmDevice struct {
	Path       string
	Name       string // e.g., "card0", "renderD128"
	Driver     string // e.g., "nvidia", "amdgpu"
	Owner      string // e.g., "root"
	Group      string // e.g., "video", "render"
	Mode       string // e.g., "0660"
	Accessible bool
}

// --- Status ---

type UdevStatusCmd struct{}

func (c *UdevStatusCmd) Run() error {
	devices := detectGPUDevices()
	inRender := userInGroup("render")
	inVideo := userInGroup("video")
	installed := udevRulesInstalled()

	fmt.Println("GPU Devices:")
	for _, d := range devices {
		access := "OK"
		if !d.Accessible {
			access = "NO ACCESS"
		}
		fmt.Printf("  %-22s %-10s %s:%-8s %s  %s\n",
			d.Path, d.Driver, d.Owner, d.Group, d.Mode, access)
	}

	fmt.Println("\nUser Groups:")
	printGroupStatus("  video", inVideo)
	printGroupStatus("  render", inRender)

	fmt.Println("\nUdev Rules:")
	if installed {
		fmt.Printf("  %s: installed\n", udevRuleFile)
	} else {
		fmt.Printf("  %s: not installed\n", udevRuleFile)
	}

	// Check if everything is OK
	allAccessible := true
	hasAMD := false
	for _, d := range devices {
		if d.Name == "kfd" {
			hasAMD = true
			if !d.Accessible {
				allAccessible = false
			}
		}
		if strings.HasPrefix(d.Name, "card") && !d.Accessible {
			allAccessible = false
		}
	}

	fmt.Println()
	if allAccessible && inRender && (!hasAMD || inVideo) {
		fmt.Println("Status: OK — GPU device access available for containers")
	} else {
		fmt.Println("Fix:")
		if !installed {
			fmt.Println("  ov udev install                # install udev rules (requires sudo)")
		}
		u, _ := user.Current()
		username := "USER"
		if u != nil {
			username = u.Username
		}
		if !inRender {
			fmt.Printf("  sudo usermod -aG render %s   # add user to render group (relogin required)\n", username)
		}
		if hasAMD && !inVideo {
			fmt.Printf("  sudo usermod -aG video %s    # add user to video group for AMD GPU (relogin required)\n", username)
		}
	}

	return nil
}

func printGroupStatus(label string, in bool) {
	if in {
		fmt.Printf("%-10s yes\n", label+":")
	} else {
		fmt.Printf("%-10s no\n", label+":")
	}
}

// --- Generate ---

type UdevGenerateCmd struct{}

func (c *UdevGenerateCmd) Run() error {
	fmt.Print(udevRuleContent)
	return nil
}

// --- Install ---

type UdevInstallCmd struct{}

func (c *UdevInstallCmd) Run() error {
	if udevRulesUpToDate() {
		fmt.Fprintf(os.Stderr, "Rules already up to date at %s\n", udevRuleFile)
		return nil
	}

	// Write rule file via sudo tee
	cmd := exec.Command("sudo", "tee", udevRuleFile)
	cmd.Stdin = strings.NewReader(udevRuleContent)
	cmd.Stdout = nil // suppress tee's stdout echo
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("writing %s: %w (is sudo available?)", udevRuleFile, err)
	}
	fmt.Fprintf(os.Stderr, "Wrote %s\n", udevRuleFile)

	// Reload udev rules
	if err := exec.Command("sudo", "udevadm", "control", "--reload-rules").Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: failed to reload udev rules: %v\n", err)
	}

	// Trigger DRM and KFD subsystems to apply new rules immediately
	if err := exec.Command("sudo", "udevadm", "trigger", "--subsystem-match=drm").Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: failed to trigger udev for DRM: %v\n", err)
	}
	if err := exec.Command("sudo", "udevadm", "trigger", "--subsystem-match=kfd").Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: failed to trigger udev for KFD: %v\n", err)
	}

	fmt.Fprintf(os.Stderr, "Reloaded udev rules and triggered device re-evaluation\n")
	return nil
}

// --- Remove ---

type UdevRemoveCmd struct{}

func (c *UdevRemoveCmd) Run() error {
	if !udevRulesInstalled() {
		fmt.Fprintf(os.Stderr, "No rules installed at %s\n", udevRuleFile)
		return nil
	}

	if err := exec.Command("sudo", "rm", "-f", udevRuleFile).Run(); err != nil {
		return fmt.Errorf("removing %s: %w", udevRuleFile, err)
	}
	fmt.Fprintf(os.Stderr, "Removed %s\n", udevRuleFile)

	// Reload and trigger
	exec.Command("sudo", "udevadm", "control", "--reload-rules").Run()
	exec.Command("sudo", "udevadm", "trigger", "--subsystem-match=drm").Run()
	exec.Command("sudo", "udevadm", "trigger", "--subsystem-match=kfd").Run()
	fmt.Fprintf(os.Stderr, "Reloaded udev rules\n")
	return nil
}

// --- Helpers ---

func detectGPUDevices() []drmDevice {
	var devices []drmDevice

	// DRM devices (card nodes, render nodes)
	patterns := []string{"/dev/dri/card*", "/dev/dri/renderD*"}
	for _, pattern := range patterns {
		matches, _ := filepath.Glob(pattern)
		for _, path := range matches {
			name := filepath.Base(path)
			d := drmDevice{
				Path: path,
				Name: name,
			}

			// Get driver name from sysfs
			driverLink, err := os.Readlink(fmt.Sprintf("/sys/class/drm/%s/device/driver", name))
			if err == nil {
				d.Driver = filepath.Base(driverLink)
			}

			// Get file ownership and permissions
			info, err := os.Stat(path)
			if err == nil {
				stat := info.Sys().(*syscall.Stat_t)
				d.Owner = lookupUID(stat.Uid)
				d.Group = lookupGID(stat.Gid)
				d.Mode = fmt.Sprintf("%04o", info.Mode().Perm())
			}

			// Check if current user can access
			d.Accessible = unix.Access(path, unix.R_OK|unix.W_OK) == nil

			devices = append(devices, d)
		}
	}

	// AMD KFD device (ROCm compute)
	if info, err := os.Stat("/dev/kfd"); err == nil {
		d := drmDevice{
			Path:   "/dev/kfd",
			Name:   "kfd",
			Driver: "amdgpu",
		}
		stat := info.Sys().(*syscall.Stat_t)
		d.Owner = lookupUID(stat.Uid)
		d.Group = lookupGID(stat.Gid)
		d.Mode = fmt.Sprintf("%04o", info.Mode().Perm())
		d.Accessible = unix.Access("/dev/kfd", unix.R_OK|unix.W_OK) == nil
		devices = append(devices, d)
	}

	return devices
}

func lookupUID(uid uint32) string {
	u, err := user.LookupId(strconv.Itoa(int(uid)))
	if err != nil {
		return strconv.Itoa(int(uid))
	}
	return u.Username
}

func lookupGID(gid uint32) string {
	g, err := user.LookupGroupId(strconv.Itoa(int(gid)))
	if err != nil {
		return strconv.Itoa(int(gid))
	}
	return g.Name
}

func userInGroup(groupName string) bool {
	g, err := user.LookupGroup(groupName)
	if err != nil {
		return false
	}
	gid, err := strconv.Atoi(g.Gid)
	if err != nil {
		return false
	}

	groups, err := os.Getgroups()
	if err != nil {
		return false
	}
	for _, id := range groups {
		if id == gid {
			return true
		}
	}
	return false
}

func udevRulesInstalled() bool {
	_, err := os.Stat(udevRuleFile)
	return err == nil
}

// udevRulesUpToDate returns true if the installed rules match the current content.
func udevRulesUpToDate() bool {
	data, err := os.ReadFile(udevRuleFile)
	if err != nil {
		return false
	}
	return string(data) == udevRuleContent
}
