// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #ExamplecommandInput — the input shape for the `examplecommand` command. The
// optional `args` list carries every CLI token after the command word.
type ExamplecommandInput struct {
	// args is the pass-through CLI token list charly forwards from
	// `charly examplecommand <args…>`. Optional — an empty/absent list means the
	// command was invoked with no positional arguments.
	Args []string `yaml:"args,omitempty" json:"args,omitempty"`
}
