// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The BUILT-IN `agent` plugin's OWN CUE schema — the typed input for the `agent`
// KIND (the AI-CLI grader catalog, formerly a core `agent:` kind decoded into the
// typed core map uf.Agent). It is the SINGLE SOURCE for this plugin's params, used
// two ways (the same contract the reference exampleprobe/process, the package-group
// plugin, and core `spec` use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by task cue:gen,
//     which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go.
//  2. VALIDATE authored input AT RUNTIME — the builtin serves this source over the
//     Describe channel (InProcTransport) exactly like an external serves it over
//     gRPC; the host splices it onto the base (base ++ plugin) and validates every
//     authored `agent:` entity body against #AgentInput BEFORE runPluginKind
//     dispatches (validateAuthoredPluginInput(ClassKind, "agent", …)) — the
//     kind-class analogue of the verb plugin_input gate.
//
// SELF-CONTAINED: it references NO base def — every shared shape (#AgDuration,
// #AgCredentialMount) is reproduced standalone here, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (the base ++ plugin
// splice exists to detect a def-name collision with the base, not to resolve base
// refs). It is a faithful reproduction of the core #Agent (schema/agent.cue) — the
// same authored WIRE keys, so the host validates a real agent entity, and the
// plugin's Invoke canonicalises the body back through the core spec.Agent type (which
// AgentConfig still aliases and the whole iterate/check harness consumes).
//
// NAME: in node-form the entity name is the top-level node KEY, not a body field, so
// the assembled entity body NEVER carries `name`; #Agent has no name field either, so
// there is nothing to make optional here.
type AgentInput struct {
	Description string `yaml:"description,omitempty" json:"description,omitempty"`

	Command []string `yaml:"command,omitempty" json:"command"`

	Prompt_via string `yaml:"prompt_via,omitempty" json:"prompt_via"`

	Version_command []string `yaml:"version_command,omitempty" json:"version_command,omitempty"`

	Timeout AgDuration `yaml:"timeout,omitempty" json:"timeout,omitempty"`

	Env map[string]string `yaml:"env,omitempty" json:"env,omitempty"`

	Working_dir string `yaml:"working_dir,omitempty" json:"working_dir,omitempty"`

	Credential []AgCredentialMount `yaml:"credential,omitempty" json:"credential,omitempty"`

	Progress_check_interval AgDuration `yaml:"progress_check_interval,omitempty" json:"progress_check_interval,omitempty"`

	Progress_no_improvement_timeout AgDuration `yaml:"progress_no_improvement_timeout,omitempty" json:"progress_no_improvement_timeout,omitempty"`

	Output_format string `yaml:"output_format,omitempty" json:"output_format"`
}

// reproduces #Duration (schema/_common.cue) standalone.
type AgDuration string

// reproduces #CredentialMount (schema/agent.cue) standalone.
type AgCredentialMount struct {
	Src string `yaml:"src,omitempty" json:"src"`

	Dst string `yaml:"dst,omitempty" json:"dst"`

	Mode string `yaml:"mode,omitempty" json:"mode,omitempty"`

	Optional bool `yaml:"optional,omitempty" json:"optional,omitempty"`
}
