// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The BUILT-IN `package-group` plugin's OWN CUE schema — the typed input for the
// `package-group` KIND (the Calamares-style netinstall package group, formerly a
// core `package-group:` kind decoded into a typed core map). It is the SINGLE SOURCE for
// this plugin's params, used two ways (the same contract the reference
// exampleprobe/process and core `spec` use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by task cue:gen,
//     which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go.
//  2. VALIDATE authored input AT RUNTIME — the builtin serves this source over the
//     Describe channel (InProcTransport) exactly like an external serves it over
//     gRPC; the host splices it onto the base (base ++ plugin) and validates every
//     authored `package-group:` entity body against #PackageGroupInput BEFORE
//     runPluginKind dispatches (validateAuthoredPluginInput(ClassKind,
//     "package-group", …)) — the kind-class analogue of the verb plugin_input gate.
//
// SELF-CONTAINED: it references NO base def — every shared shape (#PgPackageItem,
// #PgDistroPackages, #PgAUR, #PgRepoBlock) is reproduced standalone here, so it
// compiles standalone (gengotypes + the load-gate compile) AND splices onto the base
// (the base ++ plugin splice exists to detect a def-name collision with the base, not
// to resolve base refs). It is a faithful reproduction of #Group (schema/group.cue):
// the same authored WIRE keys, so the host validates a real package-group entity.
//
// NAME: in node-form the entity name is the top-level node KEY, not a body field, so
// the assembled entity body NEVER carries `name`; #PackageGroupInput therefore makes
// it OPTIONAL (concrete validation would otherwise fail on the always-absent name).
type PackageGroupInput struct {
	Name string `yaml:"name,omitempty" json:"name,omitempty"`

	Description string `yaml:"description,omitempty" json:"description,omitempty"`

	Package []PgPackageItem `yaml:"package,omitempty" json:"package,omitempty"`

	Distro map[string]PgDistroPackages `yaml:"distro,omitempty" json:"distro,omitempty"`

	Hidden bool `yaml:"hidden,omitempty" json:"hidden"`

	Selected bool `yaml:"selected,omitempty" json:"selected"`

	Critical bool `yaml:"critical,omitempty" json:"critical"`

	Immutable bool `yaml:"immutable,omitempty" json:"immutable"`

	Expanded bool `yaml:"expanded,omitempty" json:"expanded"`

	Noncheckable bool `yaml:"noncheckable,omitempty" json:"noncheckable"`

	Pre_install string `yaml:"pre_install,omitempty" json:"pre_install,omitempty"`

	Post_install string `yaml:"post_install,omitempty" json:"post_install,omitempty"`

	Source string `yaml:"source,omitempty" json:"source,omitempty"`

	Subgroup []*PackageGroupInput `yaml:"subgroup,omitempty" json:"subgroup,omitempty"`

	Require []string `yaml:"require,omitempty" json:"require,omitempty"`
}

// bare scalar shorthand XOR object form (reproduces #PackageItem standalone).
type PgPackageItem any /* CUE disjunction: (string|struct) */

// reproduces #DistroPackages standalone.
type PgDistroPackages struct {
	Package []PgPackageItem `yaml:"package,omitempty" json:"package,omitempty"`

	Copr []string `yaml:"copr,omitempty" json:"copr,omitempty"`

	Repo []PgRepoBlock `yaml:"repo,omitempty" json:"repo,omitempty"`

	Exclude []string `yaml:"exclude,omitempty" json:"exclude,omitempty"`

	Option []string `yaml:"option,omitempty" json:"option,omitempty"`

	Module []string `yaml:"module,omitempty" json:"module,omitempty"`

	Aur PgAUR `yaml:"aur,omitempty" json:"aur,omitempty"`
}

// reproduces #RepoBlock standalone — `name` load-bearing, the rest pass through.
type PgRepoBlock map[string]any /* CUE top */

// reproduces #AUR standalone.
type PgAUR struct {
	Package []PgPackageItem `yaml:"package,omitempty" json:"package,omitempty"`

	Option []string `yaml:"option,omitempty" json:"option,omitempty"`

	Replace []string `yaml:"replace,omitempty" json:"replace,omitempty"`
}
