version: '3'

tasks:
  ov:
    desc: Build ov from source
    dir: "{{.ROOT_DIR}}"
    cmds:
      - mkdir -p bin layers/ov-cli/bin
      - cd ov && go build -o ../bin/ov .
      - cp bin/ov layers/ov-cli/bin/ov

  install:
    desc: Build and install ov to ~/.local/bin
    dir: "{{.ROOT_DIR}}"
    cmds:
      - mkdir -p ~/.local/bin
      - cd ov && go build -o ~/.local/bin/ov .
