package main

// node_parse.go — the generic parser for the UNIFIED node-form document tree (the
// ONE clean forward model; NO legacy kind-first parse). Every charly.yml element is
// a name-first node `<name>: {<discriminator>: <value>, <child>: <node>…}`:
//   - the ONE discriminator is a keyword from the unified vocabulary — an ENTITY
//     kind (box/candy/bundle/pod/vm/…), a DATA key (package/env/service/route/…),
//     or a STEP verb (run/check/agent-run/agent-check/include);
//   - an ENTITY node's value holds its SCALAR/object config; its COLLECTIONS (data)
//     and PLAN (steps) are CHILD nodes, and a resource nested under it is a
//     sub-ENTITY child;
//   - a DATA node carries its one collection payload; a STEP node carries its verb
//     prose + inline Op fields. Neither has children.
// The assembler (node_build.go) folds data + step children back into the entity's
// body and decodes it through the COMPLETE per-kind schema (#Candy/#Deploy/…), so
// the strict typing comes from the complete def — no per-arm value gaps.
// The vocabulary is CUE-derived: the former five hand maps (nodeEntityKinds /
// nodeResourceKinds / nodeStepVerbs / nodeDataKeys / nodeDocDirectives) were
// deleted in the CUE-single-source cutover; this parser now reads the spec-derived
// membership sets in reserved_registry.go (kindWordSet / resourceKindSet /
// stepKeywordSet / dataKeySet / docDirectiveSet), regenerated by `task cue:gen`
// from charly/schema/*.cue.

import (
	"fmt"

	"gopkg.in/yaml.v3"
)

// genericNode is one parsed node-form node.
type genericNode struct {
	name      string         // the node's key (its name)
	disc      string         // the discriminator keyword
	discClass string         // "entity" | "data" | "step"
	discValue *yaml.Node     // the discriminator's value (entity scalars / data payload / step prose)
	raw       *yaml.Node     // the WHOLE node mapping (a step folds its raw Op; a data node its payload)
	children  []*genericNode // sub-nodes (data / step / sub-entity) — entity nodes only
}

// classifyDisc returns the discriminator class for a keyword, or "" if not a
// discriminator (→ a child node name). asChild distinguishes a top-level node
// (every entity kind is an entity) from a child node (only RESOURCE kinds nest as
// sub-entities; candy/distro as a child are their DATA sense).
func classifyDisc(k string, asChild bool) string {
	if asChild {
		switch {
		case resourceKindSet[k]:
			return "entity"
		case stepKeywordSet[k]:
			return "step"
		case dataKeySet[k]:
			return "data"
		default:
			return ""
		}
	}
	switch {
	case kindWordSet[k]:
		return "entity"
	case stepKeywordSet[k]:
		return "step"
	}
	// A plugin-contributed kind: a registered ClassKind provider whose word is NOT a
	// core kind keyword (kindWordSet). Recognized dynamically so an external kind node
	// parses and routes to runPluginKind (E3 — every kind is a plugin, builtin or
	// external). Checked BEFORE dataKeySet because a plugin-extracted build-vocabulary
	// kind can COLLIDE with a data-key name (`distro:` is both the build-vocab kind AND
	// a candy package-surface data field): at the TOP LEVEL a node is an ENTITY, so the
	// registered kind wins; the data sense only applies as a CHILD (asChild branch
	// above, which has no kind check). This restores the pre-extraction classification
	// (when `distro` was a kindWord → "entity") and keeps the loader's "a non-deployable
	// kind rejects a sub-entity child" gate live for the build-vocab kinds. Only reached
	// for non-core discriminators, so the hot path is untouched.
	if _, ok := providerRegistry.ResolveKind(k); ok {
		return "entity"
	}
	if dataKeySet[k] {
		return "data"
	}
	return ""
}

// parseNode builds a genericNode from a node mapping (the value under `name:`).
// asChild is true when the node is a child of another node (vs a top-level node).
func parseNode(name string, m *yaml.Node, asChild bool) (*genericNode, error) {
	if m.Kind == yaml.DocumentNode && len(m.Content) == 1 {
		m = m.Content[0]
	}
	if m.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("node %q: expected a mapping value, got yaml kind %v", name, m.Kind)
	}
	gn := &genericNode{name: name, raw: m}
	type kv struct{ k, v *yaml.Node }
	var childPairs []kv
	// Phase 1 — a STEP node: a step verb is the SOLE discriminator, and EVERY other
	// key is an inline Op field (carried in raw), never a discriminator or a child.
	// Step verbs take precedence so an Op field that happens to share a data-key name
	// (e.g. a `port:` probe field on a `check:` step) is not misread as a second
	// discriminator.
	for i := 0; i+1 < len(m.Content); i += 2 {
		if stepKeywordSet[m.Content[i].Value] {
			if gn.disc != "" {
				return nil, fmt.Errorf("node %q: two step verbs (%q and %q) — a step has exactly one", name, gn.disc, m.Content[i].Value)
			}
			gn.disc, gn.discClass, gn.discValue = m.Content[i].Value, "step", m.Content[i+1]
		}
	}
	if gn.disc != "" {
		return gn, nil // step node — Op fields stay in raw, no children
	}
	// Phase 2 — an ENTITY or DATA node: exactly one entity-kind / data-key
	// discriminator; every other key is a child-node name (entity nodes only).
	for i := 0; i+1 < len(m.Content); i += 2 {
		key, val := m.Content[i], m.Content[i+1]
		cls := classifyDisc(key.Value, asChild)
		if cls == "" {
			childPairs = append(childPairs, kv{key, val})
			continue
		}
		if gn.disc != "" {
			return nil, fmt.Errorf("node %q: two discriminators (%q and %q) — a node has exactly one", name, gn.disc, key.Value)
		}
		gn.disc, gn.discClass, gn.discValue = key.Value, cls, val
	}
	if gn.disc == "" {
		return nil, fmt.Errorf("node %q: no discriminator (expected an entity kind, data key, or step verb)", name)
	}
	// "Everything except scalars is a node": an entity value holds ONLY scalar
	// fields — every collection / composition / object / plan step is a CHILD node.
	// Reject a non-scalar field sitting in the value directly (the deterministic
	// child-node gate; CUE owns the closed-typo / wrong-kind-child strictness).
	if gn.discClass == "entity" && gn.discValue != nil && gn.discValue.Kind == yaml.MappingNode {
		for i := 0; i+1 < len(gn.discValue.Content); i += 2 {
			vk := gn.discValue.Content[i].Value
			if dataKeySet[vk] || stepKeywordSet[vk] || vk == "plan" {
				return nil, fmt.Errorf("node %q: %q must be a CHILD node, not a field in the %q value — everything except scalars is a node (run: charly migrate)", name, vk, gn.disc)
			}
		}
	}
	// Only ENTITY nodes have child nodes; for data/step nodes the non-discriminator
	// keys are inline Op/payload fields (left in raw), never children.
	if gn.discClass == "entity" {
		for _, c := range childPairs {
			child, err := parseNode(c.k.Value, c.v, true)
			if err != nil {
				return nil, err
			}
			// Wrong-kind-child gate: only a DEPLOYABLE kind nests sub-ENTITY members
			// (a pod/vm/k8s/local/android/group). A non-deployable kind
			// (candy/distro/…) admits ONLY data + step children. (This replaces
			// the per-child CUE kind-disjunction, which was an O(N×kinds×children)
			// blow-up; CUE still strictly validates each node's closed VALUE.)
			if child.discClass == "entity" && !resourceKindSet[gn.disc] {
				return nil, fmt.Errorf("node %q (kind %q): sub-entity child %q (kind %q) is not allowed — only deployable kinds (pod/vm/k8s/local/android/group) nest sub-entities", name, gn.disc, child.name, child.disc)
			}
			gn.children = append(gn.children, child)
		}
	}
	return gn, nil
}

// parseNodeTree walks a whole node-form document mapping into its reserved
// directives and its top-level entity nodes.
func parseNodeTree(doc *yaml.Node) (directives map[string]*yaml.Node, nodes []*genericNode, err error) {
	if doc.Kind == yaml.DocumentNode && len(doc.Content) == 1 {
		doc = doc.Content[0]
	}
	if doc.Kind != yaml.MappingNode {
		return nil, nil, fmt.Errorf("node-form document: expected a top-level mapping, got yaml kind %v", doc.Kind)
	}
	directives = map[string]*yaml.Node{}
	for i := 0; i+1 < len(doc.Content); i += 2 {
		key, val := doc.Content[i], doc.Content[i+1]
		if docDirectiveSet[key.Value] {
			directives[key.Value] = val
			continue
		}
		gn, e := parseNode(key.Value, val, false)
		if e != nil {
			return nil, nil, e
		}
		nodes = append(nodes, gn)
	}
	return directives, nodes, nil
}
