// Code generated by pluginsgen (charly box generate-plugins). DO NOT EDIT.
//
// One registerCompiledPlugin() call per plugin candy named in charly.yml
// `compiled_plugins:`. Regenerated by `task build:charly` before `go build`; the
// matching `use` directives land in the repo-root go.work. Edit charly.yml's
// compiled_plugins and re-run the generator, never this file.
package main

import (
	cp_plugin_example "github.com/overthinkos/overthink/candy/plugin-example"
	cp_plugin_example_external "github.com/overthinkos/overthink/candy/plugin-example-external"
	cp_plugin_port "github.com/overthinkos/overthink/candy/plugin-port"
)

func init() {
	registerCompiledPlugin(cp_plugin_example.NewProvider(), cp_plugin_example.NewMeta())
	registerCompiledPlugin(cp_plugin_example_external.NewProvider(), cp_plugin_example_external.NewMeta())
	registerCompiledCheckVerb(cp_plugin_port.NewCheckVerb(), cp_plugin_port.SchemaFS, cp_plugin_port.SchemaDir, cp_plugin_port.InputDefs)
}
