// Code generated by pluginsgen (charly box generate-plugins). DO NOT EDIT.
//
// One registerCompiledPlugin() call per plugin candy named in charly.yml
// `compiled_plugins:`. Regenerated by `task build:charly` before `go build`; the
// matching `use` directives land in the repo-root go.work. Edit charly.yml's
// compiled_plugins and re-run the generator, never this file.
package main

import (
	cp_plugin_addr "github.com/overthinkos/overthink/candy/plugin-addr"
	cp_plugin_dns "github.com/overthinkos/overthink/candy/plugin-dns"
	cp_plugin_example "github.com/overthinkos/overthink/candy/plugin-example"
	cp_plugin_example_external "github.com/overthinkos/overthink/candy/plugin-example-external"
	cp_plugin_examplerunverb "github.com/overthinkos/overthink/candy/plugin-examplerunverb"
	cp_plugin_http "github.com/overthinkos/overthink/candy/plugin-http"
	cp_plugin_interface "github.com/overthinkos/overthink/candy/plugin-interface"
	cp_plugin_kernel_param "github.com/overthinkos/overthink/candy/plugin-kernel-param"
	cp_plugin_matching "github.com/overthinkos/overthink/candy/plugin-matching"
	cp_plugin_mount "github.com/overthinkos/overthink/candy/plugin-mount"
	cp_plugin_port "github.com/overthinkos/overthink/candy/plugin-port"
	cp_plugin_process "github.com/overthinkos/overthink/candy/plugin-process"
	cp_plugin_unix_group "github.com/overthinkos/overthink/candy/plugin-unix-group"
	cp_plugin_user "github.com/overthinkos/overthink/candy/plugin-user"
)

func init() {
	registerCompiledPlugin(cp_plugin_example.NewProvider(), cp_plugin_example.NewMeta())
	registerCompiledPlugin(cp_plugin_example_external.NewProvider(), cp_plugin_example_external.NewMeta())
	registerCompiledCheckVerb(cp_plugin_port.NewCheckVerb(), cp_plugin_port.SchemaFS, cp_plugin_port.SchemaDir, cp_plugin_port.InputDefs)
	registerCompiledCheckVerb(cp_plugin_process.NewCheckVerb(), cp_plugin_process.SchemaFS, cp_plugin_process.SchemaDir, cp_plugin_process.InputDefs)
	registerCompiledCheckVerb(cp_plugin_interface.NewCheckVerb(), cp_plugin_interface.SchemaFS, cp_plugin_interface.SchemaDir, cp_plugin_interface.InputDefs)
	registerCompiledCheckVerb(cp_plugin_addr.NewCheckVerb(), cp_plugin_addr.SchemaFS, cp_plugin_addr.SchemaDir, cp_plugin_addr.InputDefs)
	registerCompiledCheckVerb(cp_plugin_dns.NewCheckVerb(), cp_plugin_dns.SchemaFS, cp_plugin_dns.SchemaDir, cp_plugin_dns.InputDefs)
	registerCompiledCheckVerb(cp_plugin_examplerunverb.NewCheckVerb(), cp_plugin_examplerunverb.SchemaFS, cp_plugin_examplerunverb.SchemaDir, cp_plugin_examplerunverb.InputDefs)
	registerCompiledPlugin(cp_plugin_matching.NewProvider(), cp_plugin_matching.NewMeta())
	registerCompiledCheckVerb(cp_plugin_http.NewCheckVerb(), cp_plugin_http.SchemaFS, cp_plugin_http.SchemaDir, cp_plugin_http.InputDefs)
	registerCompiledCheckVerb(cp_plugin_kernel_param.NewCheckVerb(), cp_plugin_kernel_param.SchemaFS, cp_plugin_kernel_param.SchemaDir, cp_plugin_kernel_param.InputDefs)
	registerCompiledCheckVerb(cp_plugin_mount.NewCheckVerb(), cp_plugin_mount.SchemaFS, cp_plugin_mount.SchemaDir, cp_plugin_mount.InputDefs)
	registerCompiledCheckVerb(cp_plugin_user.NewCheckVerb(), cp_plugin_user.SchemaFS, cp_plugin_user.SchemaDir, cp_plugin_user.InputDefs)
	registerCompiledCheckVerb(cp_plugin_unix_group.NewCheckVerb(), cp_plugin_unix_group.SchemaFS, cp_plugin_unix_group.SchemaDir, cp_plugin_unix_group.InputDefs)
}
