package main

import (
	"fmt"
	"strings"
)

// generatePodQuadlet produces the contents of a quadlet .pod file.
// The pod owns the shared network namespace: ports, network, and Tailscale tun interface.
//
// Dual networking: the pod stays on the "charly" bridge (reachable by other containers)
// while the Tailscale sidecar adds a tun interface for exit node routing.
// --exit-node-allow-lan-access exempts bridge subnets from the tunnel.
func generatePodQuadlet(cfg QuadletConfig) string {
	podName := PodNameInstance(cfg.BoxName, cfg.Instance)

	var b strings.Builder
	fmt.Fprintf(&b, "# %s.pod (generated by charly config)\n", podName)

	b.WriteString("[Pod]\n")
	fmt.Fprintf(&b, "PodName=%s\n", podName)

	// Network: keep the pod on the bridge for container-to-container connectivity.
	// The Tailscale sidecar creates a tun interface for exit node routing;
	// --exit-node-allow-lan-access preserves bridge subnet access.
	if cfg.Network != "" {
		fmt.Fprintf(&b, "Network=%s\n", cfg.Network)
	}

	// DNS: when Tailscale sidecar is present, configure dual DNS.
	// TS_ACCEPT_DNS=false prevents Tailscale from rewriting /etc/resolv.conf.
	// Pod-level --dns flags provide both resolvers:
	//   10.89.0.1       — aardvark-dns (container DNS + external forwarding)
	//   100.100.100.100 — Tailscale MagicDNS (.ts.net names)
	if hasTailscaleSidecar(cfg.Sidecar) {
		b.WriteString("PodmanArgs=--dns=10.89.0.1\n")
		b.WriteString("PodmanArgs=--dns=100.100.100.100\n")
		b.WriteString("PodmanArgs=--dns-search=dns.podman\n")
	}

	// Shared memory size: must be set on the pod (per-container ShmSize is ignored in pod mode)
	if cfg.Security.ShmSize != "" {
		fmt.Fprintf(&b, "PodmanArgs=--shm-size=%s\n", cfg.Security.ShmSize)
	}

	// Port mappings from the app container go on the pod (shared network namespace)
	for _, port := range cfg.Ports {
		fmt.Fprintf(&b, "PodmanArgs=-p %s\n", localizePort(port, cfg.BindAddress))
	}

	b.WriteString("\n[Install]\n")
	if cfg.EncryptedMounts && !cfg.KeyringBackend {
		b.WriteString("# Encrypted volumes require 'charly start' (no keyring auto-unlock)\n")
	} else {
		b.WriteString("WantedBy=default.target\n")
	}

	return b.String()
}

// hasTailscaleSidecar checks if any resolved sidecar is a Tailscale sidecar.
func hasTailscaleSidecar(sidecars []ResolvedSidecar) bool {
	for _, sc := range sidecars {
		if sc.Name == "tailscale" {
			return true
		}
	}
	return false
}

// generateSidecarQuadlet produces the contents of a sidecar .container file.
func generateSidecarQuadlet(sc ResolvedSidecar, podName string) string {
	var b strings.Builder

	ctrName := podName + "-" + sc.Name

	fmt.Fprintf(&b, "# %s.container (generated by charly config)\n", ctrName)
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=OpenCharly %s sidecar: %s\n", podName, sc.Name)

	b.WriteString("\n[Container]\n")
	fmt.Fprintf(&b, "Pod=%s.pod\n", podName)
	fmt.Fprintf(&b, "Image=%s\n", sc.Image)
	fmt.Fprintf(&b, "ContainerName=%s\n", ctrName)

	// Volumes
	for _, vol := range sc.Volume {
		fmt.Fprintf(&b, "Volume=%s:%s\n", vol.VolumeName, vol.ContainerPath)
	}

	// Environment variables (sorted for deterministic output)
	for _, kv := range SortedSidecarEnv(sc.Env) {
		if before, after, ok := strings.Cut(kv, "="); ok {
			key := before
			val := after
			if IsSidecarEnvQuotable(val) {
				fmt.Fprintf(&b, "Environment=%s=%q\n", key, val)
			} else {
				fmt.Fprintf(&b, "Environment=%s\n", kv)
			}
		} else {
			fmt.Fprintf(&b, "Environment=%s\n", kv)
		}
	}

	// Secrets (podman Secret= directives)
	for _, s := range sc.Secret {
		if s.Env != "" {
			fmt.Fprintf(&b, "Secret=%s,type=env,target=%s\n", s.Name, s.Env)
		} else if s.Target != "" {
			fmt.Fprintf(&b, "Secret=%s,target=%s\n", s.Name, s.Target)
		}
	}

	// Security: capabilities
	for _, cap := range sc.Security.CapAdd {
		fmt.Fprintf(&b, "AddCapability=%s\n", cap)
	}
	// Security: devices
	for _, dev := range sc.Security.Devices {
		fmt.Fprintf(&b, "AddDevice=%s\n", dev)
	}
	// Security: privileged
	if sc.Security.Privileged {
		b.WriteString("SecurityLabelDisable=true\n")
		b.WriteString("PodmanArgs=--privileged\n")
	}
	// Security: security_opt
	for _, opt := range sc.Security.SecurityOpt {
		if opt == "label=disable" {
			b.WriteString("SecurityLabelDisable=true\n")
		} else {
			fmt.Fprintf(&b, "PodmanArgs=--security-opt %s\n", opt)
		}
	}
	// Security: cgroupns — needed when a workload requires host cgroup
	// controllers (e.g. k3s needs cpuset which rootless user slices
	// don't delegate to sub-slices). Candy-intrinsic, no-op for VM/host.
	if sc.Security.CgroupNS != "" {
		fmt.Fprintf(&b, "PodmanArgs=--cgroupns=%s\n", sc.Security.CgroupNS)
	}

	b.WriteString("\n[Service]\n")
	b.WriteString("Restart=always\n")
	b.WriteString("TimeoutStartSec=120\n")

	return b.String()
}

// --- Filename helpers ---

// podQuadletFilename returns the quadlet filename for a pod.
func podQuadletFilename(boxName string) string {
	return PodName(boxName) + ".pod"
}

// podQuadletFilenameInstance returns the quadlet filename for a pod with optional instance.
func podQuadletFilenameInstance(boxName, instance string) string {
	return PodNameInstance(boxName, instance) + ".pod"
}

// sidecarQuadletFilename returns the quadlet filename for a sidecar container.
func sidecarQuadletFilename(boxName, sidecarName string) string {
	return SidecarContainerName(boxName, sidecarName) + ".container"
}

// sidecarQuadletFilenameInstance returns the quadlet filename for a sidecar with optional instance.
func sidecarQuadletFilenameInstance(boxName, instance, sidecarName string) string {
	return SidecarContainerNameInstance(boxName, instance, sidecarName) + ".container"
}
