package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// QuadletConfig holds the parameters for generating a quadlet .container file
type QuadletConfig struct {
	BoxName         string              // box name from charly.yml (e.g. "fedora-test")
	ImageRef        string              // full image reference (e.g. "ghcr.io/overthinkos/fedora-test:latest")
	Home            string              // container home directory (for WorkingDir resolution)
	Ports           []string            // port mappings from charly.yml (e.g. ["8000:8000", "8080:8080"])
	Volumes         []VolumeMount       // named volumes from candy manifest declarations
	BindMounts      []ResolvedBindMount // bind-backed volumes from deploy config
	GPU             bool                // enable GPU passthrough via CDI (AddDevice=nvidia.com/gpu=all)
	BindAddress     string              // host bind address for port publishing (e.g. "127.0.0.1" or "0.0.0.0")
	Tunnel          *TunnelConfig       // tunnel configuration (nil if no tunnel)
	UID             int                 // container user UID (for UserNS keep-id mapping)
	GID             int                 // container user GID (for UserNS keep-id mapping)
	Env             []string            // runtime env vars (KEY=VALUE pairs)
	EnvFile         string              // absolute path to env file for EnvironmentFile= directive
	Instance        string              // instance name for running multiple containers of same image
	Security        SecurityConfig      // container security options
	Network         string              // container network mode (e.g. "host", "none")
	Version         string              // image definition version (CalVer)
	Status          string              // effective status (working, testing, broken)
	Info            string              // status description
	Secrets         []CollectedSecret   // container secrets (podman Secret= directives)
	Entrypoint      []string            // init system entrypoint (e.g., ["supervisord", "-n", "-c", "/etc/supervisord.conf"])
	CharlyBin       string              // absolute path to charly binary (for ExecStartPre)
	EncryptedMounts bool                // true when any bind mount is encrypted
	KeyringBackend  bool                // true when credential store is Secret Service (keyring)
	PodName         string              // non-empty when this container belongs to a pod (sidecar mode)
	Sidecar         []ResolvedSidecar   // sidecar definitions (used to detect tailscale sidecar for tunnel)
}

// generateQuadlet produces the contents of a quadlet .container file.
func generateQuadlet(cfg QuadletConfig) string {
	name := containerNameInstance(cfg.BoxName, cfg.Instance)
	var b strings.Builder

	desc := cfg.BoxName
	if cfg.Instance != "" {
		desc = cfg.BoxName + " (" + cfg.Instance + ")"
	}
	fmt.Fprintf(&b, "# %s.container (generated by charly config)\n", name)
	if cfg.Version != "" {
		fmt.Fprintf(&b, "# Version: %s\n", cfg.Version)
	}
	status := resolveStatus(cfg.Status)
	if status != "working" {
		fmt.Fprintf(&b, "# Status: %s\n", status)
		if cfg.Info != "" {
			fmt.Fprintf(&b, "# Info: %s\n", cfg.Info)
		}
	}
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=OpenCharly %s\n", desc)
	b.WriteString("After=network-online.target\n")
	if cfg.Tunnel != nil && cfg.Tunnel.Provider == "cloudflare" {
		tunnelSvc := tunnelServiceFilename(cfg.BoxName)
		fmt.Fprintf(&b, "Wants=%s\n", tunnelSvc)
	}

	b.WriteString("\n[Container]\n")
	if cfg.PodName != "" {
		fmt.Fprintf(&b, "Pod=%s.pod\n", cfg.PodName)
	}
	fmt.Fprintf(&b, "Image=%s\n", cfg.ImageRef)
	fmt.Fprintf(&b, "ContainerName=%s\n", name)
	workDir := resolveWorkingDir(cfg.Volumes, cfg.BindMounts, cfg.Home, cfg.BoxName, cfg.Instance)
	fmt.Fprintf(&b, "WorkingDir=%s\n", workDir)
	// When in a pod, network and ports are owned by the pod (shared namespace)
	if cfg.PodName == "" {
		if cfg.Network != "" {
			fmt.Fprintf(&b, "Network=%s\n", cfg.Network)
		}
		for _, port := range cfg.Ports {
			fmt.Fprintf(&b, "PublishPort=%s\n", localizePort(port, cfg.BindAddress))
		}
	}
	// A bind mount that targets the same container path as a named
	// volume is an OVERRIDE — emit only the bind, drop the named
	// volume. Without this filter, podman rejects the unit at start
	// time with "duplicate mount destination" (e.g. when charly.yml
	// pins a `project` volume to a host bind at /workspace and the
	// image's volume label also declares the named `project` volume
	// at /workspace).
	bindPaths := make(map[string]bool, len(cfg.BindMounts))
	for _, bm := range cfg.BindMounts {
		bindPaths[bm.ContPath] = true
	}
	for _, vol := range cfg.Volumes {
		if bindPaths[vol.ContainerPath] {
			continue
		}
		fmt.Fprintf(&b, "Volume=%s:%s\n", vol.VolumeName, vol.ContainerPath)
	}
	for _, bm := range cfg.BindMounts {
		fmt.Fprintf(&b, "Volume=%s:%s\n", bm.HostPath, bm.ContPath)
	}
	for _, m := range cfg.Security.Mounts {
		if strings.HasPrefix(m, "tmpfs:") {
			// tmpfs:/path:options → Tmpfs=/path:options
			fmt.Fprintf(&b, "Tmpfs=%s\n", strings.TrimPrefix(m, "tmpfs:"))
		} else {
			fmt.Fprintf(&b, "Volume=%s\n", m)
		}
	}
	for _, s := range cfg.Secrets {
		if s.Env != "" {
			fmt.Fprintf(&b, "Secret=%s,type=env,target=%s\n", s.Name, s.Env)
		} else {
			fmt.Fprintf(&b, "Secret=%s,target=%s\n", s.Name, s.Target)
		}
	}
	if cfg.GPU && !cfg.Security.Privileged {
		b.WriteString("AddDevice=nvidia.com/gpu=all\n")
	}
	if cfg.Security.Privileged {
		b.WriteString("SecurityLabelDisable=true\n")
		b.WriteString("PodmanArgs=--privileged\n")
		// Pass security_opt even when privileged — nested containers need explicit opts
		for _, opt := range cfg.Security.SecurityOpt {
			if opt != "label=disable" { // already handled by SecurityLabelDisable
				fmt.Fprintf(&b, "PodmanArgs=--security-opt %s\n", opt)
			}
		}
		// Privileged containers that also declare devices still need them
		// explicitly — --privileged grants /dev/* host-wide access but
		// some workloads (k3s → /dev/fuse) prefer the explicit wiring so
		// the device is present regardless of host /dev/ layout.
		for _, dev := range cfg.Security.Devices {
			fmt.Fprintf(&b, "AddDevice=%s\n", dev)
		}
	} else {
		for _, cap := range cfg.Security.CapAdd {
			fmt.Fprintf(&b, "AddCapability=%s\n", cap)
		}
		for _, dev := range cfg.Security.Devices {
			fmt.Fprintf(&b, "AddDevice=%s\n", dev)
		}
		for _, opt := range cfg.Security.SecurityOpt {
			if opt == "label=disable" {
				b.WriteString("SecurityLabelDisable=true\n")
			} else {
				fmt.Fprintf(&b, "PodmanArgs=--security-opt %s\n", opt)
			}
		}
	}
	// CgroupNS applies in both privileged and non-privileged paths —
	// e.g. k3s needs --cgroupns=host to see the host's cpuset cgroup
	// controller that the rootless user slice doesn't delegate to its
	// sub-slices. Declared at the candy level; no-op for VM/host deploys.
	if cfg.Security.CgroupNS != "" {
		fmt.Fprintf(&b, "PodmanArgs=--cgroupns=%s\n", cfg.Security.CgroupNS)
	}
	for _, group := range cfg.Security.GroupAdd {
		fmt.Fprintf(&b, "GroupAdd=%s\n", group)
	}
	if cfg.Security.IpcMode != "" {
		// PodmanArgs=--ipc=<mode>: emit BEFORE ShmSize so the gate
		// below sees the same value podman will receive at runtime.
		fmt.Fprintf(&b, "PodmanArgs=--ipc=%s\n", cfg.Security.IpcMode)
	}
	if cfg.Security.ShmSize != "" && cfg.PodName == "" && !ipcModeBlocksShmSize(cfg.Security.IpcMode) {
		// In pod mode, ShmSize is set on the pod (infra container owns /dev/shm).
		// When IPC=host, podman REJECTS shm_size because the host's /dev/shm
		// is shared in-kernel; emit no ShmSize directive in that case (the
		// host's /dev/shm size already governs the in-container view).
		fmt.Fprintf(&b, "ShmSize=%s\n", cfg.Security.ShmSize)
	}
	if len(cfg.BindMounts) > 0 {
		fmt.Fprintf(&b, "UserNS=keep-id:uid=%d,gid=%d\n", cfg.UID, cfg.GID)
	}
	for _, e := range cfg.Env {
		// Quote the value if it contains characters that systemd would interpret
		if idx := strings.IndexByte(e, '='); idx >= 0 {
			key := e[:idx]
			val := e[idx+1:]
			if strings.ContainsAny(val, `"{}[] `) {
				fmt.Fprintf(&b, "Environment=%s=%q\n", key, val)
			} else {
				fmt.Fprintf(&b, "Environment=%s\n", e)
			}
		} else {
			fmt.Fprintf(&b, "Environment=%s\n", e)
		}
	}
	if cfg.EnvFile != "" {
		fmt.Fprintf(&b, "EnvironmentFile=%s\n", cfg.EnvFile)
	}
	if len(cfg.Entrypoint) > 0 {
		fmt.Fprintf(&b, "Exec=%s\n", strings.Join(cfg.Entrypoint, " "))
	} else {
		b.WriteString("Exec=sleep infinity\n")
	}

	b.WriteString("\n[Service]\n")
	b.WriteString("Restart=always\n")
	// Resource caps. Emitted as native systemd cgroup directives so they apply
	// to the container's cgroup slice regardless of podman version. MemoryHigh
	// acts as a soft limit (reclaim pressure), MemoryMax is the hard OOM line.
	// Size values are normalized to uppercase suffixes (K/M/G/T) because systemd
	// silently rejects lowercase and falls back to "infinity" — verified the hard
	// way against a live systemctl show against this exact unit.
	if v := normalizeCgroupSize(cfg.Security.MemoryMax); v != "" {
		fmt.Fprintf(&b, "MemoryMax=%s\n", v)
	}
	if v := normalizeCgroupSize(cfg.Security.MemoryHigh); v != "" {
		fmt.Fprintf(&b, "MemoryHigh=%s\n", v)
	}
	if v := normalizeCgroupSize(cfg.Security.MemorySwapMax); v != "" {
		fmt.Fprintf(&b, "MemorySwapMax=%s\n", v)
	}
	if q := formatCPUQuota(cfg.Security.Cpus); q != "" {
		fmt.Fprintf(&b, "CPUQuota=%s\n", q)
	}
	if cfg.EncryptedMounts && cfg.CharlyBin != "" {
		imgArg := cfg.BoxName
		if cfg.Instance != "" {
			imgArg = cfg.BoxName + " -i " + cfg.Instance
		}
		fmt.Fprintf(&b, "ExecStartPre=%s config mount %s\n", cfg.CharlyBin, imgArg)
		if cfg.KeyringBackend {
			// Wait indefinitely for keyring unlock (PAM login)
			b.WriteString("TimeoutStartSec=0\n")
		} else {
			b.WriteString("TimeoutStartSec=900\n")
		}
	} else {
		b.WriteString("TimeoutStartSec=900\n")
	}
	// Host-based tailscale serve/funnel: always generated when tunnel: tailscale is configured.
	// Independent of sidecars — the host tunnel serves ports on the host's tailnet,
	// while the sidecar handles exit node routing on a potentially different tailnet.
	if cfg.Tunnel != nil && cfg.Tunnel.Provider == "tailscale" && len(cfg.Tunnel.Ports) > 0 {
		for _, tp := range cfg.Tunnel.Ports {
			port := fmt.Sprintf("%d", tp.Port)
			switch {
			case tp.Protocol == "udp":
				fmt.Fprintf(&b, "# Port %s: UDP — not tunneled (tailscale serve does not support UDP; accessible directly between tailnet nodes)\n", port)
			case tp.Public:
				flag := tailscaleFlag(tp.Protocol)
				target := schemeTarget(tp.Protocol, tp.backend())
				fmt.Fprintf(&b, "# Port %s: public (internet-accessible)\n", port)
				fmt.Fprintf(&b, "ExecStartPost=tailscale funnel --bg %s=%s %s\n", flag, port, target)
			default:
				flag := tailscaleFlag(tp.Protocol)
				target := schemeTarget(tp.Protocol, tp.backend())
				proto := "https"
				if isTCPFamily(tp.Protocol) {
					proto = "tcp"
				}
				fmt.Fprintf(&b, "# Port %s: private (tailnet-only, %s)\n", port, proto)
				fmt.Fprintf(&b, "ExecStartPost=tailscale serve --bg %s=%s %s\n", flag, port, target)
			}
		}
		for _, tp := range cfg.Tunnel.Ports {
			if tp.Protocol == "udp" {
				continue // UDP ports have no tunnel commands to stop
			}
			port := fmt.Sprintf("%d", tp.Port)
			flag := tailscaleFlag(tp.Protocol)
			if tp.Public {
				fmt.Fprintf(&b, "ExecStopPost=-tailscale funnel %s=%s off\n", flag, port)
			} else {
				fmt.Fprintf(&b, "ExecStopPost=-tailscale serve %s=%s off\n", flag, port)
			}
		}
	}

	b.WriteString("\n[Install]\n")
	if cfg.EncryptedMounts && !cfg.KeyringBackend {
		// Non-keyring backends can't auto-unlock at boot; require manual charly start
		b.WriteString("# Encrypted volumes require 'charly start' (no keyring auto-unlock)\n")
	} else {
		b.WriteString("WantedBy=default.target\n")
	}

	return b.String()
}

// generateTunnelUnit produces a companion systemd service unit for cloudflare tunnels.
func generateTunnelUnit(cfg QuadletConfig) string {
	if cfg.Tunnel == nil || cfg.Tunnel.Provider != "cloudflare" {
		return ""
	}

	name := containerName(cfg.BoxName)
	tunnelName := cfg.Tunnel.TunnelName

	cfgPath, _ := tunnelConfigPath(tunnelName)

	var b strings.Builder
	fmt.Fprintf(&b, "# %s-tunnel.service (generated by charly config)\n", name)
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=Cloudflare Tunnel for %s\n", name)
	fmt.Fprintf(&b, "BindsTo=%s.service\n", name)
	fmt.Fprintf(&b, "After=%s.service\n", name)

	b.WriteString("\n[Service]\n")
	fmt.Fprintf(&b, "ExecStart=cloudflared tunnel --config %s run %s\n", cfgPath, tunnelName)
	b.WriteString("Restart=always\n")

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")

	return b.String()
}

// tunnelServiceFilename returns the systemd service filename for a tunnel companion unit.
func tunnelServiceFilename(boxName string) string {
	return containerName(boxName) + "-tunnel.service"
}

// quadletDir returns the user-level quadlet directory.
func quadletDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("determining home directory: %w", err)
	}
	return filepath.Join(home, ".config", "containers", "systemd"), nil
}

// systemdUserDir returns the user-level systemd unit directory (~/.config/systemd/user/).
func systemdUserDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("determining home directory: %w", err)
	}
	return filepath.Join(home, ".config", "systemd", "user"), nil
}

// quadletFilename returns the quadlet filename for an image.
func quadletFilename(boxName string) string {
	return containerName(boxName) + ".container"
}

// quadletFilenameInstance returns the quadlet filename for an image with optional instance.
func quadletFilenameInstance(boxName, instance string) string {
	return containerNameInstance(boxName, instance) + ".container"
}

// serviceName returns the systemd service name for an image.
func serviceName(boxName string) string {
	return containerName(boxName) + ".service"
}

// serviceNameInstance returns the systemd service name for an image with optional instance.
func serviceNameInstance(boxName, instance string) string {
	return containerNameInstance(boxName, instance) + ".service"
}

// quadletExists checks whether a .container file exists for the given image.
func quadletExists(boxName string) (bool, error) {
	return quadletExistsInstance(boxName, "")
}

// quadletExistsInstance checks whether a .container file exists for the given image/instance.
func quadletExistsInstance(boxName, instance string) (bool, error) {
	qdir, err := quadletDir()
	if err != nil {
		return false, err
	}
	qpath := filepath.Join(qdir, quadletFilenameInstance(boxName, instance))
	_, err = os.Stat(qpath)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// normalizeCgroupSize converts a podman-style size string ("6g", "512m") into
// the form systemd's cgroup directives require: uppercase K/M/G/T suffixes.
// Systemd silently rejects lowercase suffixes on MemoryMax/MemoryHigh/
// MemorySwapMax and falls back to "infinity", which would mean the quadlet
// file looks correct but the cap never takes effect. Returns an empty string
// for empty/zero input so callers can skip emitting the directive.
func normalizeCgroupSize(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	n := len(s)
	last := s[n-1]
	// Already uppercase suffix → pass through.
	if last == 'K' || last == 'M' || last == 'G' || last == 'T' {
		return s
	}
	// Lowercase suffix → uppercase.
	if last == 'k' || last == 'm' || last == 'g' || last == 't' {
		return s[:n-1] + strings.ToUpper(string(last))
	}
	// No suffix (pure digits) → pass through (systemd accepts raw bytes).
	return s
}

// formatCPUQuota converts a podman-style --cpus value ("2.5") into the
// percentage form systemd's CPUQuota= directive expects ("250%"). Returns an
// empty string if the input is empty or unparseable, so callers can skip
// emitting the directive entirely.
func formatCPUQuota(cpus string) string {
	cpus = strings.TrimSpace(cpus)
	if cpus == "" {
		return ""
	}
	f, err := strconv.ParseFloat(cpus, 64)
	if err != nil || f <= 0 {
		return ""
	}
	return fmt.Sprintf("%d%%", int(f*100+0.5))
}
