package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateQuadlet(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "fedora-test",
		ImageRef:    "ghcr.io/overthinkos/fedora-test:latest",
		Home:        "/home/user",
		Ports:       []string{"8000:8000", "8080:8080"},
		BindAddress: "127.0.0.1",
		Entrypoint:  []string{"supervisord", "-n", "-c", "/etc/supervisord.conf"},
	}

	got := generateQuadlet(cfg)

	want := `# charly-fedora-test.container (generated by charly config)
# Status: testing
[Unit]
Description=OpenCharly fedora-test
After=network-online.target

[Container]
Image=ghcr.io/overthinkos/fedora-test:latest
ContainerName=charly-fedora-test
WorkingDir=/home/user
PublishPort=127.0.0.1:8000:8000
PublishPort=127.0.0.1:8080:8080
Exec=supervisord -n -c /etc/supervisord.conf

[Service]
Restart=always
TimeoutStartSec=900

[Install]
WantedBy=default.target
`

	if got != want {
		t.Errorf("generateQuadlet() =\n%s\nwant\n%s", got, want)
	}
}

func TestGenerateQuadletNoPorts(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "fedora",
		ImageRef:    "ghcr.io/overthinkos/fedora:latest",
		Home:        "/tmp",
		Ports:       nil,
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if strings.Contains(got, "PublishPort") {
		t.Error("expected no PublishPort lines when ports are nil")
	}
	if !strings.Contains(got, "ContainerName=charly-fedora") {
		t.Error("expected ContainerName=charly-fedora")
	}
	if !strings.Contains(got, "WorkingDir=/tmp") {
		t.Error("expected WorkingDir with home path")
	}
}

func TestGenerateQuadletSinglePort(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "myapp",
		ImageRef:    "myapp:latest",
		Home:        "/home/user",
		Ports:       []string{"9090"},
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "PublishPort=127.0.0.1:9090:9090") {
		t.Errorf("expected single port to expand to 127.0.0.1:9090:9090, got:\n%s", got)
	}
	count := strings.Count(got, "PublishPort=")
	if count != 1 {
		t.Errorf("expected 1 PublishPort line, got %d", count)
	}
}

func TestGenerateQuadletWithVolumes(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "openclaw",
		ImageRef:    "ghcr.io/overthinkos/openclaw:latest",
		Home:        "/home/user",
		Ports:       []string{"18789:18789"},
		BindAddress: "127.0.0.1",
		Volumes: []VolumeMount{
			{VolumeName: "charly-openclaw-data", ContainerPath: "/home/user/.openclaw"},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "Volume=charly-openclaw-data:/home/user/.openclaw") {
		t.Errorf("expected Volume line for openclaw data, got:\n%s", got)
	}
	if !strings.Contains(got, "WorkingDir=/home/user") {
		t.Error("expected WorkingDir line")
	}
	if !strings.Contains(got, "PublishPort=127.0.0.1:18789:18789") {
		t.Error("expected PublishPort line")
	}
}

func TestGenerateQuadletWithGPU(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "ollama",
		ImageRef:    "ghcr.io/overthinkos/ollama:latest",
		Home:        "/home/user",
		GPU:         true,
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "AddDevice=nvidia.com/gpu=all") {
		t.Errorf("expected AddDevice=nvidia.com/gpu=all when GPU=true, got:\n%s", got)
	}
}

func TestGenerateQuadletWithoutGPU(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "fedora",
		ImageRef:    "ghcr.io/overthinkos/fedora:latest",
		Home:        "/home/user",
		GPU:         false,
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if strings.Contains(got, "AddDevice") {
		t.Errorf("expected no AddDevice when GPU=false, got:\n%s", got)
	}
}

func TestGenerateQuadletWithLANBindAddress(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "fedora-test",
		ImageRef:    "ghcr.io/overthinkos/fedora-test:latest",
		Home:        "/home/user",
		Ports:       []string{"8000:8000", "8080"},
		BindAddress: "0.0.0.0",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "PublishPort=0.0.0.0:8000:8000") {
		t.Errorf("expected PublishPort with 0.0.0.0 bind address, got:\n%s", got)
	}
	if !strings.Contains(got, "PublishPort=0.0.0.0:8080:8080") {
		t.Errorf("expected single port expanded with 0.0.0.0, got:\n%s", got)
	}
}

func TestServiceName(t *testing.T) {
	tests := []struct {
		image string
		want  string
	}{
		{"fedora", "charly-fedora.service"},
		{"fedora-test", "charly-fedora-test.service"},
		{"ubuntu", "charly-ubuntu.service"},
	}
	for _, tt := range tests {
		t.Run(tt.image, func(t *testing.T) {
			got := serviceName(tt.image)
			if got != tt.want {
				t.Errorf("serviceName(%q) = %q, want %q", tt.image, got, tt.want)
			}
		})
	}
}

func TestQuadletFilename(t *testing.T) {
	tests := []struct {
		image string
		want  string
	}{
		{"fedora", "charly-fedora.container"},
		{"fedora-test", "charly-fedora-test.container"},
	}
	for _, tt := range tests {
		t.Run(tt.image, func(t *testing.T) {
			got := quadletFilename(tt.image)
			if got != tt.want {
				t.Errorf("quadletFilename(%q) = %q, want %q", tt.image, got, tt.want)
			}
		})
	}
}

func TestQuadletDir(t *testing.T) {
	got, err := quadletDir()
	if err != nil {
		t.Fatalf("quadletDir() error: %v", err)
	}

	home, _ := os.UserHomeDir()
	want := filepath.Join(home, ".config", "containers", "systemd")
	if got != want {
		t.Errorf("quadletDir() = %q, want %q", got, want)
	}
}

func TestSystemdUserDir(t *testing.T) {
	got, err := systemdUserDir()
	if err != nil {
		t.Fatalf("systemdUserDir() error: %v", err)
	}

	home, _ := os.UserHomeDir()
	want := filepath.Join(home, ".config", "systemd", "user")
	if got != want {
		t.Errorf("systemdUserDir() = %q, want %q", got, want)
	}
}

func TestQuadletExists(t *testing.T) {
	tmpDir := t.TempDir()
	// Write a fake .container file
	systemdDir := filepath.Join(tmpDir, ".config", "containers", "systemd")
	if err := os.MkdirAll(systemdDir, 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(systemdDir, "charly-testimg.container"), []byte("test"), 0644); err != nil {
		t.Fatal(err)
	}

	// Override HOME so quadletDir resolves to our temp dir
	origHome := os.Getenv("HOME")
	_ = os.Setenv("HOME", tmpDir)
	defer os.Setenv("HOME", origHome) //nolint:errcheck

	exists, err := quadletExists("testimg")
	if err != nil {
		t.Fatalf("quadletExists() error: %v", err)
	}
	if !exists {
		t.Error("expected quadletExists to return true for existing file")
	}

	exists, err = quadletExists("nonexistent")
	if err != nil {
		t.Fatalf("quadletExists() error: %v", err)
	}
	if exists {
		t.Error("expected quadletExists to return false for nonexistent file")
	}
}

func TestGenerateQuadletWithTailscalePublic(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Home:        "/home/user",
		Ports:       []string{"443:8080"},
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Ports: []TunnelPort{
				{Port: 443, Protocol: "http", Public: true},
			},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale funnel --bg --https=443 http://127.0.0.1:443") {
		t.Errorf("expected ExecStartPost for public port, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale funnel --https=443 off") {
		t.Errorf("expected ExecStopPost for public port, got:\n%s", got)
	}
}

func TestGenerateQuadletWithTailscalePublicCustomPort(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Ports: []TunnelPort{
				{Port: 8443, Protocol: "http", Public: true},
			},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale funnel --bg --https=8443 http://127.0.0.1:8443") {
		t.Errorf("expected ExecStartPost with port 8443, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale funnel --https=8443 off") {
		t.Errorf("expected ExecStopPost with port 8443, got:\n%s", got)
	}
}

func TestGenerateQuadletWithTailscalePrivate(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "immich-ml",
		ImageRef:    "ghcr.io/overthinkos/immich-ml:latest",
		Home:        "/home/user",
		Ports:       []string{"2283:2283"},
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Ports: []TunnelPort{
				{Port: 2283, BackendPort: 2283, Protocol: "http", Public: false},
			},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale serve --bg --https=2283 http://127.0.0.1:2283") {
		t.Errorf("expected ExecStartPost for private port 2283, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale serve --https=2283 off") {
		t.Errorf("expected ExecStopPost for port 2283, got:\n%s", got)
	}
	if strings.Contains(got, "tailscale funnel") {
		t.Errorf("private mode should not contain 'tailscale funnel', got:\n%s", got)
	}
}

func TestGenerateQuadletWithTailscaleExplicitRemap(t *testing.T) {
	// Explicit BackendPort: listen on 443, proxy to 2283.
	cfg := QuadletConfig{
		BoxName:     "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Ports: []TunnelPort{
				{Port: 443, BackendPort: 2283, Protocol: "http", Public: false},
			},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale serve --bg --https=443 http://127.0.0.1:2283") {
		t.Errorf("expected remapped ExecStartPost (--https=443, backend 2283), got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale serve --https=443 off") {
		t.Errorf("expected ExecStopPost with listen port 443, got:\n%s", got)
	}
}

// TestGenerateQuadletPublishPortPreservesIPPrefix is the integration regression
// for the 2026-04-29 cutover: when deploy.yml carried ports as
// "127.0.0.1:8888:8888" (an explicit bind prefix that charly config also adds for
// tunneled ports), the legacy localizePort double-prepended and produced
// PublishPort=127.0.0.1:127.0.0.1:8888:8888 — a malformed mapping podman
// rejects at start time. The fix routes localizePort through the canonical
// ParsePortMapping; either input form (bare or IP-prefixed) is now normalized
// to a single-prefixed line.
func TestGenerateQuadletPublishPortPreservesIPPrefix(t *testing.T) {
	tests := []struct {
		name        string
		ports       []string
		bindAddress string
		want        string
		notWant     string
	}{
		{
			name:        "bare 8888:8888 gets bind prepended (existing behavior)",
			ports:       []string{"8888:8888"},
			bindAddress: "127.0.0.1",
			want:        "PublishPort=127.0.0.1:8888:8888\n",
			notWant:     "PublishPort=127.0.0.1:127.0.0.1:8888:8888",
		},
		{
			name:        "IP-prefixed 127.0.0.1:8888:8888 is preserved verbatim (regression)",
			ports:       []string{"127.0.0.1:8888:8888"},
			bindAddress: "127.0.0.1",
			want:        "PublishPort=127.0.0.1:8888:8888\n",
			notWant:     "PublishPort=127.0.0.1:127.0.0.1:8888:8888",
		},
		{
			name:        "IPv6 bracket form is preserved verbatim",
			ports:       []string{"[::1]:8080:80"},
			bindAddress: "127.0.0.1",
			want:        "PublishPort=[::1]:8080:80\n",
			notWant:     "PublishPort=127.0.0.1:[::1]",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := QuadletConfig{
				BoxName:     "myapp",
				ImageRef:    "ghcr.io/test/myapp:latest",
				Home:        "/home/user",
				Ports:       tt.ports,
				BindAddress: tt.bindAddress,
			}
			got := generateQuadlet(cfg)
			if !strings.Contains(got, tt.want) {
				t.Errorf("expected %q in quadlet, got:\n%s", tt.want, got)
			}
			if strings.Contains(got, tt.notWant) {
				t.Errorf("unexpected double-prefix %q in quadlet, got:\n%s", tt.notWant, got)
			}
		})
	}
}

func TestGenerateQuadletWithHTTPSInsecureBackend(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "selkies-app",
		ImageRef:    "ghcr.io/test/selkies:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Ports: []TunnelPort{
				{Port: 3000, Protocol: "https+insecure"},
				{Port: 8888, Protocol: "http"},
			},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale serve --bg --https=3000 https+insecure://127.0.0.1:3000") {
		t.Errorf("expected https+insecure serve command for port 3000, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStartPost=tailscale serve --bg --https=8888 http://127.0.0.1:8888") {
		t.Errorf("expected http serve command for port 8888, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale serve --https=3000 off") {
		t.Errorf("expected ExecStopPost for port 3000, got:\n%s", got)
	}
}

func TestGenerateQuadletWithTLSTerminatedTCP(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "ssh-server",
		ImageRef:    "ghcr.io/test/ssh:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider: "tailscale",
			Ports: []TunnelPort{
				{Port: 22, Protocol: "tls-terminated-tcp"},
			},
		},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ExecStartPost=tailscale serve --bg --tls-terminated-tcp=22 tcp://127.0.0.1:22") {
		t.Errorf("expected tls-terminated-tcp serve command, got:\n%s", got)
	}
	if !strings.Contains(got, "ExecStopPost=-tailscale serve --tls-terminated-tcp=22 off") {
		t.Errorf("expected tls-terminated-tcp stop command, got:\n%s", got)
	}
}

func TestGenerateQuadletWithCloudflareTunnelNoExecPost(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "myapp",
		ImageRef:    "ghcr.io/test/myapp:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
		Tunnel: &TunnelConfig{
			Provider:   "cloudflare",
			TunnelName: "charly-myapp",
			Hostname:   "app.example.com",
			Ports: []TunnelPort{
				{Port: 3001, Protocol: "http", Public: true},
			},
		},
	}

	got := generateQuadlet(cfg)

	// Cloudflare uses a companion service, not ExecStartPost
	if strings.Contains(got, "ExecStartPost") {
		t.Errorf("cloudflare tunnel should not have ExecStartPost in container file, got:\n%s", got)
	}
}

func TestGenerateTunnelUnit(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:  "immich",
		ImageRef: "ghcr.io/test/immich:latest",
		Home:     "/home/user",
		Tunnel: &TunnelConfig{
			Provider:   "cloudflare",
			TunnelName: "charly-immich",
			Hostname:   "im.example.com",
			Ports: []TunnelPort{
				{Port: 3001, Protocol: "http", Public: true},
			},
		},
	}

	got := generateTunnelUnit(cfg)

	if !strings.Contains(got, "charly-immich-tunnel.service") {
		t.Errorf("expected filename in comment, got:\n%s", got)
	}
	if !strings.Contains(got, "BindsTo=charly-immich.service") {
		t.Errorf("expected BindsTo, got:\n%s", got)
	}
	if !strings.Contains(got, "After=charly-immich.service") {
		t.Errorf("expected After, got:\n%s", got)
	}
	if !strings.Contains(got, "cloudflared tunnel --config") {
		t.Errorf("expected cloudflared ExecStart, got:\n%s", got)
	}
	if !strings.Contains(got, "run charly-immich") {
		t.Errorf("expected tunnel name in ExecStart, got:\n%s", got)
	}
	if !strings.Contains(got, "WantedBy=default.target") {
		t.Errorf("expected WantedBy, got:\n%s", got)
	}
}

func TestGenerateTunnelUnitNilTunnel(t *testing.T) {
	cfg := QuadletConfig{
		BoxName: "myapp",
		Tunnel:  nil,
	}

	got := generateTunnelUnit(cfg)
	if got != "" {
		t.Errorf("expected empty string for nil tunnel, got: %s", got)
	}
}

func TestTunnelServiceFilename(t *testing.T) {
	tests := []struct {
		image string
		want  string
	}{
		{"myapp", "charly-myapp-tunnel.service"},
		{"immich", "charly-immich-tunnel.service"},
	}
	for _, tt := range tests {
		t.Run(tt.image, func(t *testing.T) {
			got := tunnelServiceFilename(tt.image)
			if got != tt.want {
				t.Errorf("tunnelServiceFilename(%q) = %q, want %q", tt.image, got, tt.want)
			}
		})
	}
}

func TestGenerateQuadletWithNetwork(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "githubrunner",
		ImageRef:    "ghcr.io/overthinkos/githubrunner:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
		Network:     "host",
		Security:    SecurityConfig{Privileged: true},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "Network=host\n") {
		t.Errorf("expected Network=host, got:\n%s", got)
	}
	if !strings.Contains(got, "PodmanArgs=--privileged") {
		t.Errorf("expected PodmanArgs=--privileged, got:\n%s", got)
	}
}

func TestGenerateQuadletWithoutNetwork(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "fedora",
		ImageRef:    "ghcr.io/overthinkos/fedora:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
	}

	got := generateQuadlet(cfg)

	if strings.Contains(got, "Network=") {
		t.Errorf("expected no Network= when network is empty, got:\n%s", got)
	}
}

func TestGenerateQuadletWithEnvVars(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "githubrunner",
		ImageRef:    "ghcr.io/overthinkos/githubrunner:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
		Env:         []string{"RUNNER_TOKEN=abc123", "RUNNER_NAME=r1"},
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "Environment=RUNNER_TOKEN=abc123") {
		t.Errorf("expected Environment=RUNNER_TOKEN=abc123, got:\n%s", got)
	}
	if !strings.Contains(got, "Environment=RUNNER_NAME=r1") {
		t.Errorf("expected Environment=RUNNER_NAME=r1, got:\n%s", got)
	}
}

func TestGenerateQuadletWithEnvFile(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "githubrunner",
		ImageRef:    "ghcr.io/overthinkos/githubrunner:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
		EnvFile:     "/home/user/.config/charly/githubrunner.env",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "EnvironmentFile=/home/user/.config/charly/githubrunner.env") {
		t.Errorf("expected EnvironmentFile line, got:\n%s", got)
	}
}

func TestGenerateQuadletWithInstance(t *testing.T) {
	cfg := QuadletConfig{
		BoxName:     "githubrunner",
		ImageRef:    "ghcr.io/overthinkos/githubrunner:latest",
		Home:        "/home/user",
		BindAddress: "127.0.0.1",
		Instance:    "runner-1",
	}

	got := generateQuadlet(cfg)

	if !strings.Contains(got, "ContainerName=charly-githubrunner-runner-1") {
		t.Errorf("expected instance container name, got:\n%s", got)
	}
	if !strings.Contains(got, "Description=OpenCharly githubrunner (runner-1)") {
		t.Errorf("expected instance description, got:\n%s", got)
	}
	if !strings.Contains(got, "# charly-githubrunner-runner-1.container") {
		t.Errorf("expected instance filename in comment, got:\n%s", got)
	}
}

func TestServiceNameInstance(t *testing.T) {
	tests := []struct {
		image    string
		instance string
		want     string
	}{
		{"fedora", "", "charly-fedora.service"},
		{"githubrunner", "runner-1", "charly-githubrunner-runner-1.service"},
	}
	for _, tt := range tests {
		got := serviceNameInstance(tt.image, tt.instance)
		if got != tt.want {
			t.Errorf("serviceNameInstance(%q, %q) = %q, want %q", tt.image, tt.instance, got, tt.want)
		}
	}
}

func TestQuadletFilenameInstance(t *testing.T) {
	tests := []struct {
		image    string
		instance string
		want     string
	}{
		{"fedora", "", "charly-fedora.container"},
		{"githubrunner", "runner-2", "charly-githubrunner-runner-2.container"},
	}
	for _, tt := range tests {
		got := quadletFilenameInstance(tt.image, tt.instance)
		if got != tt.want {
			t.Errorf("quadletFilenameInstance(%q, %q) = %q, want %q", tt.image, tt.instance, got, tt.want)
		}
	}
}
