package main

// reserved_registry.go — the reserved-word ⇄ Go-handler registry + the startup
// BIJECTION gate. (The plain name `registry.go` is taken by the OCI remote-image
// module, so this file carries the reserved-word registry.) The reserved
// vocabulary is CUE-derived (charly/spec, regenerated by `task cue:gen` from
// charly/schema/*.cue); this file is the SINGLE place that proves every
// CUE-declared reserved word has exactly one Go handler and vice versa — so a
// kind/verb can never be added to the schema without a handler, nor a handler
// kept after its word is dropped. The init() panics (fail-fast at process start,
// mirroring registerCueKind / mustCalVer); the same checks run as
// TestReservedWordRegistry_* (which also proves the gate FAILS when a handler is
// missing).
//
// It also hosts the CUE-derived membership SETS that replaced the former eight
// hand vocab lists (kindKeys/kindKeysSet/rootShapeKeys/docDirectiveKeys in
// unified.go + nodeEntityKinds/nodeResourceKinds/nodeStepVerbs/nodeDataKeys/
// nodeDocDirectives in node_parse.go). Every loader consumer now reads these.

import (
	"fmt"
	"sort"

	"github.com/overthinkos/overthink/charly/spec"
)

// setFromSlice builds an O(1) membership set from a CUE-derived vocabulary slice.
func setFromSlice(words []string) map[string]bool {
	m := make(map[string]bool, len(words))
	for _, w := range words {
		m[w] = true
	}
	return m
}

// CUE-derived membership sets — the SINGLE source for the loader's reserved-word
// classification. Each is a set view of a spec.* slice generated by `task cue:gen`
// from charly/schema/*.cue. NEVER hand-edit a parallel copy; change the schema and
// regenerate.
var (
	// kindWordSet — the authoring KIND vocabulary (#Node arms). Replaces the hand
	// kindKeys/kindKeysSet (unified.go) + nodeEntityKinds (node_parse.go).
	kindWordSet = setFromSlice(spec.KindWords)
	// resourceKindSet — the DEPLOYABLE subset that nests sub-entity children
	// (#ResourceKind). Replaces the hand nodeResourceKinds + node_normalize.go's
	// inline resource-child switch.
	resourceKindSet = setFromSlice(spec.ResourceKinds)
	// stepKeywordSet — the plan-step intent keywords (#Step). Replaces the hand
	// nodeStepVerbs.
	stepKeywordSet = setFromSlice(spec.StepKeywords)
	// dataKeySet — the DATA discriminator keywords (non-scalar #Candy/#Deploy
	// fields folded as child nodes). Replaces the hand nodeDataKeys.
	dataKeySet = setFromSlice(spec.DataKeys)
	// docDirectiveSet — the reserved DOCUMENT directives (#NodeDoc). Replaces the
	// hand docDirectiveKeys (unified.go) + nodeDocDirectives (node_parse.go).
	docDirectiveSet = setFromSlice(spec.DocDirectives)
)

// legacyKindAliases are the reserved top-level keys that mark a LEGACY
// (pre-node-form) document but are NOT current CUE node kinds: `deploy` is the
// pre-rename spelling of the `bundle` kind, `check` is the legacy bed-collection
// map key. The legacy kind-keyed ROUTING was deleted in the #NodeDoc-sole-gate
// cutover; these aliases survive ONLY as part of classifyDoc's legacy-detection
// set, so a residual `deploy:` / `check:` collection doc is hard-rejected with a
// `charly migrate` hint (rather than mis-read as a node named after a non-kind
// word).
var legacyKindAliases = []string{"deploy", "check"}

// rootShapeKeySet — the top-level keys whose presence (with a non-node-shaped
// value) marks a doc as a legacy kind-keyed / root-shape document, which
// classifyDoc hard-rejects with a `charly migrate` hint. Derived from the CUE
// vocabulary (doc directives + every core kind word + every DEPLOYABLE resource
// kind) PLUS the legacy collection-map aliases. ResourceKinds is unioned in so a
// legacy `pod:`/`vm:`/`k8s:`/`local:`/`android:`/`group:` collection map is still
// detected after those kinds left KindWords (C2-group / C2-substrate externalized
// them — they carry no #Node arm but stay legacy-detectable resource kinds). It is
// the legacy-DETECTOR only — no routing reads it.
var rootShapeKeySet = func() map[string]bool {
	m := setFromSlice(spec.DocDirectives)
	for k := range kindWordSet {
		m[k] = true
	}
	for _, k := range spec.ResourceKinds {
		m[k] = true
	}
	for _, legacy := range legacyKindAliases {
		m[legacy] = true
	}
	return m
}()

// ---------------------------------------------------------------------------
// Reserved-word ⇄ handler registry + the bijection gate.
// ---------------------------------------------------------------------------

// The kind decode dispatch + the kind⇄def bijection now live on the KindProviders
// (each in its own dedicated provider file) — folded onto the providers in C2 (R3),
// replacing the former hand-maintained handler map + its bijection gate.
// checkKindProviderBijection runs in registry_bootstrap.go's init() (the ONE built-in
// registration site), after all provider registration.

// checkVerbBijection verifies the package-main VerbCatalog dispatch table and the
// CUE verb vocabulary (spec.OpVerbs) are in exact bijection, and that every verb is
// also a member of the broader authorable Op vocabulary (spec.AuthoringVerbs).
func checkVerbBijection(catalog map[string]VerbSpec, verbs, authoring []string) error {
	want := setFromSlice(verbs)
	auth := setFromSlice(authoring)
	var missing, extra, notAuthorable []string
	for v := range want {
		if _, ok := catalog[v]; !ok {
			missing = append(missing, v)
		}
		if !auth[v] {
			notAuthorable = append(notAuthorable, v)
		}
	}
	for v := range catalog {
		if !want[v] {
			extra = append(extra, v)
		}
	}
	sort.Strings(missing)
	sort.Strings(extra)
	sort.Strings(notAuthorable)
	if len(missing) > 0 || len(extra) > 0 || len(notAuthorable) > 0 {
		return fmt.Errorf("reserved-word registry: verb bijection broken — verbs in spec.OpVerbs with no VerbCatalog handler: %v; VerbCatalog keys not in spec.OpVerbs: %v; verbs not in spec.AuthoringVerbs: %v", missing, extra, notAuthorable)
	}
	return nil
}

// init is the startup verb-bijection gate. It panics unless every reserved word in
// the CUE vocabulary has exactly one Go handler and vice versa — a fail-fast that
// makes a schema/handler divergence impossible to ship.
func init() {
	if err := checkVerbBijection(VerbCatalog, spec.OpVerbs, spec.AuthoringVerbs); err != nil {
		panic(err)
	}
}
