// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The BUILT-IN `builder` plugin's OWN CUE schema — the typed input for the `builder`
// KIND (the multi-stage builder vocabulary: pixi/npm/cargo/aur/bootstrap, formerly a
// core `builder:` kind decoded into the typed core map uf.Builder). SINGLE SOURCE for
// this plugin's params, used two ways (the same contract the package-group/agent/
// module/sidecar/distro plugins and core `spec` use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (task cue:gen) →
//     ../params/cue_types_gen.go.
//  2. VALIDATE authored input AT RUNTIME — served over Describe (InProcTransport),
//     spliced base ++ plugin, every authored `builder:` body validated against
//     #BuilderInput BEFORE runPluginKind dispatches.
//
// SELF-CONTAINED: references NO base def — every shared shape (#CacheMount / #PhaseSet /
// #PhaseTemplates / #StrMap from _common.cue) is reproduced standalone here (prefix
// #Bd). Faithful reproduction of the core #Builder (schema/builder.cue) — same authored
// WIRE keys — so the host validates a real builder entity and the plugin's Invoke
// canonicalises the body back through the core spec.Builder type (which BuilderDef
// aliases and the generator consumes via the Builders() accessor). @go() annotations
// are dropped (CORE codegen only; the validator ignores attributes). NAME: the entity
// name is the node KEY, never a body field — #Builder has no name field.
type BuilderInput struct {
	Detect_file []string `yaml:"detect_file,omitempty" json:"detect_file,omitempty"`

	Detect_config string `yaml:"detect_config,omitempty" json:"detect_config,omitempty"`

	Requires_src_dir bool `yaml:"requires_src_dir,omitempty" json:"requires_src_dir,omitempty"`

	Inline bool `yaml:"inline,omitempty" json:"inline,omitempty"`

	Cache_mount []BdCacheMount `yaml:"cache_mount,omitempty" json:"cache_mount,omitempty"`

	Env BdStrMap `yaml:"env,omitempty" json:"env,omitempty"`

	Runtime_env BdStrMap `yaml:"runtime_env,omitempty" json:"runtime_env,omitempty"`

	Stage_template string `yaml:"stage_template,omitempty" json:"stage_template,omitempty"`

	Install_template string `yaml:"install_template,omitempty" json:"install_template,omitempty"`

	Manylinux_fix string `yaml:"manylinux_fix,omitempty" json:"manylinux_fix,omitempty"`

	Build_script string `yaml:"build_script,omitempty" json:"build_script,omitempty"`

	Phase BdPhaseSet `yaml:"phase,omitempty" json:"phase,omitempty"`

	Install_command map[string]string `yaml:"install_command,omitempty" json:"install_command,omitempty"`

	Copy_artifact []BdCopy `yaml:"copy_artifact,omitempty" json:"copy_artifact,omitempty"`

	Copy_binary BdCopy `yaml:"copy_binary,omitempty" json:"copy_binary,omitempty"`

	Path_contribution []string `yaml:"path_contribution,omitempty" json:"path_contribution,omitempty"`

	Kind string `yaml:"kind,omitempty" json:"kind"`

	Privileged bool `yaml:"privileged,omitempty" json:"privileged"`

	Output_artifact string `yaml:"output_artifact,omitempty" json:"output_artifact,omitempty"`
}

// reproduces #CacheMount (schema/_common.cue) standalone.
type BdCacheMount struct {
	Dst string `yaml:"dst,omitempty" json:"dst"`

	Sharing string `yaml:"sharing,omitempty" json:"sharing,omitempty"`

	Owned bool `yaml:"owned,omitempty" json:"owned,omitempty"`
}

// reproduces #StrMap (schema/_common.cue) standalone — values are string-coercible
// (a quoted string / number / bool; yaml.v3 coerces an unquoted int/bool to its
// literal text).
type BdStrMap map[string]any /* CUE disjunction: (bool|string|number) */

// reproduces #PhaseSet / #PhaseTemplates (schema/_common.cue) standalone.
type BdPhaseSet struct {
	Prepare BdPhaseTemplates `yaml:"prepare,omitempty" json:"prepare,omitempty"`

	Install BdPhaseTemplates `yaml:"install,omitempty" json:"install,omitempty"`

	Cleanup BdPhaseTemplates `yaml:"cleanup,omitempty" json:"cleanup,omitempty"`
}

type BdPhaseTemplates struct {
	Container string `yaml:"container,omitempty" json:"container,omitempty"`

	Host string `yaml:"host,omitempty" json:"host,omitempty"`
}

type BdCopy struct {
	Src string `yaml:"src,omitempty" json:"src"`

	Dst string `yaml:"dst,omitempty" json:"dst"`

	Chown bool `yaml:"chown,omitempty" json:"chown,omitempty"`
}
