// Command pluginsgen emits the compiled-in plugin wiring from a charly.yml's
// `compiled_plugins:` list: charly/plugins_generated.go (one registerCompiledPlugin
// call per plugin candy) AND the repo-root go.work (a `use` directive per candy, so
// `go build ./charly` resolves the candy imports in plugins_generated.go).
//
// It is the in-proc-placement counterpart of the out-of-process plugin loader:
// `compiled_plugins:` selects which plugin candies are COMPILED INTO this charly
// binary; everything else still loads out-of-process over gRPC when referenced (the
// coexist path). "which plugins are in the binary" is therefore a normal
// candy-inclusion choice, expressed in charly.yml.
//
// It imports only the stdlib + gopkg.in/yaml.v3 and NEVER imports the candy modules
// (it string-templates their import paths from each candy's go.mod), so it builds and
// runs without a pre-built charly and without the candy modules resolving — which is
// what lets `task build:charly` run it BEFORE the `go build` that needs go.work
// (dodging the chicken-and-egg). Run it with GOWORK=off so a stale go.work can't fail
// workspace load before regeneration.
//
// Reproducible: same `compiled_plugins:` list -> byte-identical outputs (guarded by
// TestPluginsGenReproducible). Run from `task build:charly`; edit charly.yml's
// compiled_plugins and re-run, never the generated files.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	cfg := flag.String("config", "charly/charly.yml", "charly.yml whose compiled_plugins: drives generation (relative to -root)")
	root := flag.String("root", ".", "repo root (contains charly/ and candy/); go.work use-paths are relative to it")
	outGo := flag.String("out", "charly/plugins_generated.go", "generated registration file (relative to -root)")
	outWork := flag.String("gowork", "go.work", "generated go.work (relative to -root)")
	flag.Parse()

	if err := run(*root, *cfg, *outGo, *outWork); err != nil {
		fmt.Fprintf(os.Stderr, "pluginsgen: %v\n", err)
		os.Exit(1)
	}
}

func run(root, cfg, outGo, outWork string) error {
	genGo, genWork, err := generate(root, cfg)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, outGo), genGo, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outGo, err)
	}
	if err := os.WriteFile(filepath.Join(root, outWork), genWork, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outWork, err)
	}
	return nil
}

// generate produces the byte content of plugins_generated.go + go.work from a
// charly.yml's compiled_plugins: list, WITHOUT writing — so the reproducibility gate
// (TestPluginsGenReproducible) can diff against the committed files.
func generate(root, cfg string) (genGo, genWork []byte, err error) {
	names, err := readCompiledPlugins(filepath.Join(root, cfg))
	if err != nil {
		return nil, nil, err
	}
	type entry struct {
		name   string // candy dir name under candy/
		module string // go.mod module path (== the importable root package)
		alias  string // import alias in the generated file
		shape  string // "kit" (NewCheckVerb, schema) or "pb" (NewProvider/NewMeta)
	}
	entries := make([]entry, 0, len(names))
	for _, name := range names {
		candyDir := filepath.Join(root, "candy", name)
		mod, err := readModulePath(filepath.Join(candyDir, "go.mod"))
		if err != nil {
			return nil, nil, fmt.Errorf("compiled plugin %q: %w", name, err)
		}
		if err := requirePluginBlock(filepath.Join(candyDir, "charly.yml")); err != nil {
			return nil, nil, fmt.Errorf("compiled plugin %q: %w", name, err)
		}
		shape, err := detectShape(candyDir)
		if err != nil {
			return nil, nil, fmt.Errorf("compiled plugin %q: %w", name, err)
		}
		entries = append(entries, entry{name: name, module: mod, alias: goAlias(name), shape: shape})
	}

	// --- plugins_generated.go ---
	var g bytes.Buffer
	g.WriteString("// Code generated by pluginsgen (charly box generate-plugins). DO NOT EDIT.\n//\n")
	g.WriteString("// One registerCompiledPlugin() call per plugin candy named in charly.yml\n")
	g.WriteString("// `compiled_plugins:`. Regenerated by `task build:charly` before `go build`; the\n")
	g.WriteString("// matching `use` directives land in the repo-root go.work. Edit charly.yml's\n")
	g.WriteString("// compiled_plugins and re-run the generator, never this file.\n")
	g.WriteString("package main\n\n")
	if len(entries) > 0 {
		g.WriteString("import (\n")
		for _, e := range entries {
			fmt.Fprintf(&g, "\t%s %q\n", e.alias, e.module)
		}
		g.WriteString(")\n\n")
		g.WriteString("func init() {\n")
		for _, e := range entries {
			switch e.shape {
			case "kit":
				// kit-shape: host-coupled check verb, compiled-in-only — register through
				// the kit adapter (charly concatenates the candy's raw schema FS).
				fmt.Fprintf(&g, "\tregisterCompiledCheckVerb(%s.NewCheckVerb(), %s.SchemaFS, %s.InputDefs)\n",
					e.alias, e.alias, e.alias)
			default:
				// pb-shape: dual-placement plugin — in-proc via the served Describe channel.
				fmt.Fprintf(&g, "\tregisterCompiledPlugin(%s.NewProvider(), %s.NewMeta())\n", e.alias, e.alias)
			}
		}
		g.WriteString("}\n")
	}
	formatted, err := format.Source(g.Bytes())
	if err != nil {
		return nil, nil, fmt.Errorf("format generated go: %w\n%s", err, g.String())
	}

	// --- go.work ---
	goVer, err := readGoDirective(filepath.Join(root, "charly", "go.mod"))
	if err != nil {
		return nil, nil, err
	}
	var w bytes.Buffer
	fmt.Fprintf(&w, "go %s\n\n", goVer)
	w.WriteString("// Generated by pluginsgen (charly box generate-plugins). DO NOT EDIT.\n")
	w.WriteString("// The charly module plus every plugin candy selected into the binary via\n")
	w.WriteString("// charly.yml `compiled_plugins:`. `go build ./charly` resolves the compiled-in\n")
	w.WriteString("// candy imports in charly/plugins_generated.go through these `use` directives.\n")
	w.WriteString("use ./charly\n")
	for _, e := range entries {
		fmt.Fprintf(&w, "use ./candy/%s\n", e.name)
	}
	return formatted, w.Bytes(), nil
}

// readCompiledPlugins reads ONLY the compiled_plugins: list from a charly.yml,
// tolerating every other key (it decodes into a one-field struct).
func readCompiledPlugins(path string) ([]string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var doc struct {
		CompiledPlugins []string `yaml:"compiled_plugins"`
	}
	if err := yaml.Unmarshal(b, &doc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return doc.CompiledPlugins, nil
}

// readModulePath returns the `module` path declared in a go.mod.
func readModulePath(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("open go.mod: %w (a compiled plugin must be its own Go module)", err)
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if rest, ok := strings.CutPrefix(line, "module "); ok {
			return strings.TrimSpace(rest), nil
		}
	}
	if err := sc.Err(); err != nil {
		return "", err
	}
	return "", fmt.Errorf("no module directive in go.mod")
}

// readGoDirective returns the `go` version directive from a go.mod (for go.work's go line).
func readGoDirective(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if rest, ok := strings.CutPrefix(line, "go "); ok {
			return strings.TrimSpace(rest), nil
		}
	}
	if err := sc.Err(); err != nil {
		return "", err
	}
	return "", fmt.Errorf("no go directive in %s", path)
}

// requirePluginBlock asserts a candy's charly.yml declares a plugin: block — guarding
// against listing a non-plugin candy in compiled_plugins (which would compile in a
// package with no NewProvider/NewMeta). A coarse textual check is sufficient here;
// `charly box validate` does the authoritative plugin-candy validation.
func requirePluginBlock(path string) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read candy charly.yml: %w", err)
	}
	if !bytes.Contains(b, []byte("plugin:")) {
		return fmt.Errorf("candy has no plugin: block — only plugin candies may be compiled in")
	}
	return nil
}

// detectShape reports a candy's plugin shape from a textual scan of its Go at codegen
// time (never runtime; avoids importing the candy module, keeping pluginsgen stdlib+yaml
// only): "kit" if it exports `func NewCheckVerb(` (a host-coupled check verb WITH a
// schema, compiled-in-only), else "pb" (a dual-placement NewProvider/NewMeta plugin).
func detectShape(candyDir string) (string, error) {
	shape := "pb"
	err := filepath.WalkDir(candyDir, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}
		b, rerr := os.ReadFile(path)
		if rerr != nil {
			return rerr
		}
		if bytes.Contains(b, []byte("func NewCheckVerb(")) {
			shape = "kit"
		}
		return nil
	})
	return shape, err
}

// goAlias turns a candy dir name into a stable, valid Go import alias (cp_<sanitized>).
func goAlias(name string) string {
	var b strings.Builder
	b.WriteString("cp_")
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}
