// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The BUILT-IN `resource` plugin's OWN CUE schema — the typed input for the `resource`
// KIND (exclusive host-resource tokens for GPU arbitration, formerly a core `resource:`
// kind decoded into the typed core map uf.Resource). SINGLE SOURCE for this plugin's
// params, used two ways (the same contract the package-group/agent/module/sidecar/
// distro/builder/init plugins and core `spec` use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (task cue:gen) →
//     ../params/cue_types_gen.go.
//  2. VALIDATE authored input AT RUNTIME — served over Describe (InProcTransport),
//     spliced base ++ plugin, every authored `resource:` body validated against
//     #ResourceInput BEFORE runPluginKind dispatches.
//
// SELF-CONTAINED: the core #Resource (schema/resource.cue) references NO _common.cue
// def, so this is a verbatim reproduction with the inner #GpuSelector renamed
// #RsGpuSelector (prefix #Rs) and the @go() annotation dropped (CORE codegen only). The
// plugin's Invoke canonicalises the body back through the core spec.Resource type (which
// ResourceDef aliases and the GPU-arbitration code consumes via the Resources()
// accessor). Both shapes valid: `{}` (bare arbitration token) and `{gpu: {vendor: …}}`
// (selector token). NAME: the entity name is the node KEY, never a body field.
type ResourceInput struct {
	Gpu RsGpuSelector `yaml:"gpu,omitempty" json:"gpu,omitempty"`
}

// vendor required + non-empty; NOT regex-pinned (normalizePCIVendor accepts
// "10DE"/"0X10de"/"0x10de" — a strict regex would reject Go-valid input).
type RsGpuSelector struct {
	Vendor string `yaml:"vendor,omitempty" json:"vendor"`
}
