// Command plugin-example-command is the reference OUT-OF-TREE charly COMMAND-class
// plugin: a standalone binary (its own Go module) that serves the `examplecommand`
// command over go-plugin gRPC via the charly plugin SDK. It is the COMMAND-class
// companion of the verb-class candy/plugin-example-external.
//
// CLI dispatch contract (charly/provider_command_external.go dispatchExternalCommand):
// charly forwards the user's pass-through CLI tokens from `charly examplecommand
// <args…>` by Invoking this provider with op.Op == OpRun and
// op.Params == {"args": [...]} (the tokens, marshalled directly — NOT wrapped in the
// `plugin_input` envelope a verb CHECK step uses). This provider decodes that args
// list, then does ONE observable, deterministic thing: it writes a marker FILE (path =
// the first arg, else a fixed /tmp/charly-examplecommand/ran) whose body is the joined
// args — so a test can assert the command ran AND received its args.
//
// The command class is external-capable: charly's prescan (plugin_command_prescan.go)
// registers `examplecommand` into the CLI grammar before kong.Parse, and the first
// `charly examplecommand` invocation lazy-connects + Invokes this provider out-of-process.
// (builtinCommandBase.Invoke's "in-process only" stub is only the BUILTIN-command path; an
// external command runs here, over gRPC.) The full end-to-end (`charly examplecommand
// <args>` → marker file) is exercised by the Go e2e + the live R10, not by this candy's
// build-context ADE check (see charly.yml).
package main

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"path"
	"strings"

	"github.com/overthinkos/overthink/candy/plugin-example-command/params"
	pb "github.com/overthinkos/overthink/charly/plugin/proto"
	"github.com/overthinkos/overthink/charly/plugin/sdk"
)

//go:embed schema/*.cue
var schemaFS embed.FS

func main() { sdk.Serve(&provider{}, &meta{}) }

// opRun mirrors charly's command-run op selector (package main's OpRun = "run"). An
// external plugin can't import that constant, so it is named here; the host's
// dispatchExternalCommand sends opRun on the command Invoke. Any other op returns a
// benign empty result.
const opRun = "run"

// defaultMarker is the marker path used when `charly examplecommand` is invoked with
// no positional args — a fixed, disposable /tmp path with zero operator side-effect.
const defaultMarker = "/tmp/charly-examplecommand/ran"

type provider struct{ pb.UnimplementedProviderServer }

// Invoke handles the command-run Op (opRun): it decodes the pass-through CLI args from
// op.Params (the {"args": [...]} the host forwards DIRECTLY — no plugin_input wrapper),
// then writes a marker FILE at the first arg (or the fixed defaultMarker) containing the
// joined args, so a test can assert both that the command ran and which args it received.
// The result echoes the joined args as the message (the same deterministic-pass shape
// candy/plugin-example-external returns for its verb).
func (provider) Invoke(_ context.Context, req *pb.InvokeRequest) (*pb.InvokeReply, error) {
	if req.GetOp() != opRun {
		return &pb.InvokeReply{ResultJson: []byte("{}")}, nil
	}
	// Decode the args list into the CUE-GENERATED typed struct (params.ExamplecommandInput,
	// generated by `cue exp gengotypes` from schema/examplecommand.cue) — never a
	// hand-parsed map. Command dispatch marshals op.Params as {"args": [...]} directly,
	// so the struct decodes the top-level payload (no plugin_input envelope).
	var in params.ExamplecommandInput
	if raw := req.GetParamsJson(); len(raw) > 0 {
		if err := json.Unmarshal(raw, &in); err != nil {
			return nil, fmt.Errorf("plugin-example-command: decode args: %w", err)
		}
	}
	target := defaultMarker
	if len(in.Args) > 0 {
		target = in.Args[0]
	}
	body := strings.Join(in.Args, " ")
	if err := os.MkdirAll(path.Dir(target), 0o755); err != nil {
		return nil, fmt.Errorf("plugin-example-command: mkdir %q: %w", path.Dir(target), err)
	}
	if err := os.WriteFile(target, []byte(body), 0o644); err != nil {
		return nil, fmt.Errorf("plugin-example-command: write marker %q: %w", target, err)
	}
	j, err := json.Marshal(map[string]string{"status": "pass", "message": body})
	if err != nil {
		return nil, err
	}
	return &pb.InvokeReply{ResultJson: j}, nil
}

type meta struct {
	pb.UnimplementedPluginMetaServer
}

// Describe ships the plugin's capability AND its self-contained CUE schema over the
// wire via sdk.BuildCapabilities — the schema travels with the plugin, identically to a
// built-in. The SDK compiles the schema STANDALONE here, failing loudly before serving
// if it is broken or empty.
func (meta) Describe(context.Context, *pb.Empty) (*pb.Capabilities, error) {
	return sdk.BuildCapabilities("2026.175.0900",
		[]sdk.ProvidedCapability{{Class: "command", Word: "examplecommand", InputDef: "#ExamplecommandInput"}},
		schemaFS, "schema")
}
