// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The BUILT-IN `distro` plugin's OWN CUE schema — the typed input for the `distro`
// KIND (the per-distro build vocabulary, formerly a core `distro:` kind decoded into
// the typed core map uf.Distro). It is the SINGLE SOURCE for this plugin's params,
// used two ways (the same contract the reference exampleprobe/process, the
// package-group/agent/module/sidecar plugins, and core `spec` use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by task cue:gen,
//     which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go.
//  2. VALIDATE authored input AT RUNTIME — the builtin serves this source over the
//     Describe channel (InProcTransport) exactly like an external serves it over
//     gRPC; the host splices it onto the base (base ++ plugin) and validates every
//     authored `distro:` entity body against #DistroInput BEFORE runPluginKind
//     dispatches (validateAuthoredPluginInput(ClassKind, "distro", …)) — the
//     kind-class analogue of the verb plugin_input gate.
//
// SELF-CONTAINED: it references NO base def — every shared shape (#CacheMount /
// #PhaseSet / #PhaseTemplates from _common.cue) is reproduced standalone here (prefix
// #Ds), so it compiles standalone (gengotypes + the load-gate compile) AND splices
// onto the base (the base ++ plugin splice exists to detect a def-name collision with
// the base, not to resolve base refs). It is a faithful reproduction of the core
// #Distro (schema/distro.cue) — the same authored WIRE keys, so the host validates a
// real distro entity (incl. the binary-embedded build vocabulary), and the plugin's
// Invoke canonicalises the body back through the core spec.Distro type (which DistroDef
// aliases and the generator/format code consumes via the Distros() accessor).
//
// NAME: in node-form the entity name is the top-level node KEY, not a body field, so
// the assembled entity body NEVER carries `name`; #Distro has no name field either, so
// there is nothing to make optional here. @go() annotations are dropped (they steer the
// CORE spec codegen only; the validator ignores attributes, the plugin Invoke decodes
// into spec.Distro, so the generated params struct's Go names are cosmetic for a builtin).
type DistroInput struct {
	Inherits string `yaml:"inherits,omitempty" json:"inherits,omitempty"`

	Inherit_packages bool `yaml:"inherit_packages,omitempty" json:"inherit_packages,omitempty"`

	Version string `yaml:"version,omitempty" json:"version,omitempty"`

	Bootstrap DsBootstrap `yaml:"bootstrap,omitempty" json:"bootstrap,omitempty"`

	Workaround []string `yaml:"workaround,omitempty" json:"workaround,omitempty"`

	Format map[string]DsFormat `yaml:"format,omitempty" json:"format,omitempty"`

	Base_user DsBaseUser `yaml:"base_user,omitempty" json:"base_user,omitempty"`

	Pacstrap DsPacstrap `yaml:"pacstrap,omitempty" json:"pacstrap,omitempty"`

	Debootstrap DsDebootstrap `yaml:"debootstrap,omitempty" json:"debootstrap,omitempty"`

	Alpine_bootstrap DsAlpineBootstrap `yaml:"alpine_bootstrap,omitempty" json:"alpine_bootstrap,omitempty"`

	Bootloader DsBootloader `yaml:"bootloader,omitempty" json:"bootloader,omitempty"`

	Dnf DsDnf `yaml:"dnf,omitempty" json:"dnf,omitempty"`
}

// install_cmd is the bootstrap command; ubuntu sets it to "" (kept WITHOUT
// `& !=""` so the empty-string base case validates).
type DsBootstrap struct {
	Install_cmd string `yaml:"install_cmd,omitempty" json:"install_cmd"`

	Package []string `yaml:"package,omitempty" json:"package,omitempty"`

	Cache_mount []DsCacheMount `yaml:"cache_mount,omitempty" json:"cache_mount,omitempty"`
}

// reproduces #CacheMount (schema/_common.cue) standalone.
type DsCacheMount struct {
	Dst string `yaml:"dst,omitempty" json:"dst"`

	Sharing string `yaml:"sharing,omitempty" json:"sharing,omitempty"`

	Owned bool `yaml:"owned,omitempty" json:"owned,omitempty"`
}

type DsFormat struct {
	Cache_mount []DsCacheMount `yaml:"cache_mount,omitempty" json:"cache_mount,omitempty"`

	Section_field map[string]string `yaml:"section_field,omitempty" json:"section_field,omitempty"`

	Install_template string `yaml:"install_template,omitempty" json:"install_template,omitempty"`

	Uninstall_template string `yaml:"uninstall_template,omitempty" json:"uninstall_template,omitempty"`

	Phase DsPhaseSet `yaml:"phase,omitempty" json:"phase,omitempty"`

	Validate []DsFormatRule `yaml:"validate,omitempty" json:"validate,omitempty"`

	Secondary bool `yaml:"secondary,omitempty" json:"secondary,omitempty"`

	Local_pkg DsLocalPkg `yaml:"local_pkg,omitempty" json:"local_pkg,omitempty"`
}

// reproduces #PhaseSet / #PhaseTemplates (schema/_common.cue) standalone.
type DsPhaseSet struct {
	Prepare DsPhaseTemplates `yaml:"prepare,omitempty" json:"prepare,omitempty"`

	Install DsPhaseTemplates `yaml:"install,omitempty" json:"install,omitempty"`

	Cleanup DsPhaseTemplates `yaml:"cleanup,omitempty" json:"cleanup,omitempty"`
}

type DsPhaseTemplates struct {
	Container string `yaml:"container,omitempty" json:"container,omitempty"`

	Host string `yaml:"host,omitempty" json:"host,omitempty"`
}

type DsFormatRule struct {
	Field string `yaml:"field,omitempty" json:"field"`

	Rule string `yaml:"rule,omitempty" json:"rule"`
}

type DsLocalPkg struct {
	Pkg_glob string `yaml:"pkg_glob,omitempty" json:"pkg_glob"`

	Source_sentinel string `yaml:"source_sentinel,omitempty" json:"source_sentinel"`

	Build_template string `yaml:"build_template,omitempty" json:"build_template"`

	Install_template string `yaml:"install_template,omitempty" json:"install_template"`

	Probe string `yaml:"probe,omitempty" json:"probe"`

	Dep_builder string `yaml:"dep_builder,omitempty" json:"dep_builder,omitempty"`

	Download_template string `yaml:"download_template,omitempty" json:"download_template,omitempty"`
}

type DsBaseUser struct {
	Name string `yaml:"name,omitempty" json:"name"`

	Uid int64 `yaml:"uid,omitempty" json:"uid"`

	Gid int64 `yaml:"gid,omitempty" json:"gid"`

	Home string `yaml:"home,omitempty" json:"home"`
}

type DsPacstrap struct {
	Base_package []string `yaml:"base_package,omitempty" json:"base_package,omitempty"`

	Keyring_init_cmd string `yaml:"keyring_init_cmd,omitempty" json:"keyring_init_cmd,omitempty"`

	Mirrorlist_url string `yaml:"mirrorlist_url,omitempty" json:"mirrorlist_url,omitempty"`

	Extra_repo []DsPacstrapRepo `yaml:"extra_repo,omitempty" json:"extra_repo,omitempty"`

	Runtime_pacman_conf string `yaml:"runtime_pacman_conf,omitempty" json:"runtime_pacman_conf,omitempty"`
}

type DsPacstrapRepo struct {
	Name string `yaml:"name,omitempty" json:"name"`

	Server string `yaml:"server,omitempty" json:"server"`

	Siglevel string `yaml:"siglevel,omitempty" json:"siglevel,omitempty"`
}

type DsDebootstrap struct {
	Suite string `yaml:"suite,omitempty" json:"suite,omitempty"`

	Mirror string `yaml:"mirror,omitempty" json:"mirror,omitempty"`

	Variant string `yaml:"variant,omitempty" json:"variant,omitempty"`

	Components string `yaml:"components,omitempty" json:"components,omitempty"`

	Include_package []string `yaml:"include_package,omitempty" json:"include_package,omitempty"`

	Base_package []string `yaml:"base_package,omitempty" json:"base_package,omitempty"`

	Extra_repo []DsDebootstrapRepo `yaml:"extra_repo,omitempty" json:"extra_repo,omitempty"`
}

type DsDebootstrapRepo struct {
	Name string `yaml:"name,omitempty" json:"name"`

	Url string `yaml:"url,omitempty" json:"url"`

	Suite string `yaml:"suite,omitempty" json:"suite,omitempty"`

	Components string `yaml:"components,omitempty" json:"components,omitempty"`
}

type DsAlpineBootstrap struct {
	Mirror_url string `yaml:"mirror_url,omitempty" json:"mirror_url,omitempty"`
}

type DsBootloader struct {
	Install_template string `yaml:"install_template,omitempty" json:"install_template,omitempty"`

	Initramfs_template string `yaml:"initramfs_template,omitempty" json:"initramfs_template,omitempty"`

	Fstab_template string `yaml:"fstab_template,omitempty" json:"fstab_template,omitempty"`
}

type DsDnf struct {
	Max_parallel_downloads int64 `yaml:"max_parallel_downloads,omitempty" json:"max_parallel_downloads,omitempty"`

	Fastestmirror bool `yaml:"fastestmirror,omitempty" json:"fastestmirror,omitempty"`
}
