// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The BUILT-IN `file` plugin's OWN CUE schema — the typed plugin_input for the `file`
// verb (a stat-based path probe in do:assert, a touch/cat+chmod file-creation in
// do:act). It is the SINGLE SOURCE for this plugin's params, used two ways (the same
// contract the reference exampleprobe and core `spec` use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by task cue:gen,
//     which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a TYPED
//     struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the builtin serves this source over the
//     Describe channel (InProcTransport) exactly like an external serves it over
//     gRPC; the host splices it onto the base (base ++ plugin) and validates every
//     authored `file` step's plugin_input against #FileInput.
//
// SELF-CONTAINED: it references NO base def — the `contains` matcher shape reproduces
// standalone under plugin-private def names (#FileContains / #FileMatcher /
// #FileMatchOp, so there is NO collision with the base #Matcher / #MatchOpMap when
// base ++ plugin compiles), so it compiles standalone (gengotypes +
// the load-gate compile) AND splices onto the base.
//
// `file` is DUAL-NATURED — a state-provision verb that is BOTH a CheckVerbProvider
// (RunVerb → r.runFile, the stat probe that keeps the live *Runner) AND a
// ProvisionActor (RenderProvisionScript → mkdir/touch/cat+chmod, the RUNTIME
// file-creation act, distinct from the BUILD-time COPY directives the write:/copy:
// verbs emit). The seven file-EXCLUSIVE fields (file/exists/owner/group_of/filetype/
// contains/sha256, read ONLY by the `file` verb) LEFT #Op for this def. `mode` is the
// shared companion: it STAYS in base #Op (the copy/write install verbs read Op.Mode at
// deploy) yet is reproduced here so the file plugin reads its own plugin_input.mode —
// exactly how `gid` is shared between unix_group and user. The probe asserts mode/owner/
// group_of/filetype/contains/sha256 when set; the act renders touch + `chmod <mode>`.
type FileInput struct {
	// file — the absolute path the stat probe inspects (assert) / the file
	// touch/cat creates (act). The verb discriminator.
	File string `yaml:"file,omitempty" json:"file"`

	// exists — whether the path is expected to exist (default true). Tri-state pointer
	// so an absent key means "expected to exist".
	Exists *bool `yaml:"exists,omitempty" json:"exists,omitempty"`

	// mode — optional expected octal permission string (assert) / `chmod` arg (act).
	// The SHARED companion: also a base #Op modifier the copy/write verbs read.
	Mode string `yaml:"mode,omitempty" json:"mode,omitempty"`

	// owner — optional expected owning user name (stat %U).
	Owner string `yaml:"owner,omitempty" json:"owner,omitempty"`

	// group_of — optional expected owning group name (stat %G). Spelled group_of
	// because `group` is a reserved kind word (the getent-group verb is unix_group).
	GroupOf string `yaml:"group_of,omitempty" json:"group_of,omitempty"`

	// filetype — optional expected node type (goss-parity short forms).
	Filetype string `yaml:"filetype,omitempty" json:"filetype,omitempty"`

	// contains — optional goss-style matchers the file's contents must satisfy.
	// Reproduces the contains-default matcher-list shape standalone (scalar / single
	// operator-map / list); a bare scalar means `contains` at decode (decodeContainsList).
	Contains FileContains `yaml:"contains,omitempty" json:"contains,omitempty"`

	// sha256 — optional expected SHA-256 hex digest of the file's contents.
	Sha256 string `yaml:"sha256,omitempty" json:"sha256,omitempty"`
}

// #FileContains is the contains-default matcher list: a single matcher OR a list.
type FileContains any /* CUE disjunction: (bool|string|list|struct|number) */

// #FileMatcher mirrors the base #Matcher: a bare scalar (implicit match) or a
// single-operator map.
type FileMatcher any /* CUE disjunction: (bool|string|struct|number) */

// #FileMatchOp mirrors the base #MatchOpMap: exactly one matcher operator key.
type FileMatchOp map[string]any
