// Pure structural methods on the generated/aliased spec types, relocated here
// from package main by the CUE-single-source cutover (WF-B THE REPOINT). A method
// on an aliased type (e.g. type BoxConfig = spec.Box in package main) cannot be
// declared in package main — the type is foreign — so every method that touches
// ONLY the type's own fields + the stdlib lives here, beside the type it acts on.
// Methods that reach package-main internals (VerbCatalog, Phase/Venue, EmitOpts,
// the readiness/preempt consts, …) stay in package main as free functions taking
// a *spec.X — they are NOT here. STANDALONE: this package imports nothing from
// package main.
package spec

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// ---------------------------------------------------------------------------
// Op — structural verb vocabulary (Kind / verbsSet / StringFields). The check
// SEMANTICS (EffectiveDo / EffectiveContexts / InContext / ExpandVars) consult
// package-main's VerbCatalog and stay free functions in main.
// ---------------------------------------------------------------------------

// OpVerbs (the canonical verb-discriminator set used by Kind()'s error message)
// is CUE-derived from #OpVerb — see vocab_gen.go (regenerated by `task cue:gen`).

// PluginInputStr returns the string value of plugin_input[verb] when this Op is a
// `plugin: <verb>` op carrying that key — "" otherwise. The ONE home (R3) for the host
// check runner (checkrun.go) AND the k8sgen plugin's probe builder (candy/plugin-k8sgen),
// both of which read a migrated `plugin: http`/`addr`/`file`/`command` check subject.
func (c *Op) PluginInputStr(verb string) string {
	if c == nil || c.Plugin != verb || c.PluginInput == nil {
		return ""
	}
	if v, ok := c.PluginInput[verb].(string); ok {
		return v
	}
	return ""
}

// Kind returns the single verb set on the Op, or an error when zero or multiple
// are set (the exactly-one-verb rule).
func (c *Op) Kind() (string, error) {
	set := c.VerbsSet()
	if len(set) == 0 {
		return "", fmt.Errorf("check has no verb set (expected exactly one of: %s)", strings.Join(OpVerbs, ", "))
	}
	if len(set) > 1 {
		return "", fmt.Errorf("check has multiple verbs set (%s); exactly one is required", strings.Join(set, ", "))
	}
	return set[0], nil
}

//nolint:gocyclo // flat exactly-one-verb enumeration over the Op verb fields; extraction would relocate the cases without clarifying
func (c *Op) VerbsSet() []string {
	var set []string
	if c.Mkdir != "" {
		set = append(set, "mkdir")
	}
	if c.Copy != "" {
		set = append(set, "copy")
	}
	if c.Write != "" {
		set = append(set, "write")
	}
	if c.Link != "" {
		set = append(set, "link")
	}
	if c.Download != "" {
		set = append(set, "download")
	}
	if c.Setcap != "" {
		set = append(set, "setcap")
	}
	if c.Build != "" {
		set = append(set, "build")
	}
	// `file` is NO LONGER a verb — it left #OpVerb in the file→plugin extraction (a file
	// check/run is now `plugin: file` + #FileInput; exists/owner/group_of/filetype/contains/
	// sha256 moved into plugin_input, and the SHARED `mode` rides plugin_input on a file step
	// while staying an #Op modifier for copy/write). Op no longer carries a File field, so it
	// contributes no verb.
	// `package` is NO LONGER a verb — it left #OpVerb in the package→plugin extraction
	// (a package check/run is now `plugin: package` + #PackageInput; installed/version/
	// package_map moved into plugin_input). Op no longer carries a Package field, so it
	// contributes no verb. The shared `exclude_distro` skip modifier stays on #Op.
	// `service` is NO LONGER a verb — it left #OpVerb in the service→plugin extraction
	// (a service check/run is now `plugin: service` + #ServiceInput, running/enabled moved
	// into plugin_input). Op no longer carries a Service field, so it contributes no verb.
	// `command` is NO LONGER a verb — it left #OpVerb in the command→plugin extraction
	// (a command check/run is now `plugin: command` + #CommandInput). It stays an #Op
	// modifier ONLY: the live-container verbs wl/libvirt read it as their argv, and the
	// command plugin's install-emit rehydrates it onto an OpStep for emitCmd. So Op.Command
	// never contributes a verb here.
	if c.Cdp != "" {
		set = append(set, "cdp")
	}
	if c.Wl != "" {
		set = append(set, "wl")
	}
	if c.Dbus != "" {
		set = append(set, "dbus")
	}
	if c.Vnc != "" {
		set = append(set, "vnc")
	}
	if c.Mcp != "" {
		set = append(set, "mcp")
	}
	if c.Record != "" {
		set = append(set, "record")
	}
	if c.Spice != "" {
		set = append(set, "spice")
	}
	if c.Libvirt != "" {
		set = append(set, "libvirt")
	}
	if c.Kube != "" {
		set = append(set, "kube")
	}
	if c.Adb != "" {
		set = append(set, "adb")
	}
	if c.Appium != "" {
		set = append(set, "appium")
	}
	if c.Summarize != "" {
		set = append(set, "summarize")
	}
	if c.Kill != "" {
		set = append(set, "kill")
	}
	if c.Plugin != "" {
		set = append(set, "plugin")
	}
	return set
}

// StringFields returns pointers to every string-valued modifier field, for the
// in-place ${VAR} expansion driven by ExpandVars (free function in main).
func (c *Op) StringFields() []*string {
	return []*string{
		&c.Command,
		&c.ID, &c.Description, &c.Timeout,
		// `mode` is the SHARED file/copy/write modifier kept on #Op (owner/group_of/filetype/
		// sha256 left with the file verb into #FileInput; file's plugin_input is expanded by
		// the plugin path, not here).
		&c.Mode,
		&c.Method, &c.RequestBody,
		// Test-mode live-container verb discriminators + modifiers.
		&c.Cdp, &c.Wl, &c.Dbus, &c.Vnc, &c.Mcp,
		&c.Record, &c.Spice, &c.Libvirt, &c.Kube,
		&c.Adb, &c.Appium,
		// kube + shared resource-identity modifiers
		&c.Name, &c.Namespace, &c.Label, &c.Cluster, &c.Manifest,
		&c.KubeKind, &c.KubeContext, &c.Kubeconfig,
		&c.KubeResource, &c.KubeGroup, &c.KubeVersion,
		&c.Tab, &c.Expression, &c.URL, &c.Selector,
		&c.Dest, &c.Path, &c.Artifact,
		&c.Button, &c.Text, &c.KeyName, &c.Combo,
		&c.Direction, &c.Target, &c.Action, &c.Query,
		// mcp-specific modifiers
		&c.McpName, &c.Tool, &c.URI, &c.Input,
		// adb / appium-specific modifiers
		&c.Apk, &c.Property, &c.Caps, &c.Strategy, &c.Session,
		// record-specific modifiers
		&c.RecordName, &c.RecordMode,
		// Capture/Eventually/RetryInterval are identifiers/durations but still run
		// through the expander for symmetry.
		&c.Capture, &c.CaptureExtract, &c.Eventually, &c.RetryInterval,
		// kill: verb's PID arg is typically ${CAPTURED:<name>} from a prior
		// background command; Signal is a literal but expanded for symmetry.
		&c.Kill, &c.Signal,
		// Install/build verb discriminators + path-like modifiers (the former
		// Task surface). Content is INTENTIONALLY excluded — write: bodies are
		// verbatim bytes, never ${VAR}-substituted (matches the task rule).
		&c.Mkdir, &c.Copy, &c.Write, &c.Link, &c.Download, &c.Setcap, &c.Build,
		&c.RunAs, &c.To, &c.Extract,
	}
}

// ---------------------------------------------------------------------------
// Step — the two predicates not already in union_types.go.
// ---------------------------------------------------------------------------

// IsInclude reports whether the step is an include: composition directive.
func (s *Step) IsInclude() bool { return s.Include != "" }

// Mutates reports whether the step changes system state (run / agent-run).
// `charly check live` (verify-only mode) skips mutating steps.
func (s *Step) Mutates() bool { return s.Run != "" || s.AgentRun != "" }

// ---------------------------------------------------------------------------
// Box (BoxConfig)
// ---------------------------------------------------------------------------

// IsEnabled reports whether the box is enabled (default true when unset).
func (ic *Box) IsEnabled() bool {
	if ic.Enabled == nil {
		return true
	}
	return *ic.Enabled
}

// HasBaseFromConflict reports whether the box authored BOTH base: and from:.
func (ic *Box) HasBaseFromConflict() bool {
	return ic.From != "" && ic.Base != ""
}

// ---------------------------------------------------------------------------
// Builder (BuilderDef)
// ---------------------------------------------------------------------------

// IsBootstrap reports whether the builder is a bootstrap builder.
func (b *Builder) IsBootstrap() bool {
	if b == nil {
		return false
	}
	return b.Kind == "bootstrap"
}

// ---------------------------------------------------------------------------
// Distro (DistroDef — the build vocabulary distro)
// ---------------------------------------------------------------------------

// PrimaryFormat returns the distro's primary (non-secondary) package format.
func (d *Distro) PrimaryFormat() string {
	if d == nil {
		return ""
	}
	names := make([]string, 0, len(d.Format))
	for name := range d.Format {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if fd := d.Format[name]; fd != nil && fd.Secondary {
			continue // secondary build format (declared in YAML), never primary
		}
		return name
	}
	return ""
}

// LocalPkgFormat picks the format whose local_pkg block to build the charly
// toolchain from: the caller's primary format, then the distro's own
// PrimaryFormat, then any localpkg-capable format (deterministic).
func (d *Distro) LocalPkgFormat(primaryFormat string) (string, *LocalPkg) {
	if d == nil {
		return "", nil
	}
	for _, fmtName := range []string{primaryFormat, d.PrimaryFormat()} {
		if fmtName == "" {
			continue
		}
		if fd := d.Format[fmtName]; fd != nil && fd.LocalPkg != nil {
			return fmtName, fd.LocalPkg
		}
	}
	names := make([]string, 0, len(d.Format))
	for name := range d.Format {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if fd := d.Format[name]; fd != nil && fd.LocalPkg != nil {
			return name, fd.LocalPkg
		}
	}
	return "", nil
}

// ---------------------------------------------------------------------------
// EphemeralLifetime
// ---------------------------------------------------------------------------

// EffectiveTTL returns the configured TTL, or the 1h default.
func (e *EphemeralLifetime) EffectiveTTL() time.Duration {
	if e == nil {
		return 0
	}
	if e.TTL == "" {
		return time.Hour
	}
	d, err := time.ParseDuration(e.TTL)
	if err != nil || d <= 0 {
		return time.Hour
	}
	return d
}

// EffectiveNamingPattern returns the configured naming pattern, or the default.
func (e *EphemeralLifetime) EffectiveNamingPattern() string {
	if e == nil || e.NamingPattern == "" {
		return "{{.Source}}-eph-{{.UUID6}}"
	}
	return e.NamingPattern
}

// ---------------------------------------------------------------------------
// Iterate (IterateConfig) — NotesEnabled is pure; EffectiveMCPEndpoint reaches
// a package-main default and stays a free function there.
// ---------------------------------------------------------------------------

// NotesEnabled reports whether the iteration NOTES.md memory is on (default on).
func (i *Iterate) NotesEnabled() bool {
	if i == nil || i.Note == nil {
		return true
	}
	return *i.Note
}

// ---------------------------------------------------------------------------
// Resource (ResourceDef)
// ---------------------------------------------------------------------------

// HasSelector reports whether the resource carries a GPU selector.
func (r *Resource) HasSelector() bool {
	return r != nil && r.Gpu != nil
}

// ---------------------------------------------------------------------------
// CandyService (ServiceEntry)
// ---------------------------------------------------------------------------

// EffectiveScope returns the service scope, defaulting to "system".
func (e *CandyService) EffectiveScope() string {
	if e == nil || e.Scope == "" {
		return "system"
	}
	return e.Scope
}

// IsPackaged reports whether the service is the packaged (use_packaged) form.
func (e *CandyService) IsPackaged() bool {
	return e != nil && e.UsePackaged != ""
}

// ---------------------------------------------------------------------------
// Android (AndroidSpec)
// ---------------------------------------------------------------------------

// IsEndpoint reports whether the device targets a remote adb endpoint.
func (a *Android) IsEndpoint() bool {
	return a != nil && a.Adb != nil && a.Adb.Host != ""
}

// EffectiveSerial returns the device serial, defaulting to the emulator serial.
func (a *Android) EffectiveSerial() string {
	if a != nil && a.Serial != "" {
		return a.Serial
	}
	return "emulator-5554"
}

// ---------------------------------------------------------------------------
// ApkPackageSpec
// ---------------------------------------------------------------------------

// EffectiveSource returns the APK source store, defaulting to apk-pure.
func (s ApkPackageSpec) EffectiveSource() string {
	if s.Source != "" {
		return s.Source
	}
	return "apk-pure"
}

// EffectiveArch returns the APK ABI, defaulting to x86_64.
func (s ApkPackageSpec) EffectiveArch() string {
	if s.Arch != "" {
		return s.Arch
	}
	return "x86_64"
}

// ---------------------------------------------------------------------------
// Deploy (BundleNode) — the pure tree/classification predicates. WalkPreOrder /
// WalkPostOrder reach package-main's sortedNestedKeys and stay free functions.
// ---------------------------------------------------------------------------

// IsDisposable reports whether the deploy is safe to destroy + rebuild.
func (c Deploy) IsDisposable() bool {
	return (c.Disposable != nil && *c.Disposable) || c.IsEphemeral()
}

// IsGroup reports whether this is a GROUP bundle — no workload cross-ref but
// with sibling members (the cross-deployment subject+driver shape).
func (c Deploy) IsGroup() bool {
	return c.Target == "" && len(c.Members) > 0
}

// IsEphemeral reports whether this deploy is marked ephemeral.
func (c Deploy) IsEphemeral() bool {
	return c.Ephemeral != nil
}

// IsPreemptible reports whether this deploy holds a preemptible exclusive
// resource (graceful-stop side).
func (c Deploy) IsPreemptible() bool {
	return c.Preemptible != nil && len(c.Preemptible.Holds) > 0
}

// PreemptionHolds returns the exclusive-resource token(s) this deploy occupies.
func (c Deploy) PreemptionHolds() []string {
	if c.Preemptible == nil {
		return nil
	}
	return c.Preemptible.Holds
}

// RequiredExclusive returns the exclusive-resource token(s) this deploy claims.
func (c Deploy) RequiredExclusive() []string {
	return c.RequiresExclusive
}

// RequiredShared returns the shared-mode resource token(s) this deploy claims.
func (c Deploy) RequiredShared() []string {
	return c.RequiresShared
}

// LifecycleTag returns the deploy's lifecycle tag.
func (c Deploy) LifecycleTag() string {
	return c.Lifecycle
}

// HasChildren reports whether this node has any nested deployments.
func (n *Deploy) HasChildren() bool {
	return n != nil && len(n.Children) > 0
}

// ---------------------------------------------------------------------------
// Shell (ShellConfig) + DeployShellOverlay — ByShell synthesizes the per-shell
// map from the explicit bash/zsh/fish/sh pointers (the former custom-unmarshal
// map). A non-nil per-shell pointer = that shell was authored.
// ---------------------------------------------------------------------------

func shellMap(bash, zsh, fish, sh *ShellSpec) map[string]*ShellSpec {
	out := map[string]*ShellSpec{}
	if bash != nil {
		out["bash"] = bash
	}
	if zsh != nil {
		out["zsh"] = zsh
	}
	if fish != nil {
		out["fish"] = fish
	}
	if sh != nil {
		out["sh"] = sh
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// ByShell returns the per-shell overlay map (nil when none authored).
func (s *Shell) ByShell() map[string]*ShellSpec {
	if s == nil {
		return nil
	}
	return shellMap(s.Bash, s.Zsh, s.Fish, s.Sh)
}

// ByShell returns the per-shell overlay map (nil when none authored).
func (o *DeployShellOverlay) ByShell() map[string]*ShellSpec {
	if o == nil {
		return nil
	}
	return shellMap(o.Bash, o.Zsh, o.Fish, o.Sh)
}
